(function(global){
  'use strict';
  var reg=null,waiting=null,pendingVersion='',pendingNotes='';
  function id(x){return document.getElementById(x);}
  function current(){try{return localStorage.getItem('moshaver_admin_installed_version')||((global.APP_CONFIG&&global.APP_CONFIG.APP_VERSION)||'');}catch(e){return(global.APP_CONFIG&&global.APP_CONFIG.APP_VERSION)||'';}}
  function setCurrent(v){try{if(v)localStorage.setItem('moshaver_admin_installed_version',v);}catch(e){}}
  function show(){if(id('updateModal'))id('updateModal').className='update-modal';if(id('backdrop'))id('backdrop').className='backdrop';if(id('updateNotes')){id('updateNotes').textContent=pendingNotes||'';id('updateNotes').className=pendingNotes?'release-note':'release-note hidden';}}
  function hide(){if(id('updateModal'))id('updateModal').className='update-modal hidden';if(id('backdrop'))id('backdrop').className='backdrop hidden';}
  function check(){var x=new XMLHttpRequest();x.open('GET','./version.json?t='+new Date().getTime(),true);x.onreadystatechange=function(){if(x.readyState!==4||x.status<200||x.status>=300)return;try{var d=JSON.parse(x.responseText||'{}'),v=d.version||'',c=current();pendingNotes=d.notes||'';if(!c&&v){setCurrent(v);return;}if(v&&c&&v!==c){pendingVersion=v;if(reg)reg.update();show();}}catch(e){}};x.send();}
  function init(){if(location.hostname==='localhost'||location.hostname==='127.0.0.1'){if('serviceWorker'in navigator)navigator.serviceWorker.getRegistrations().then(function(rs){for(var i=0;i<rs.length;i++)rs[i].unregister();});return;}if(id('applyUpdateBtn'))id('applyUpdateBtn').onclick=function(){setCurrent(pendingVersion);if(waiting)waiting.postMessage({type:'SKIP_WAITING'});else location.reload(true);};if(id('laterUpdateBtn'))id('laterUpdateBtn').onclick=hide;if(!('serviceWorker'in navigator)){check();return;}navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(function(r){reg=r;if(r.waiting){waiting=r.waiting;show();}r.addEventListener('updatefound',function(){var w=r.installing;if(!w)return;w.addEventListener('statechange',function(){if(w.state==='installed'&&navigator.serviceWorker.controller){waiting=w;show();}});});setTimeout(function(){r.update();},1000);check();setInterval(check,90000);}).catch(check);navigator.serviceWorker.addEventListener('controllerchange',function(){if(pendingVersion)setCurrent(pendingVersion);location.reload();});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
