'use strict';
var http=require('http'),cp=require('child_process'),path=require('path'),fs=require('fs');
var root=path.resolve(__dirname,'..'),tmp=path.join(root,'data','smoke-'+process.pid+'.sqlite');try{fs.unlinkSync(tmp);}catch(e){}
var env=Object.assign({},process.env,{NODE_ENV:'test',PORT:'4199',DATABASE_PATH:tmp,CORS_ORIGINS:'http://localhost:8080,http://localhost:8081',ADMIN_USERNAME:'admin',ADMIN_PASSWORD:'SmokeAdmin123!',STUDENT_USERNAME:'student',STUDENT_PASSWORD:'SmokeStudent123!',ALLOW_BEARER_AUTH:'false',LOGIN_MAX_FAILURES:'5',LOGIN_BLOCK_MINUTES:'1'});
var child=cp.spawn(process.execPath,['--experimental-sqlite',path.join(root,'src/server.js')],{cwd:root,env:env,stdio:['ignore','pipe','pipe']});var done=false,started=false;
function cleanup(code){if(done)return;done=true;try{child.kill('SIGTERM');}catch(e){}setTimeout(function(){['','-wal','-shm'].forEach(function(x){try{fs.unlinkSync(tmp+x);}catch(e){}});process.exit(code);},300);}
child.stdout.on('data',function(b){var t=b.toString();process.stdout.write(t);if(t.indexOf('Moshaver | مشاور API started')>=0)runChecks();});child.stderr.on('data',function(b){process.stderr.write(b);});child.on('exit',function(c){if(!done)cleanup(c||1);});
function cookieFrom(res){var h=res.headers['set-cookie'];if(!h||!h.length)return '';return String(h[0]).split(';')[0];}
function request(method,pathname,body,auth,origin){return new Promise(function(resolve,reject){var payload=body!=null?JSON.stringify(body):null,headers={Accept:'application/json'};if(payload){headers['Content-Type']='application/json';headers['Content-Length']=Buffer.byteLength(payload);}if(auth&&auth.cookie)headers.Cookie=auth.cookie;if(auth&&auth.csrf)headers['X-CSRF-Token']=auth.csrf;if(origin)headers.Origin=origin;var req=http.request({host:'127.0.0.1',port:4199,path:pathname,method:method,headers:headers},function(res){var chunks=[];res.on('data',function(c){chunks.push(c);});res.on('end',function(){var text=Buffer.concat(chunks).toString('utf8'),json=null;try{json=JSON.parse(text);}catch(e){}resolve({status:res.statusCode,headers:res.headers,json:json,text:text});});});req.on('error',reject);if(payload)req.write(payload);req.end();});}
function assert(ok,msg){if(!ok)throw new Error(msg);}
async function login(username,password,origin){var r=await request('POST','/api/v1/auth/login',{username:username,password:password},null,origin);assert(r.status===200,'login '+username+' '+r.text);assert(r.json&&r.json.data&&r.json.data.csrfToken,'csrf on login');return{cookie:cookieFrom(r),csrf:r.json.data.csrfToken,user:r.json.data.user};}
function waitForSse(auth,origin,eventName,trigger){return new Promise(function(resolve,reject){var settled=false,req,timer=setTimeout(function(){if(!settled){settled=true;try{req.destroy();}catch(e){}reject(new Error('SSE timeout waiting for '+eventName));}},5000);var headers={Accept:'text/event-stream',Cookie:auth.cookie,Origin:origin};req=http.request({host:'127.0.0.1',port:4199,path:'/api/v1/events',method:'GET',headers:headers},function(res){if(res.statusCode!==200){settled=true;clearTimeout(timer);return reject(new Error('SSE status '+res.statusCode));}var buf='';res.on('data',function(c){buf+=c.toString('utf8');if(buf.indexOf('event: '+eventName)>=0&&!settled){settled=true;clearTimeout(timer);try{req.destroy();}catch(e){}resolve(buf);}});setTimeout(function(){Promise.resolve().then(trigger).catch(function(e){if(!settled){settled=true;clearTimeout(timer);req.destroy();reject(e);}});},120);});req.on('error',function(e){if(!settled){settled=true;clearTimeout(timer);reject(e);}});req.end();});}
async function runChecks(){if(started)return;started=true;try{
 var r=await request('GET','/');assert(r.status===200,'GET /');r=await request('GET','/health');assert(r.status===200&&r.json&&r.json.ok,'health');assert(!r.text.includes('node'),'health should not expose node version');
 r=await request('OPTIONS','/api/v1/auth/login',null,null,'http://localhost:8081');assert(r.status===204,'allowed CORS');assert(r.headers['access-control-allow-credentials']==='true','credentials CORS');r=await request('OPTIONS','/api/v1/auth/login',null,null,'http://evil.test');assert(r.status===403,'blocked CORS');
 var admin=await login('admin','SmokeAdmin123!','http://localhost:8081');var student=await login('student','SmokeStudent123!','http://localhost:8080');assert(admin.cookie.indexOf('moshaver_session=')===0,'admin cookie');assert(student.cookie.indexOf('moshaver_session=')===0,'student cookie');
 var loginCsrf=student.csrf;
 var noCsrf=await request('POST','/api/v1/activity',{eventType:'task.opened'}, {cookie:student.cookie},'http://localhost:8080');assert(noCsrf.status===403,'CSRF must block mutation');
 var me=await request('GET','/api/v1/auth/me',null,student,'http://localhost:8080');assert(me.status===200&&me.json.data.csrfToken,'me');var meCsrf1=me.json.data.csrfToken;
 var meAgain=await request('GET','/api/v1/auth/me',null,student,'http://localhost:8080');assert(meAgain.status===200&&meAgain.json.data.csrfToken,'second me');var meCsrf2=meAgain.json.data.csrfToken;
 assert(loginCsrf===meCsrf1&&meCsrf1===meCsrf2,'CSRF token must remain stable across auth/me calls');
 var originalTokenMutation=await request('POST','/api/v1/activity',{eventType:'task.opened',metadata:{source:'stable-csrf-smoke'}},{cookie:student.cookie,csrf:loginCsrf},'http://localhost:8080');assert(originalTokenMutation.status===201,'login CSRF must remain valid after auth/me calls '+originalTokenMutation.text);
 var badTokenMutation=await request('POST','/api/v1/activity',{eventType:'task.opened',metadata:{}},{cookie:student.cookie,csrf:'definitely-wrong-csrf-token'},'http://localhost:8080');assert(badTokenMutation.status===403,'wrong CSRF token must be rejected');
 student.csrf=meCsrf2;
 var students=await request('GET','/api/v1/admin/students?limit=10',null,admin,'http://localhost:8081');assert(students.status===200&&students.json.data.items.length&&students.json.data.total>=1,'paginated students');var sid=students.json.data.items[0].id;
 var fixturePaths=[path.join(root,'../examples/json/plan-day.example.json'),path.join(root,'../examples/json/exam-with-questions.example.json'),path.join(root,'../examples/json/complete-import.example.json'),path.join(root,'../moshaver-30-day-all-task-types.json')];
 for(var fixtureIndex=0;fixtureIndex<fixturePaths.length;fixtureIndex++){var fixture=JSON.parse(fs.readFileSync(fixturePaths[fixtureIndex],'utf8')),fixturePreview=await request('POST','/api/v1/admin/import/preview',{studentId:sid,data:fixture},admin,'http://localhost:8081');assert(fixturePreview.status===200&&fixturePreview.json.data.errors.length===0,'fixture preview '+path.basename(fixturePaths[fixtureIndex])+' '+fixturePreview.text);}
 var date='2026-09-20',payload={schemaVersion:1,studentId:sid,plans:[{planDate:date,dayLabel:'شنبه',persianDate:'نمونه',title:'Smoke imported day',published:false,tasks:[{start:'07:00',end:'08:00',type:'study',subject:'روان‌شناسی',title:'مطالعه نمونه',pages:'1-5',testCount:0,note:'smoke'}]}],exams:[{title:'Smoke Exam',persianDate:'نمونه',isoDate:'2026-09-21',note:'smoke',status:'upcoming',syllabus:[{subject:'روان‌شناسی',description:'درس ۱',required:true,track:''}]}]};
 var preview=await request('POST','/api/v1/admin/import/preview',{studentId:sid,data:payload},admin,'http://localhost:8081');assert(preview.status===200&&preview.json.data.errors.length===0,'import preview '+preview.text);
 var commit=await request('POST','/api/v1/admin/import/commit',{studentId:sid,data:payload,replaceExistingPlans:true,replaceExistingExams:true,publishImported:true,sourceName:'smoke'},admin,'http://localhost:8081');assert(commit.status===201&&commit.json.data.plans===1,'import commit '+commit.text);
 var roundDate='2026-10-04',roundTitle='Round-trip Exam',roundPayload={schemaVersion:2,plans:[{planDate:roundDate,title:'Round-trip plan',published:true,tasks:[{start:'08:00',end:'09:00',type:'exam',title:roundTitle,examRef:'round-exam'}]}],exams:[{ref:'round-exam',title:roundTitle,persianDate:'نمونه',isoDate:roundDate,openAt:'2026-10-04T08:00:00+03:30',closeAt:'2026-10-04T12:00:00+03:30',durationMinutes:45,maxAttempts:3,published:true,questions:[{question:'پاسخ درست؟',options:['الف','ب','ج','د'],correctOption:'b',book:'کتاب نمونه',chapter:'فصل نمونه',lesson:'درس نمونه',topic:'مبحث نمونه',hint:'راهنمای نمونه'}]}]};
 var roundPreview=await request('POST','/api/v1/admin/import/preview',{studentId:sid,data:roundPayload},admin,'http://localhost:8081');assert(roundPreview.status===200&&roundPreview.json.data.errors.length===0,'round-trip preview '+roundPreview.text);
 var roundDraft=await request('POST','/api/v1/admin/import/commit',{studentId:sid,data:roundPayload,replaceExistingPlans:true,replaceExistingExams:true,publishImported:false,sourceName:'round-trip draft'},admin,'http://localhost:8081');assert(roundDraft.status===201&&!roundDraft.json.data.published,'draft import '+roundDraft.text);
 var draftPlan=await request('GET','/api/v1/admin/plans?studentId='+sid+'&date='+roundDate,null,admin,'http://localhost:8081');assert(draftPlan.status===200&&!draftPlan.json.data.published,'draft import must keep plan hidden');
 var draftExams=await request('GET','/api/v1/admin/exams?studentId='+sid,null,admin,'http://localhost:8081'),draftExam=draftExams.json.data.filter(function(x){return x.title===roundTitle;})[0];assert(draftExam&&!draftExam.published&&draftExam.maxAttempts===3,'draft exam and maxAttempts must persist');var oldExamId=draftExam.id,oldQuizId=draftExam.delivery.quizId;
 var exported=await request('GET','/api/v1/admin/export/json?studentId='+sid+'&from='+roundDate+'&to='+roundDate,null,admin,'http://localhost:8081');assert(exported.status===200&&exported.json.data.plans[0].tasks[0].examRef===oldExamId&&!Object.prototype.hasOwnProperty.call(exported.json.data.plans[0].tasks[0],'examId'),'portable examRef export');assert(exported.json.data.exams[0].maxAttempts===3,'maxAttempts export');assert(exported.json.data.exams[0].questions[0].topic==='مبحث نمونه'&&exported.json.data.exams[0].questions[0].hint==='راهنمای نمونه','question metadata round-trip');
 var examsOnly=await request('GET','/api/v1/admin/export/json?studentId='+sid+'&scope=exams',null,admin,'http://localhost:8081');assert(examsOnly.status===200&&examsOnly.json.data.scope==='exams'&&examsOnly.json.data.plans.length===0&&examsOnly.json.data.exams.some(function(x){return x.title===roundTitle&&x.questions.length===1;}),'exam-only export retains questions');
 var examTemplate=await request('GET','/api/v1/admin/import/template?studentId='+sid+'&scope=exams',null,admin,'http://localhost:8081');assert(examTemplate.status===200&&examTemplate.json.data.scope==='exams'&&examTemplate.json.data.plans.length===0&&examTemplate.json.data.exams.length===1,'exam-only template');
 var roundReplace=await request('POST','/api/v1/admin/import/commit',{studentId:sid,data:exported.json.data,replaceExistingPlans:true,replaceExistingExams:true,publishImported:true,sourceName:'round-trip replace'},admin,'http://localhost:8081');assert(roundReplace.status===201&&roundReplace.json.data.published,'round-trip replace '+roundReplace.text);
 var replacedPlan=await request('GET','/api/v1/admin/plans?studentId='+sid+'&date='+roundDate,null,admin,'http://localhost:8081');assert(replacedPlan.json.data.tasks[0].examId===oldExamId&&replacedPlan.json.data.published,'round-trip must preserve link and publish');
 var replacedExams=await request('GET','/api/v1/admin/exams?studentId='+sid,null,admin,'http://localhost:8081'),replacedExam=replacedExams.json.data.filter(function(x){return x.title===roundTitle;})[0];assert(replacedExam.id===oldExamId&&replacedExam.delivery.quizId!==oldQuizId&&replacedExam.maxAttempts===3,'exam identity/history boundary must be stable');
 var retiredQuiz=await request('GET','/api/v1/quizzes/'+oldQuizId,null,student,'http://localhost:8080');assert(retiredQuiz.status===404,'replaced quiz must be retired');
 var invalidImport={schemaVersion:99,plans:[{planDate:'2026-02-30',tasks:[{start:'09:00',end:'08:00',type:'study',title:'bad'}]}],exams:[{title:'bad',isoDate:'2026-10-05',questions:[{question:'bad',options:['x','x','','z'],correctOption:'a'}]}]};
 var invalidPreview=await request('POST','/api/v1/admin/import/preview',{studentId:sid,data:invalidImport},admin,'http://localhost:8081');assert(invalidPreview.status===200&&invalidPreview.json.data.errors.length>=3,'strict import preview');
 var plan=await request('GET','/api/v1/plans?date='+date,null,student,'http://localhost:8080');assert(plan.status===200&&plan.json.data&&plan.json.data.tasks.length===1,'student published plan');var taskId=plan.json.data.tasks[0].id;
 var today=await request('GET','/api/v1/student/today',null,student,'http://localhost:8080');assert(today.status===200&&today.json.data.today&&today.json.data.dueReviews.length<=8,'bounded student today');
 var ss=await request('POST','/api/v1/study-sessions/start',{taskId:taskId,deviceLabel:'Smoke Browser'},student,'http://localhost:8080');assert(ss.status===201&&ss.json.data.id,'session start '+ss.text);var sessionId=ss.json.data.id;
 var pause=await request('POST','/api/v1/study-sessions/'+sessionId+'/pause',{},student,'http://localhost:8080');assert(pause.status===200&&pause.json.data.paused,'session pause');var resume=await request('POST','/api/v1/study-sessions/'+sessionId+'/resume',{},student,'http://localhost:8080');assert(resume.status===200&&!resume.json.data.paused,'session resume');
 var resumeAgain=await request('POST','/api/v1/study-sessions/'+sessionId+'/resume',{},student,'http://localhost:8080');assert(resumeAgain.status===200&&!resumeAgain.json.data.paused,'session resume idempotent');
 var issue=await request('POST','/api/v1/task-issues',{taskId:taskId,issueType:'فراموش کردم',note:'smoke issue'},student,'http://localhost:8080');assert(issue.status===201,'issue');
 var report=await request('POST','/api/v1/reports',{planDate:date,studyHours:'99',tests:999,correct:999,focus:7,fatigue:4,motivation:8,problem:'smoke',tomorrow:'smoke'},student,'http://localhost:8080');assert(report.status===201,'report');var reports=await request('GET','/api/v1/reports?from='+date+'&to='+date,null,student,'http://localhost:8080');assert(reports.status===200&&Number(reports.json.data[0].tests)!==999,'objective metrics must ignore client values');
 var conv=await request('GET','/api/v1/chat/conversation',null,student,'http://localhost:8080');assert(conv.status===200&&conv.json.data.id,'student conversation');var cid=conv.json.data.id;
 var tooLong=await request('POST','/api/v1/chat/conversations/'+cid+'/messages',{text:'x'.repeat(3001)},student,'http://localhost:8080');assert(tooLong.status===400&&tooLong.json.error.code==='VALIDATION','chat length must reject instead of truncate');
 var sse=waitForSse(admin,'http://localhost:8081','chat.message.created',async function(){var sent=await request('POST','/api/v1/chat/conversations/'+cid+'/messages',{text:'سلام مشاور، پیام تست.'},student,'http://localhost:8080');assert(sent.status===201,'student chat send');});await sse;
 for(var chatIndex=1;chatIndex<=17;chatIndex++){var pagedSend=await request('POST','/api/v1/chat/conversations/'+cid+'/messages',{text:'پیام صفحه‌بندی '+chatIndex},student,'http://localhost:8080');assert(pagedSend.status===201,'pagination fixture '+chatIndex);}
 var cl=await request('GET','/api/v1/admin/chat/conversations',null,admin,'http://localhost:8081');assert(cl.status===200&&cl.json.data.length&&cl.json.data[0].unread>=1,'admin chat list unread');
 var clPage=await request('GET','/api/v1/admin/chat/conversations?limit=15&offset=0',null,admin,'http://localhost:8081');assert(clPage.status===200&&Array.isArray(clPage.json.data.items)&&clPage.json.data.total>=1&&clPage.json.data.totalUnread>=18,'paginated chat list contract');
 var clSearch=await request('GET','/api/v1/admin/chat/conversations?limit=15&search='+encodeURIComponent('نامی که وجود ندارد'),null,admin,'http://localhost:8081');assert(clSearch.status===200&&clSearch.json.data.total===0&&clSearch.json.data.items.length===0,'bounded chat search');
 var cm=await request('GET','/api/v1/chat/conversations/'+cid+'/messages?limit=20',null,admin,'http://localhost:8081');assert(cm.status===200&&cm.json.data.messages.some(function(x){return x.text==='سلام مشاور، پیام تست.';}),'chat history');
 var pageOne=await request('GET','/api/v1/chat/conversations/'+cid+'/messages?limit=15',null,admin,'http://localhost:8081');assert(pageOne.status===200&&pageOne.json.data.messages.length===15&&pageOne.json.data.hasMore&&pageOne.json.data.nextBeforeMessageId,'bounded chat first page');
 var safeLimit=await request('GET','/api/v1/chat/conversations/'+cid+'/messages?limit=not-a-number',null,admin,'http://localhost:8081');assert(safeLimit.status===200&&safeLimit.json.data.messages.length===15,'malformed chat limit uses safe default');
 var pageTwo=await request('GET','/api/v1/chat/conversations/'+cid+'/messages?limit=15&beforeMessageId='+encodeURIComponent(pageOne.json.data.nextBeforeMessageId),null,admin,'http://localhost:8081');assert(pageTwo.status===200&&pageTwo.json.data.messages.length>=3,'chat older page');assert(!pageTwo.json.data.messages.some(function(x){return pageOne.json.data.messages.some(function(y){return x.id===y.id;});}),'chat pages must not overlap');
 var badCursor=await request('GET','/api/v1/chat/conversations/'+cid+'/messages?limit=15&beforeMessageId=missing-message',null,admin,'http://localhost:8081');assert(badCursor.status===400&&badCursor.json.error.code==='INVALID_CURSOR','invalid chat cursor');
 var ar=await request('POST','/api/v1/chat/conversations/'+cid+'/read',{},admin,'http://localhost:8081');assert(ar.status===200,'admin read');
 var clRead=await request('GET','/api/v1/admin/chat/conversations?limit=15',null,admin,'http://localhost:8081');assert(clRead.status===200&&clRead.json.data.totalUnread===0,'global unread count after read');
 var reply=await request('POST','/api/v1/chat/conversations/'+cid+'/messages',{text:'پیامت رسید؛ برنامه را بررسی می‌کنم.'},admin,'http://localhost:8081');assert(reply.status===201,'admin chat reply');
 var finish=await request('POST','/api/v1/study-sessions/'+sessionId+'/finish',{deviceLabel:'Smoke Browser',testsCompleted:12,correct:99,wrong:99,focusRating:'invalid'},student,'http://localhost:8080');assert(finish.status===200&&finish.json.data.testsCompleted===12&&finish.json.data.correct===12&&finish.json.data.wrong===0&&finish.json.data.focusRating===1,'validated session finish '+finish.text);
 var protectedReplace=await request('POST','/api/v1/admin/import/commit',{studentId:sid,data:payload,replaceExistingPlans:true,replaceExistingExams:true,publishImported:false,sourceName:'must not erase progress'},admin,'http://localhost:8081');assert(protectedReplace.status===409&&protectedReplace.json.error.code==='PLAN_HAS_PROGRESS','plan replacement must preserve recorded progress '+protectedReplace.text);
 var sessions=await request('GET','/api/v1/auth/sessions',null,admin,'http://localhost:8081');assert(sessions.status===200&&sessions.json.data.length,'session management');
 var activityBad=await request('POST','/api/v1/activity',{eventType:'attacker.event',metadata:{}},student,'http://localhost:8080');assert(activityBad.status===400,'activity whitelist');
 var logout=await request('POST','/api/v1/auth/logout',{}, {cookie:student.cookie},'http://localhost:8080');assert(logout.status===200,'logout must succeed even when CSRF storage is stale/missing '+logout.text);
 var afterLogout=await request('GET','/api/v1/auth/me',null,{cookie:student.cookie},'http://localhost:8080');assert(afterLogout.status===401,'session must be invalid immediately after logout');
 var logoutAgain=await request('POST','/api/v1/auth/logout',{},null,'http://localhost:8080');assert(logoutAgain.status===200,'logout must be idempotent without a valid session');
 var firstAgain=await login('student','SmokeStudent123!','http://localhost:8080');
 var replace=await request('POST','/api/v1/auth/login',{username:'student',password:'SmokeStudent123!'},{cookie:firstAgain.cookie},'http://localhost:8080');assert(replace.status===200&&cookieFrom(replace),'replacement login');
 var oldAfterReplace=await request('GET','/api/v1/auth/me',null,{cookie:firstAgain.cookie},'http://localhost:8080');assert(oldAfterReplace.status===401,'successful login must revoke prior cookie session in same browser');
 var newAfterReplace=await request('GET','/api/v1/auth/me',null,{cookie:cookieFrom(replace)},'http://localhost:8080');assert(newAfterReplace.status===200,'replacement login cookie must be active');
 for(var i=0;i<6;i++)r=await request('POST','/api/v1/auth/login',{username:'nobody',password:'WrongPassword123!'},null,'http://localhost:8081');assert(r.status===429,'login rate limit');
 console.log('SMOKE TEST PASSED: JSON fixtures, strict validation, draft/publish, round-trip links, stable exam replacement, retired quizzes, progress protection, auth, study, chat and SSE');cleanup(0);
 }catch(e){console.error('SMOKE TEST FAILED:',e&&e.stack?e.stack:e);cleanup(1);}}
setTimeout(function(){if(!started){console.error('SMOKE TEST FAILED: server did not start in time');cleanup(1);}},15000);
