'use strict';
var http=require('http'),cp=require('child_process'),path=require('path'),fs=require('fs');
var root=path.resolve(__dirname,'..'),tmp=path.join(root,'data','smoke-'+process.pid+'.sqlite');try{fs.unlinkSync(tmp);}catch(e){}
var env=Object.assign({},process.env,{NODE_ENV:'test',PORT:'4199',DATABASE_PATH:tmp,CORS_ORIGINS:'http://localhost:8080,http://localhost:8081',ADMIN_USERNAME:'admin',ADMIN_PASSWORD:'SmokeAdmin123!',STUDENT_USERNAME:'student',STUDENT_PASSWORD:'SmokeStudent123!',ALLOW_BEARER_AUTH:'false',LOGIN_MAX_FAILURES:'5',LOGIN_BLOCK_MINUTES:'1'});
var child=cp.spawn(process.execPath,['--experimental-sqlite',path.join(root,'src/server.js')],{cwd:root,env:env,stdio:['ignore','pipe','pipe']});var done=false,started=false;
function cleanup(code){if(done)return;done=true;try{child.kill('SIGTERM');}catch(e){}setTimeout(function(){['','-wal','-shm'].forEach(function(x){try{fs.unlinkSync(tmp+x);}catch(e){}});process.exit(code);},300);}
child.stdout.on('data',function(b){var t=b.toString();process.stdout.write(t);if(t.indexOf('Moshaver | مشاور API started')>=0)runChecks();});child.stderr.on('data',function(b){process.stderr.write(b);});child.on('exit',function(c){if(!done)cleanup(c||1);});
function cookieFrom(res){var h=res.headers['set-cookie'];if(!h||!h.length)return '';return String(h[0]).split(';')[0];}
function request(method,pathname,body,auth,origin){return new Promise(function(resolve,reject){var payload=body!=null?JSON.stringify(body):null,headers={Accept:'application/json'};if(payload){headers['Content-Type']='application/json';headers['Content-Length']=Buffer.byteLength(payload);}if(auth&&auth.cookie)headers.Cookie=auth.cookie;if(auth&&auth.csrf)headers['X-CSRF-Token']=auth.csrf;if(origin)headers.Origin=origin;var req=http.request({host:'127.0.0.1',port:4199,path:pathname,method:method,headers:headers},function(res){var chunks=[];res.on('data',function(c){chunks.push(c);});res.on('end',function(){var text=Buffer.concat(chunks).toString('utf8'),json=null;try{json=JSON.parse(text);}catch(e){}resolve({status:res.statusCode,headers:res.headers,json:json,text:text});});});req.on('error',reject);if(payload)req.write(payload);req.end();});}
function assert(ok,msg){if(!ok)throw new Error(msg);}
async function login(username,password,origin){var r=await request('POST','/api/v1/auth/login',{username:username,password:password},null,origin);assert(r.status===200,'login '+username+' '+r.text);assert(r.json&&r.json.data&&r.json.data.csrfToken,'csrf on login');return{cookie:cookieFrom(r),csrf:r.json.data.csrfToken,user:r.json.data.user};}
function waitForSse(auth,origin,eventName,trigger){return new Promise(function(resolve,reject){var settled=false,req,timer=setTimeout(function(){if(!settled){settled=true;try{req.destroy();}catch(e){}reject(new Error('SSE timeout waiting for '+eventName));}},5000);var headers={Accept:'text/event-stream',Cookie:auth.cookie,Origin:origin};req=http.request({host:'127.0.0.1',port:4199,path:'/api/v1/events',method:'GET',headers:headers},function(res){if(res.statusCode!==200){settled=true;clearTimeout(timer);return reject(new Error('SSE status '+res.statusCode));}var buf='';res.on('data',function(c){buf+=c.toString('utf8');if(buf.indexOf('event: '+eventName)>=0&&!settled){settled=true;clearTimeout(timer);try{req.destroy();}catch(e){}resolve(buf);}});setTimeout(function(){Promise.resolve().then(trigger).catch(function(e){if(!settled){settled=true;clearTimeout(timer);req.destroy();reject(e);}});},120);});req.on('error',function(e){if(!settled){settled=true;clearTimeout(timer);reject(e);}});req.end();});}
async function runChecks(){if(started)return;started=true;try{
 var r=await request('GET','/');assert(r.status===200,'GET /');r=await request('GET','/health');assert(r.status===200&&r.json&&r.json.ok,'health');assert(!r.text.includes('node'),'health should not expose node version');
 r=await request('OPTIONS','/api/v1/auth/login',null,null,'http://localhost:8081');assert(r.status===204,'allowed CORS');assert(r.headers['access-control-allow-credentials']==='true','credentials CORS');r=await request('OPTIONS','/api/v1/auth/login',null,null,'http://evil.test');assert(r.status===403,'blocked CORS');
 var admin=await login('admin','SmokeAdmin123!','http://localhost:8081');var student=await login('student','SmokeStudent123!','http://localhost:8080');assert(admin.cookie.indexOf('moshaver_session=')===0,'admin cookie');assert(student.cookie.indexOf('moshaver_session=')===0,'student cookie');
 var loginCsrf=student.csrf;
 var noCsrf=await request('POST','/api/v1/activity',{eventType:'task.opened'}, {cookie:student.cookie},'http://localhost:8080');assert(noCsrf.status===403,'CSRF must block mutation');
 var me=await request('GET','/api/v1/auth/me',null,student,'http://localhost:8080');assert(me.status===200&&me.json.data.csrfToken,'me');var meCsrf1=me.json.data.csrfToken;
 var meAgain=await request('GET','/api/v1/auth/me',null,student,'http://localhost:8080');assert(meAgain.status===200&&meAgain.json.data.csrfToken,'second me');var meCsrf2=meAgain.json.data.csrfToken;
 assert(loginCsrf===meCsrf1&&meCsrf1===meCsrf2,'CSRF token must remain stable across auth/me calls');
 var originalTokenMutation=await request('POST','/api/v1/activity',{eventType:'task.opened',metadata:{source:'stable-csrf-smoke'}},{cookie:student.cookie,csrf:loginCsrf},'http://localhost:8080');assert(originalTokenMutation.status===201,'login CSRF must remain valid after auth/me calls '+originalTokenMutation.text);
 var badTokenMutation=await request('POST','/api/v1/activity',{eventType:'task.opened',metadata:{}},{cookie:student.cookie,csrf:'definitely-wrong-csrf-token'},'http://localhost:8080');assert(badTokenMutation.status===403,'wrong CSRF token must be rejected');
 student.csrf=meCsrf2;
 var students=await request('GET','/api/v1/admin/students',null,admin,'http://localhost:8081');assert(students.status===200&&students.json.data.length,'students');var sid=students.json.data[0].id;
 var date='2026-09-20',payload={schemaVersion:1,studentId:sid,plans:[{planDate:date,dayLabel:'شنبه',persianDate:'نمونه',title:'Smoke imported day',published:false,tasks:[{start:'07:00',end:'08:00',type:'study',subject:'روان‌شناسی',title:'مطالعه نمونه',pages:'1-5',testCount:0,note:'smoke'}]}],exams:[{title:'Smoke Exam',persianDate:'نمونه',isoDate:'2026-09-21',note:'smoke',status:'upcoming',syllabus:[{subject:'روان‌شناسی',description:'درس ۱',required:true,track:''}]}]};
 var preview=await request('POST','/api/v1/admin/import/preview',{studentId:sid,data:payload},admin,'http://localhost:8081');assert(preview.status===200&&preview.json.data.errors.length===0,'import preview '+preview.text);
 var commit=await request('POST','/api/v1/admin/import/commit',{studentId:sid,data:payload,replaceExistingPlans:true,replaceExistingExams:true,publishImported:true,sourceName:'smoke'},admin,'http://localhost:8081');assert(commit.status===201&&commit.json.data.plans===1,'import commit '+commit.text);
 var plan=await request('GET','/api/v1/plans?date='+date,null,student,'http://localhost:8080');assert(plan.status===200&&plan.json.data&&plan.json.data.tasks.length===1,'student published plan');var taskId=plan.json.data.tasks[0].id;
 var ss=await request('POST','/api/v1/study-sessions/start',{taskId:taskId,deviceLabel:'Smoke Browser'},student,'http://localhost:8080');assert(ss.status===201&&ss.json.data.id,'session start '+ss.text);var sessionId=ss.json.data.id;
 var issue=await request('POST','/api/v1/task-issues',{taskId:taskId,issueType:'فراموش کردم',note:'smoke issue'},student,'http://localhost:8080');assert(issue.status===201,'issue');
 var report=await request('POST','/api/v1/reports',{planDate:date,studyHours:'99',tests:999,correct:999,focus:7,fatigue:4,motivation:8,problem:'smoke',tomorrow:'smoke'},student,'http://localhost:8080');assert(report.status===201,'report');var reports=await request('GET','/api/v1/reports?from='+date+'&to='+date,null,student,'http://localhost:8080');assert(reports.status===200&&Number(reports.json.data[0].tests)!==999,'objective metrics must ignore client values');
 var conv=await request('GET','/api/v1/chat/conversation',null,student,'http://localhost:8080');assert(conv.status===200&&conv.json.data.id,'student conversation');var cid=conv.json.data.id;
 var sse=waitForSse(admin,'http://localhost:8081','chat.message.created',async function(){var sent=await request('POST','/api/v1/chat/conversations/'+cid+'/messages',{text:'سلام مشاور، پیام تست.'},student,'http://localhost:8080');assert(sent.status===201,'student chat send');});await sse;
 var cl=await request('GET','/api/v1/admin/chat/conversations',null,admin,'http://localhost:8081');assert(cl.status===200&&cl.json.data.length&&cl.json.data[0].unread>=1,'admin chat list unread');
 var cm=await request('GET','/api/v1/chat/conversations/'+cid+'/messages?limit=20',null,admin,'http://localhost:8081');assert(cm.status===200&&cm.json.data.messages.some(function(x){return x.text==='سلام مشاور، پیام تست.';}),'chat history');
 var ar=await request('POST','/api/v1/chat/conversations/'+cid+'/read',{},admin,'http://localhost:8081');assert(ar.status===200,'admin read');
 var reply=await request('POST','/api/v1/chat/conversations/'+cid+'/messages',{text:'پیامت رسید؛ برنامه را بررسی می‌کنم.'},admin,'http://localhost:8081');assert(reply.status===201,'admin chat reply');
 var finish=await request('POST','/api/v1/study-sessions/'+sessionId+'/finish',{deviceLabel:'Smoke Browser'},student,'http://localhost:8080');assert(finish.status===200,'session finish');
 var sessions=await request('GET','/api/v1/auth/sessions',null,admin,'http://localhost:8081');assert(sessions.status===200&&sessions.json.data.length,'session management');
 var activityBad=await request('POST','/api/v1/activity',{eventType:'attacker.event',metadata:{}},student,'http://localhost:8080');assert(activityBad.status===400,'activity whitelist');
 var logout=await request('POST','/api/v1/auth/logout',{}, {cookie:student.cookie},'http://localhost:8080');assert(logout.status===200,'logout must succeed even when CSRF storage is stale/missing '+logout.text);
 var afterLogout=await request('GET','/api/v1/auth/me',null,{cookie:student.cookie},'http://localhost:8080');assert(afterLogout.status===401,'session must be invalid immediately after logout');
 var logoutAgain=await request('POST','/api/v1/auth/logout',{},null,'http://localhost:8080');assert(logoutAgain.status===200,'logout must be idempotent without a valid session');
 var firstAgain=await login('student','SmokeStudent123!','http://localhost:8080');
 var replace=await request('POST','/api/v1/auth/login',{username:'student',password:'SmokeStudent123!'},{cookie:firstAgain.cookie},'http://localhost:8080');assert(replace.status===200&&cookieFrom(replace),'replacement login');
 var oldAfterReplace=await request('GET','/api/v1/auth/me',null,{cookie:firstAgain.cookie},'http://localhost:8080');assert(oldAfterReplace.status===401,'successful login must revoke prior cookie session in same browser');
 var newAfterReplace=await request('GET','/api/v1/auth/me',null,{cookie:cookieFrom(replace)},'http://localhost:8080');assert(newAfterReplace.status===200,'replacement login cookie must be active');
 for(var i=0;i<6;i++)r=await request('POST','/api/v1/auth/login',{username:'nobody',password:'WrongPassword123!'},null,'http://localhost:8081');assert(r.status===429,'login rate limit');
 console.log('SMOKE TEST PASSED: stable CSRF, reliable logout, secure cookies, CORS, rate-limit, JSON import, study/report integrity, chat + SSE, sessions, activity validation');cleanup(0);
 }catch(e){console.error('SMOKE TEST FAILED:',e&&e.stack?e.stack:e);cleanup(1);}}
setTimeout(function(){if(!started){console.error('SMOKE TEST FAILED: server did not start in time');cleanup(1);}},15000);
