import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { DataSource, In, IsNull, Repository } from "typeorm";
import { ApiException } from "../../common/exceptions/api.exception";
import { Exam, ExamAssignment, ExamAttempt, ExamRetryRequest, ExamSyllabus, Mistake, Organization, OrganizationMembership, Quiz, QuizAttempt, QuizQuestion, Student, SyllabusProgress, User } from "../../database/entities";
import { MembershipStatus } from "../../database/entities/organization-membership.entity";
import { RetryRequestStatus } from "../../database/entities/exam-retry-request.entity";
import { AuthorizationService, UserContext } from "../authorization";
import { CreateQuizDto, ModerateRetryDto, QuizQuestionDto, SubmitQuizDto, SyllabusDto, SyllabusProgressDto, UpdateQuizDto } from "./dto/assessment.dto";

@Injectable()
export class AssessmentsService {
  constructor(
    @InjectRepository(Exam) private exams: Repository<Exam>, @InjectRepository(ExamAssignment) private assignments: Repository<ExamAssignment>,
    @InjectRepository(ExamSyllabus) private syllabus: Repository<ExamSyllabus>, @InjectRepository(SyllabusProgress) private progress: Repository<SyllabusProgress>,
    @InjectRepository(ExamRetryRequest) private retries: Repository<ExamRetryRequest>, @InjectRepository(Quiz) private quizzes: Repository<Quiz>,
    @InjectRepository(QuizQuestion) private questions: Repository<QuizQuestion>, @InjectRepository(QuizAttempt) private attempts: Repository<QuizAttempt>,
    @InjectRepository(Student) private students: Repository<Student>, @InjectRepository(ExamAttempt) private examAttempts: Repository<ExamAttempt>, private authz: AuthorizationService, private db: DataSource,
  ) {}
  private student(userId:string) { return this.students.findOneOrFail({where:{user:{id:userId}},relations:{user:true}}); }
  async addSyllabus(context:UserContext,examId:string,dto:SyllabusDto){ const exam=await this.requireExam(context,examId,"syllabus.manage"); return this.syllabus.save(this.syllabus.create({...dto,description:dto.description||"",required:!!dto.required,track:dto.track||"",exam})); }
  async removeSyllabus(context:UserContext,id:string){ const row=await this.syllabus.findOne({where:{id},relations:{exam:{organization:true}}}); if(!row) throw new ApiException(404,"SYLLABUS_NOT_FOUND","بودجه آزمون پیدا نشد."); this.requireOrganization(context,row.exam.organization?.id,"syllabus.manage"); await this.syllabus.delete(id); return {id,deleted:true}; }
  async updateProgress(userId:string,id:string,dto:SyllabusProgressDto){ const student=await this.student(userId); const row=await this.syllabus.findOne({where:{id},relations:{exam:true}}); if(!row || !await this.assignments.findOne({where:{exam:{id:row.exam.id},student:{id:student.id}}})) throw new ApiException(404,"SYLLABUS_NOT_FOUND","بودجه آزمون پیدا نشد."); let value=await this.progress.findOne({where:{student:{id:student.id},syllabus:{id}}}); value ||= this.progress.create({student,syllabus:row}); Object.assign(value,{status:dto.status,accuracy:dto.accuracy??0,note:dto.note||""}); return this.progress.save(value); }
  async studentSyllabus(userId:string,examId:string){const student=await this.student(userId);if(!await this.assignments.findOne({where:{exam:{id:examId},student:{id:student.id}}}))throw new ApiException(404,"EXAM_NOT_ASSIGNED","آزمون در دسترس نیست.");const [rows,values]=await Promise.all([this.syllabus.find({where:{exam:{id:examId}},order:{subject:"ASC"}}),this.progress.find({where:{student:{id:student.id}},relations:{syllabus:true}})]);const bySyllabus=new Map(values.map(value=>[value.syllabus.id,value]));return rows.map(row=>{const value=bySyllabus.get(row.id);return{id:row.id,subject:row.subject,description:row.description,required:row.required,track:row.track,progress:value?{status:value.status,accuracy:value.accuracy,note:value.note,updatedAt:value.updatedAt}:null};});}
  async requestRetry(userId:string,examId:string,message=""){ const student=await this.student(userId); const exam=await this.exams.findOneByOrFail({id:examId}); if(!await this.assignments.findOne({where:{exam:{id:examId},student:{id:student.id}}})) throw new ApiException(404,"EXAM_NOT_ASSIGNED","آزمون در دسترس نیست."); const pending=await this.retries.findOne({where:{exam:{id:examId},student:{id:student.id},status:RetryRequestStatus.PENDING}}); if(pending) return pending; const [used,approved]=await Promise.all([this.examAttempts.count({where:{exam:{id:examId},student:{id:student.id}}}),this.retries.count({where:{exam:{id:examId},student:{id:student.id},status:RetryRequestStatus.APPROVED}})]); if(used<exam.attemptLimit+approved) throw new ApiException(409,"ATTEMPTS_AVAILABLE","هنوز امکان شروع آزمون را دارید و نیازی به درخواست تلاش مجدد نیست."); return this.retries.save(this.retries.create({exam,student,message})); }
  async studentRetries(userId:string){const student=await this.student(userId);return this.retries.find({where:{student:{id:student.id}},relations:{exam:true},order:{createdAt:"DESC"},take:50}).then(rows=>rows.map(row=>({id:row.id,examId:row.exam.id,examTitle:row.exam.title,message:row.message,status:row.status,moderatorNote:row.moderatorNote,resolvedAt:row.resolvedAt,createdAt:row.createdAt})));}
  async listRetries(context:UserContext){ const rows=await this.retries.find({relations:{exam:true,student:true},order:{createdAt:"DESC"}}); const out=[]; for(const row of rows) if(await this.authz.canAccessStudent(context,row.student.id,"retry_requests.read")) out.push(row); return out; }
  async moderateRetry(context:UserContext,userId:string,id:string,dto:ModerateRetryDto){ if(dto.status===RetryRequestStatus.PENDING) throw new ApiException(400,"INVALID_STATUS","وضعیت نهایی لازم است."); const row=await this.retries.findOne({where:{id},relations:{exam:true,student:true}}); if(!row) throw new ApiException(404,"RETRY_NOT_FOUND","درخواست پیدا نشد."); if(!await this.authz.canAccessStudent(context,row.student.id,"retry_requests.moderate")) throw new ApiException(403,"STUDENT_FORBIDDEN","به این دانش‌آموز دسترسی ندارید."); if(row.status!==RetryRequestStatus.PENDING) throw new ApiException(409,"RETRY_RESOLVED","درخواست قبلا بررسی شده است."); row.status=dto.status; row.moderatorNote=dto.note||""; row.resolvedAt=new Date(); row.resolvedBy=await this.db.manager.findOneByOrFail(User,{id:userId}); return this.db.transaction(async m=>m.save(ExamRetryRequest,row)); }
  async listQuizzes(context:UserContext){ return this.quizzes.find({where:context.roles.includes("PLATFORM_ADMIN")?{}:{organization:{id:In(context.organizationIds)}},relations:{questions:true,exam:true,organization:true},order:{createdAt:"DESC"}}); }
  async studentQuizzes(userId:string){
    const student=await this.student(userId);
    const rows=await this.quizzes.find({where:{active:true},relations:{questions:true,exam:true,organization:true},order:{createdAt:"DESC"}});
    const visible=[];
    for(const quiz of rows) if(await this.canStudentAccessQuiz(student,quiz)){
      const latest=await this.attempts.findOne({where:{quiz:{id:quiz.id},student:{id:student.id}},order:{startedAt:"DESC"}});
      visible.push({id:quiz.id,title:quiz.title,subject:quiz.subject,durationMinutes:quiz.durationMinutes,questionCount:quiz.questions.length,examId:quiz.exam?.id??null,attempt:latest?{id:latest.id,submittedAt:latest.submittedAt,percent:latest.percent}:null});
    }
    return visible;
  }
  async createQuiz(context:UserContext,dto:CreateQuizDto){ const organizationId=dto.organizationId??(context.organizationIds.length===1?context.organizationIds[0]:undefined); this.requireOrganization(context,organizationId,"quizzes.create"); const [exam,organization]=await Promise.all([dto.examId?this.requireExam(context,dto.examId,"quizzes.create"):null,organizationId?this.db.manager.findOneByOrFail(Organization,{id:organizationId}):null]); return this.quizzes.save(this.quizzes.create({...dto,subject:dto.subject||"",durationMinutes:dto.durationMinutes||20,active:dto.active??true,exam,organization})); }
  async updateQuiz(context:UserContext,id:string,dto:UpdateQuizDto){ const quiz=await this.requireQuiz(context,id,"quizzes.update"); Object.assign(quiz,dto); return this.quizzes.save(quiz); }
  async quizQuestions(context:UserContext,id:string,answers=true){ await this.requireQuiz(context,id,"quizzes.read"); const rows=await this.questions.find({where:{quiz:{id}},order:{sortOrder:"ASC"}}); return answers?rows:rows.map(({correctAnswer:_c,explanation:_e,...q})=>q); }
  async addQuizQuestion(context:UserContext,id:string,dto:QuizQuestionDto){ if(dto.options.length!==4 || !dto.options.includes(dto.correctAnswer)) throw new ApiException(400,"INVALID_QUESTION","چهار گزینه و پاسخ صحیح معتبر لازم است."); const quiz=await this.requireQuiz(context,id,"quiz_questions.manage"); return this.questions.save(this.questions.create({...dto,explanation:dto.explanation||"",sortOrder:dto.sortOrder||0,quiz})); }
  async updateQuizQuestion(context:UserContext,id:string,dto:QuizQuestionDto){ const row=await this.questions.findOne({where:{id},relations:{quiz:{organization:true,exam:{organization:true}}}}); if(!row) throw new ApiException(404,"QUIZ_QUESTION_NOT_FOUND","سؤال پیدا نشد."); this.requireOrganization(context,row.quiz.organization?.id??row.quiz.exam?.organization?.id,"quiz_questions.manage"); Object.assign(row,{...dto,explanation:dto.explanation||"",sortOrder:dto.sortOrder||0}); return this.questions.save(row); }
  async removeQuizQuestion(context:UserContext,id:string){ const row=await this.questions.findOne({where:{id},relations:{quiz:{organization:true,exam:{organization:true}}}}); if(!row) throw new ApiException(404,"QUIZ_QUESTION_NOT_FOUND","سؤال پیدا نشد."); this.requireOrganization(context,row.quiz.organization?.id??row.quiz.exam?.organization?.id,"quiz_questions.manage"); await this.questions.delete(id); return {id,deleted:true}; }
  async studentQuiz(userId:string,id:string){ const student=await this.student(userId); const quiz=await this.quizzes.findOne({where:{id,active:true},relations:{exam:true,organization:true}}); if(!quiz) throw new ApiException(404,"QUIZ_NOT_FOUND","آزمونک پیدا نشد."); await this.assertQuizAccess(quiz,student); const rows=await this.questions.find({where:{quiz:{id}},order:{sortOrder:"ASC"}}); return {...quiz,questions:rows.map(({correctAnswer:_c,explanation:_e,...q})=>q)}; }
  async startQuiz(userId:string,id:string){ const student=await this.student(userId); const quiz=await this.quizzes.findOne({where:{id,active:true},relations:{exam:true,organization:true,questions:true}}); if(!quiz) throw new ApiException(404,"QUIZ_NOT_FOUND","آزمونک پیدا نشد."); await this.assertQuizAccess(quiz,student); let run=await this.attempts.findOne({where:{quiz:{id},student:{id:student.id},submittedAt:IsNull()},relations:{quiz:{questions:true}}}); if(!run) run=await this.attempts.save(this.attempts.create({quiz,student,startedAt:new Date(),answers:[]})); return this.runPayload(run); }
  async submitQuiz(userId:string,id:string,dto:SubmitQuizDto){ const student=await this.student(userId); const run=await this.attempts.findOne({where:{id:dto.runId,quiz:{id},student:{id:student.id},submittedAt:IsNull()},relations:{quiz:{questions:true}}}); if(!run) throw new ApiException(409,"NO_ACTIVE_ATTEMPT","تلاش فعالی وجود ندارد."); const deadline=run.startedAt.getTime()+run.quiz.durationMinutes*60000; const submittedAt=new Date(); const answers=submittedAt.getTime()>deadline?run.answers:dto.answers; const map=new Map(answers.map(a=>[a.questionId,a.selectedOption||""])); const correct=run.quiz.questions.filter(q=>map.get(q.id)===q.correctAnswer).length; const blank=run.quiz.questions.filter(q=>!map.get(q.id)).length; const wrong=run.quiz.questions.length-correct-blank; return this.db.transaction(async m=>{ Object.assign(run,{answers,correct,wrong,blank,percent:run.quiz.questions.length?Math.round(correct/run.quiz.questions.length*100):0,submittedAt}); await m.save(QuizAttempt,run); for(const q of run.quiz.questions.filter(q=>map.get(q.id)&&map.get(q.id)!==q.correctAnswer)){ const exists=await m.findOne(Mistake,{where:{studentId:student.id,questionId:q.id}}); if(!exists) await m.save(Mistake,m.create(Mistake,{studentId:student.id,questionId:q.id,reason:"",resolved:false})); } return this.result(run); }); }
  async history(userId:string,id?:string){ const student=await this.student(userId); if(id){ const row=await this.attempts.findOne({where:{id,student:{id:student.id}},relations:{quiz:{questions:true}}}); if(!row) throw new ApiException(404,"ATTEMPT_NOT_FOUND","نتیجه پیدا نشد."); return this.result(row); } return this.attempts.find({where:{student:{id:student.id}},relations:{quiz:true},order:{startedAt:"DESC"}}); }
  private async canStudentAccessQuiz(student:Student,quiz:Quiz){
    if(quiz.exam) return Boolean(await this.assignments.findOne({where:{exam:{id:quiz.exam.id},student:{id:student.id}}}));
    if(!quiz.organization||!student.user) return false;
    return Boolean(await this.db.manager.findOne(OrganizationMembership,{where:{user:{id:student.user.id},organization:{id:quiz.organization.id},status:MembershipStatus.ACTIVE}}));
  }
  private async assertQuizAccess(quiz:Quiz,student:Student){ if(!await this.canStudentAccessQuiz(student,quiz)) throw new ApiException(404,"QUIZ_NOT_ASSIGNED","آزمونک در دسترس نیست."); }
  private requireOrganization(context:UserContext,organizationId:string|undefined,capability:string){ if(context.roles.includes("PLATFORM_ADMIN")) return; if(!organizationId||!this.authz.canAccessOrganization(context,organizationId,capability)) throw new ApiException(404,"NOT_FOUND","منبع پیدا نشد."); }
  private async requireExam(context:UserContext,id:string,capability:string){ const exam=await this.exams.findOne({where:{id},relations:{organization:true}}); if(!exam) throw new ApiException(404,"EXAM_NOT_FOUND","آزمون پیدا نشد."); this.requireOrganization(context,exam.organization?.id,capability); return exam; }
  private async requireQuiz(context:UserContext,id:string,capability:string){ const quiz=await this.quizzes.findOne({where:{id},relations:{organization:true,exam:{organization:true}}}); if(!quiz) throw new ApiException(404,"QUIZ_NOT_FOUND","آزمونک پیدا نشد."); this.requireOrganization(context,quiz.organization?.id??quiz.exam?.organization?.id,capability); return quiz; }
  private runPayload(run:QuizAttempt){ const deadline=new Date(run.startedAt.getTime()+run.quiz.durationMinutes*60000); return {runId:run.id,startedAt:run.startedAt,deadline,remainingSeconds:Math.max(0,Math.ceil((deadline.getTime()-Date.now())/1000)),savedAnswers:run.answers,quiz:{id:run.quiz.id,title:run.quiz.title,durationMinutes:run.quiz.durationMinutes,questions:run.quiz.questions.map(({correctAnswer:_c,explanation:_e,...q})=>q)}}; }
  private result(run:QuizAttempt){ const map=new Map(run.answers.map(a=>[a.questionId,a.selectedOption||""])); return {id:run.id,quizId:run.quiz.id,correct:run.correct,wrong:run.wrong,blank:run.blank,percent:run.percent,startedAt:run.startedAt,submittedAt:run.submittedAt,review:run.quiz.questions?.map(q=>({questionId:q.id,selectedOption:map.get(q.id)||null,correctOption:q.correctAnswer,explanation:q.explanation,isCorrect:map.get(q.id)===q.correctAnswer}))||[]}; }
}
