import { Injectable } from "@nestjs/common";import { DataSource } from "typeorm";import { ApiException } from "../../common/exceptions/api.exception";import { AuthenticatedUser } from "../auth/auth.service";
@Injectable()export class DashboardService{constructor(private db:DataSource){}
 async get(user:AuthenticatedUser,requested?:string){const roles=user.roles||(user.role==="ADMIN"?[]:[user.role]);const context=String(requested||roles.find(r=>r!=="STUDENT")||roles[0]||"").toUpperCase();if(!context||!roles.includes(context))throw new ApiException(403,"CONTEXT_FORBIDDEN","این زمینه برای حساب شما فعال نیست.");const ids=await this.studentIds(user.id,context);const values=ids.length?ids:["__none__"];const marks=values.map(()=>"?").join(",");const scalar=async(sql:string,args:unknown[]=[])=>(await this.db.query(sql,args))[0]?.n||0;const common={context,generatedAt:new Date().toISOString(),assignedStudents:ids.length,unreadConversations:await scalar(`SELECT COUNT(*) n FROM chat_messages m JOIN conversation_members cm ON cm.conversationId=m.conversationId WHERE cm.userId=? AND cm.leftAt IS NULL AND m.senderId<>? AND m.readAt IS NULL`,[user.id,user.id])};
  if(context==="ADVISOR")return{...common,attentionStudents:await scalar(`SELECT COUNT(DISTINCT p.studentId)n FROM plans p JOIN tasks t ON t.planId=p.id WHERE p.studentId IN (${marks}) AND p.date=date('now') AND t.completedAt IS NULL`,values),taskIssues:await scalar(`SELECT COUNT(*)n FROM task_issues WHERE studentId IN (${marks}) AND status='OPEN'`,values),recoveryRequests:await scalar(`SELECT COUNT(*)n FROM recovery_requests WHERE studentId IN (${marks}) AND status='PENDING'`,values),retryRequests:await scalar(`SELECT COUNT(*)n FROM exam_retry_requests WHERE studentId IN (${marks}) AND status='pending'`,values),todayPlanHealth:await this.planHealth(values),upcomingExams:await this.upcomingExams(values)};
  if(context==="TEACHER")return{...common,subjects:await this.db.query(`SELECT DISTINCT s.id,s.name FROM subjects s JOIN student_subjects ss ON ss.subjectId=s.id WHERE ss.studentId IN (${marks}) AND ss.enabled=1`,values),upcomingExams:await this.upcomingExams(values),recentExamResults:await this.db.query(`SELECT ea.id,ea.score,ea.finishedAt,ea.studentId,e.title FROM exam_attempts ea JOIN exams e ON e.id=ea.examId WHERE ea.studentId IN (${marks}) AND ea.finishedAt IS NOT NULL ORDER BY ea.finishedAt DESC LIMIT 10`,values),studentsNeedingAttention:await scalar(`SELECT COUNT(*)n FROM mistakes WHERE studentId IN (${marks}) AND resolved=0`,values),contentTasks:{questions:await scalar(`SELECT COUNT(*)n FROM questions`),quizzes:await scalar(`SELECT COUNT(*)n FROM quizzes WHERE active=1`)}};
  if(context==="MENTOR")return{...common,recentProgress:await this.planHealth(values),upcomingGoals:await this.upcomingExams(values),messages:common.unreadConversations};
  if(context==="CONTENT_MANAGER")return{...common,subjects:await scalar(`SELECT COUNT(*)n FROM subjects WHERE active=1`),questions:await scalar(`SELECT COUNT(*)n FROM questions`),quizzes:await scalar(`SELECT COUNT(*)n FROM quizzes`),exams:await scalar(`SELECT COUNT(*)n FROM exams`),draftCount:await scalar(`SELECT COUNT(*)n FROM quizzes WHERE active=0`),publishedCount:await scalar(`SELECT COUNT(*)n FROM quizzes WHERE active=1`),contentIssues:[]};
  if(context==="ORGANIZATION_ADMIN"){const orgs=user.organizationIds||[];const ov=orgs.length?orgs:["__none__"],om=ov.map(()=>"?").join(",");return{...common,organizations:orgs,members:await scalar(`SELECT COUNT(*)n FROM organization_memberships WHERE organizationId IN (${om}) AND status='ACTIVE'`,ov),students:await scalar(`SELECT COUNT(*)n FROM organization_memberships m JOIN students s ON s.userId=m.userId WHERE m.organizationId IN (${om}) AND m.status='ACTIVE'`,ov),staff:await scalar(`SELECT COUNT(DISTINCT m.userId)n FROM organization_memberships m LEFT JOIN students s ON s.userId=m.userId WHERE m.organizationId IN (${om}) AND m.status='ACTIVE' AND s.id IS NULL`,ov),activeUsers:await scalar(`SELECT COUNT(*)n FROM organization_memberships m JOIN users u ON u.id=m.userId WHERE m.organizationId IN (${om}) AND u.status='ACTIVE'`,ov),inactiveUsers:await scalar(`SELECT COUNT(*)n FROM organization_memberships m JOIN users u ON u.id=m.userId WHERE m.organizationId IN (${om}) AND u.status<>'ACTIVE'`,ov),analytics:{plans:await scalar(`SELECT COUNT(*)n FROM plans p JOIN students s ON s.id=p.studentId JOIN organization_memberships m ON m.userId=s.userId WHERE m.organizationId IN (${om})`,ov)},notices:[]};}
  if(context==="PLATFORM_ADMIN")return{...common,organizations:await scalar(`SELECT COUNT(*)n FROM organizations`),users:await scalar(`SELECT COUNT(*)n FROM users`),systemHealth:{database:"ok",sqlite:true},releaseStatus:{version:process.env.APP_VERSION||"2.0.0",environment:process.env.NODE_ENV||"development"},auditSummary:{events24h:await scalar(`SELECT COUNT(*)n FROM audit_logs WHERE createdAt>=datetime('now','-1 day')`),lockedLogins:await scalar(`SELECT COUNT(*)n FROM login_throttles WHERE lockedUntil>datetime('now')`)}};
  if(context==="GUARDIAN")return{...common,children:ids.length};throw new ApiException(400,"UNSUPPORTED_CONTEXT","داشبورد این نقش هنوز تعریف نشده است.");}
 private async studentIds(userId:string,context:string){if(context==="GUARDIAN"||["ADVISOR","TEACHER","MENTOR"].includes(context)){const rows=await this.db.query(`SELECT DISTINCT toStudentId id FROM user_relationships WHERE fromUserId=? AND status='ACTIVE' AND type=?`,[userId,context==="GUARDIAN"?"GUARDIAN_OF":`${context}_OF`]);return rows.map((r:{id:string})=>r.id);}return[];}
 private planHealth(ids:string[]){const marks=ids.map(()=>"?").join(",");return this.db.query(`SELECT COUNT(DISTINCT p.id)plans,COUNT(t.id)tasks,SUM(CASE WHEN t.completedAt IS NOT NULL OR t.status='DONE' THEN 1 ELSE 0 END)completed FROM plans p LEFT JOIN tasks t ON t.planId=p.id WHERE p.studentId IN (${marks}) AND p.date=date('now')`,ids).then(r=>r[0]);}
 private upcomingExams(ids:string[]){const marks=ids.map(()=>"?").join(",");return this.db.query(`SELECT DISTINCT e.id,e.title,e.subject,e.startTime FROM exams e JOIN exam_assignments a ON a.examId=e.id WHERE a.studentId IN (${marks}) AND (e.startTime IS NULL OR e.startTime>=datetime('now')) ORDER BY e.startTime LIMIT 10`,ids);}
}
