import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Clock3, Filter, Info, Pause, Play, Square, X } from 'lucide-react';
import { planMetrics, taskStatus, type StudentTask } from '@moshaver/student-core';
import { useStudentStore } from '../../services/student-store';
import { useSearchParams } from 'react-router-dom';

type Result = 'done' | 'partial' | 'skipped';
type FilterValue = 'all' | 'open' | 'active' | 'done' | 'missed' | StudentTask['type'];

export function PlanPage() {
  const [searchParams] = useSearchParams();
  const plan = useStudentStore((state) => state.plan); const loadPlan = useStudentStore((state) => state.loadPlan); const loadStatus = useStudentStore((state) => state.loadStatus); const storeError = useStudentStore((state) => state.error);
  const session = useStudentStore((state) => state.activeSession); const startTask = useStudentStore((state) => state.startTask); const pause = useStudentStore((state) => state.pauseFocus); const resume = useStudentStore((state) => state.resumeFocus); const finishTask = useStudentStore((state) => state.finishTask); const canMutate = useStudentStore((state) => Boolean(state.access?.canMutateStudentWork));
  const [date, setDate] = useState(plan.isoDate); const [now, setNow] = useState(Date.now()); const [filter, setFilter] = useState<FilterValue>('all'); const [filterOpen, setFilterOpen] = useState(false); const [detailIndex, setDetailIndex] = useState<number | null>(null); const [finishId, setFinishId] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [finishError, setFinishError] = useState<string | null>(null); const [feedback, setFeedback] = useState({ status: 'done' as Result, actualTests: '', difficulty: 'متوسط', note: '' });
  const metrics = planMetrics(plan.tasks); const time = new Date(now).toTimeString().slice(0, 5); const elapsed = session ? session.elapsedSeconds + (session.status === 'running' ? Math.max(0, Math.floor((now - new Date(session.startedAt).getTime()) / 1000)) : 0) : 0;
  const visible = useMemo(() => plan.tasks.filter((task) => matches(task, filter, time, session?.taskId)), [filter, plan.tasks, session?.taskId, time]); const detail = detailIndex === null ? null : plan.tasks[detailIndex];
  useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(id); }, []);
  useEffect(() => {
    const taskId = searchParams.get('task');
    if (!taskId) return;
    const index = plan.tasks.findIndex((task) => task.id === taskId);
    if (index >= 0) setDetailIndex(index);
  }, [plan.tasks, searchParams]);
  function pick(value: string) { setDate(value); void loadPlan(value); } function openTask(task: StudentTask) { setDetailIndex(plan.tasks.findIndex((item) => item.id === task.id)); } function openFinish(task: StudentTask) { setFinishId(task.id); setFeedback({ status: 'done', actualTests: String(task.testCount || ''), difficulty: 'متوسط', note: '' }); setFinishError(null); }

  return <section className="plan-page">
    <div className="plan-toolbar"><PersianDatePicker value={date} onChange={pick} /><div className="task-filter"><button type="button" aria-expanded={filterOpen} onClick={() => setFilterOpen((value) => !value)}><Filter /><span>{filterLabel(filter)}</span><ChevronDown /></button>{filterOpen ? <div role="menu">{filterOptions.map((item) => <button type="button" key={item.value} className={filter === item.value ? 'is-active' : ''} onClick={() => { setFilter(item.value); setFilterOpen(false); }}>{item.label}</button>)}</div> : null}</div></div>
    <div className="plan-metrics"><Metric label="فعالیت" value={`${metrics.doneTasks}/${metrics.totalTasks}`} /><Metric label="دقیقه" value={metrics.plannedMinutes} /><Metric label="تست" value={metrics.plannedTests} /></div>
    {loadStatus === 'loading' ? <p className="plan-state">در حال دریافت برنامه…</p> : null}{loadStatus === 'error' ? <div className="plan-state is-error"><p>{storeError}</p><button onClick={() => void loadPlan(date)}>تلاش دوباره</button></div> : null}
    <div className="task-rows">{visible.map((task) => <TaskRow key={task.id} task={task} now={time} active={session?.taskId === task.id} readOnly={!canMutate} onOpen={() => openTask(task)} onStart={() => void startTask(task.id)} onFinish={() => openFinish(task)} />)}{loadStatus !== 'loading' && !visible.length ? <p className="plan-state">فعالیتی با این فیلتر پیدا نشد.</p> : null}</div>
    {detail ? <div className="task-focus-backdrop"><article className="task-focus" role="dialog" aria-modal="true" aria-labelledby="task-focus-title"><header><button onClick={() => setDetailIndex(null)} aria-label="بستن"><X /></button><span>{(detailIndex! + 1).toLocaleString('fa-IR')} از {plan.tasks.length.toLocaleString('fa-IR')}</span><div><button disabled={detailIndex === 0} onClick={() => setDetailIndex((value) => Math.max(0, (value || 0) - 1))} aria-label="فعالیت قبلی"><ChevronRight /></button><button disabled={detailIndex === plan.tasks.length - 1} onClick={() => setDetailIndex((value) => Math.min(plan.tasks.length - 1, (value || 0) + 1))} aria-label="فعالیت بعدی"><ChevronLeft /></button></div></header><div className="task-focus__content"><span className="task-focus__type">{taskTypeLabel(detail.type)}</span><h2 id="task-focus-title">{taskTitle(detail)}</h2><div className="task-focus__time"><Clock3 /><strong dir="ltr">{detail.start} — {detail.end}</strong><span>{plannedMinutes(detail).toLocaleString('fa-IR')} دقیقه</span></div>{session?.taskId === detail.id ? <div className="task-focus__timer"><small>{session.status === 'running' ? 'در حال مطالعه' : 'مکث شده'}</small><strong dir="ltr">{formatElapsed(elapsed)}</strong></div> : null}<dl><Meta label="تعداد تست" value={(detail.testCount || 0).toLocaleString('fa-IR')} /><Meta label="وضعیت" value={statusLabel(detail, time, session?.taskId)} /></dl><p>{detail.note || 'برای این فعالیت توضیح بیشتری ثبت نشده است.'}</p></div>{canMutate ? <footer>{session?.taskId === detail.id ? <button className="secondary" onClick={() => void (session.status === 'running' ? pause() : resume())}>{session.status === 'running' ? <Pause /> : <Play />}{session.status === 'running' ? 'مکث' : 'ادامه'}</button> : <button className="secondary" onClick={() => void startTask(detail.id)}><Play />شروع</button>}<button className="primary" onClick={() => openFinish(detail)}><CheckCircle2 />ثبت نتیجه</button></footer> : null}</article></div> : null}
    {finishId ? <div className="finish-backdrop"><form className="finish-sheet" onSubmit={(event) => { event.preventDefault(); setSaving(true); setFinishError(null); void finishTask(finishId, { ...feedback, actualTests: Number(feedback.actualTests || 0) }).then(() => { setFinishId(null); setDetailIndex(null); }).catch((error) => setFinishError(error instanceof Error ? error.message : 'ثبت نتیجه ناموفق بود.')).finally(() => setSaving(false)); }}><header><h2>نتیجه فعالیت</h2><button type="button" onClick={() => setFinishId(null)} aria-label="بستن"><X /></button></header><div className="completion-options">{(['done', 'partial', 'skipped'] as Result[]).map((value) => <button type="button" key={value} className={`${value} ${feedback.status === value ? 'is-active' : ''}`} onClick={() => setFeedback((state) => ({ ...state, status: value }))}>{value === 'done' ? 'کامل' : value === 'partial' ? 'نیمه‌کامل' : 'انجام نشد'}</button>)}</div><label>تعداد تست<input inputMode="numeric" value={feedback.actualTests} onChange={(event) => setFeedback({ ...feedback, actualTests: event.target.value })} /></label><label>سختی<select value={feedback.difficulty} onChange={(event) => setFeedback({ ...feedback, difficulty: event.target.value })}><option>آسان</option><option>متوسط</option><option>سخت</option></select></label><label>یادداشت<textarea value={feedback.note} onChange={(event) => setFeedback({ ...feedback, note: event.target.value })} /></label>{finishError ? <p role="alert">{finishError}</p> : null}<button className="submit" disabled={saving}>{saving ? 'در حال ثبت…' : 'ثبت نتیجه'}</button></form></div> : null}
  </section>;
}

function TaskRow({ task, now, active, readOnly, onOpen, onStart, onFinish }: { task: StudentTask; now: string; active: boolean; readOnly: boolean; onOpen(): void; onStart(): void; onFinish(): void }) { return <article className={`task-row ${active ? 'is-active' : ''}`} onClick={onOpen}><div className="task-row__time"><strong dir="ltr">{task.start}</strong><span dir="ltr">{task.end}</span></div><div className="task-row__body"><span>{taskTypeLabel(task.type)} · {statusLabel(task, now, active ? task.id : undefined)}</span><h2>{taskTitle(task)}</h2><p>{plannedMinutes(task).toLocaleString('fa-IR')} دقیقه · {(task.testCount || 0).toLocaleString('fa-IR')} تست</p></div><div className="task-row__actions" onClick={(event) => event.stopPropagation()}><button onClick={onOpen} aria-label="جزئیات"><Info /></button>{!readOnly && !task.completion ? <button onClick={onStart} aria-label={active ? 'ادامه' : 'شروع'}><Play /></button> : null}{!readOnly && !task.completion ? <button onClick={onFinish} aria-label="ثبت نتیجه"><Square /></button> : null}</div></article>; }

function PersianDatePicker({ value, onChange }: { value: string; onChange(value: string): void }) { const [open, setOpen] = useState(false); const [cursor, setCursor] = useState(value); const grid = useMemo(() => calendarGrid(cursor), [cursor]); const title = new Intl.DateTimeFormat('fa-IR-u-ca-persian', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(`${value}T12:00:00`)); return <div className="persian-picker"><button type="button" onClick={() => setOpen((state) => !state)} aria-expanded={open}><CalendarDays /><span>{title}</span><ChevronDown /></button>{open ? <div className="persian-calendar"><header><button onClick={() => setCursor(shiftMonth(cursor, -1))}><ChevronRight /></button><strong>{new Intl.DateTimeFormat('fa-IR-u-ca-persian', { month: 'long', year: 'numeric' }).format(new Date(`${cursor}T12:00:00`))}</strong><button onClick={() => setCursor(shiftMonth(cursor, 1))}><ChevronLeft /></button></header><div className="persian-weekdays">{['ش','ی','د','س','چ','پ','ج'].map((day) => <span key={day}>{day}</span>)}</div><div className="persian-days">{grid.map((day, index) => day ? <button type="button" key={day.iso} className={`${day.iso === value ? 'is-selected' : ''} ${day.iso === todayIso() ? 'is-today' : ''}`} onClick={() => { onChange(day.iso); setCursor(day.iso); setOpen(false); }}>{day.day.toLocaleString('fa-IR')}</button> : <span key={index} />)}</div><button type="button" className="today" onClick={() => { onChange(todayIso()); setCursor(todayIso()); setOpen(false); }}>امروز</button></div> : null}</div>; }

const filterOptions: Array<{ value: FilterValue; label: string }> = [{ value: 'all', label: 'همه فعالیت‌ها' }, { value: 'open', label: 'انجام‌نشده' }, { value: 'active', label: 'در حال انجام' }, { value: 'done', label: 'تکمیل‌شده' }, { value: 'missed', label: 'ازدست‌رفته' }, { value: 'study', label: 'مطالعه' }, { value: 'review', label: 'مرور' }, { value: 'test', label: 'تست' }, { value: 'exam', label: 'آزمون' }, { value: 'break', label: 'استراحت' }];
function matches(task: StudentTask, filter: FilterValue, now: string, activeId?: string) { if (filter === 'all') return true; if (filter === 'active') return task.id === activeId; if (filter === 'done') return Boolean(task.completion); if (filter === 'open') return !task.completion; if (filter === 'missed') return !task.completion && task.end < now; return task.type === filter; } function filterLabel(value: FilterValue) { return filterOptions.find((item) => item.value === value)?.label || 'فیلتر'; }
function statusLabel(task: StudentTask, now: string, activeId?: string) { if (task.id === activeId) return 'در حال انجام'; const status = taskStatus(task, now); return status === 'done' ? 'انجام شد' : status === 'partial' ? 'نیمه‌کامل' : status === 'skipped' || status === 'overdue' ? 'از دست رفته' : status === 'current' ? 'آماده' : 'برنامه‌ریزی‌شده'; }
function Metric({ label, value }: { label: string; value: number | string }) { return <div><span>{label}</span><strong>{value}</strong></div>; } function Meta({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; } function taskTypeLabel(type: string) { return type === 'test' ? 'تست' : type === 'review' ? 'مرور' : type === 'exam' ? 'آزمون' : type === 'break' ? 'استراحت' : 'مطالعه'; } function taskTitle(task: Pick<StudentTask, 'subject' | 'title'>) { return [task.subject, task.title].filter(Boolean).join(' · ') || 'فعالیت'; }
function plannedMinutes(task: Pick<StudentTask, 'start' | 'end'>) { const [sh, sm] = task.start.split(':').map(Number); const [eh, em] = task.end.split(':').map(Number); return Math.max(0, eh * 60 + em - sh * 60 - sm); } function formatElapsed(value: number) { return `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`; } function todayIso() { return new Date().toISOString().slice(0, 10); } function addDays(iso: string, days: number) { const date = new Date(`${iso}T12:00:00`); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10); }
function parts(iso: string) { const values = new Intl.DateTimeFormat('fa-IR-u-ca-persian-nu-latn', { year: 'numeric', month: 'numeric', day: 'numeric' }).formatToParts(new Date(`${iso}T12:00:00`)); const get = (type: string) => Number(values.find((item) => item.type === type)?.value); return { month: get('month'), day: get('day') }; } function calendarGrid(cursor: string) { let first = cursor; for (let i = 0; i < 35 && parts(first).day !== 1; i++) first = addDays(first, -1); const result: Array<{ iso: string; day: number } | null> = Array((new Date(`${first}T12:00:00`).getDay() + 1) % 7).fill(null); const month = parts(first).month; for (let iso = first; parts(iso).month === month; iso = addDays(iso, 1)) result.push({ iso, day: parts(iso).day }); return result; } function shiftMonth(cursor: string, delta: number) { const month = parts(cursor).month; let next = cursor; for (let i = 0; i < 40; i++) { next = addDays(next, delta > 0 ? 1 : -1); if (parts(next).month !== month) break; } return next; }
