"use strict";

var DEFAULTS = {
  members_can_send_messages: 1, members_can_add_members: 0, members_can_invite: 0,
  members_can_react: 1, members_can_use_mentions: 1, members_can_share_study_state: 1,
  members_can_share_exam_results: 1, members_can_share_learning_progress: 1,
  members_can_edit_own_messages: 1, members_can_delete_own_messages: 1,
  admins_can_delete_messages: 1
};

function createGroupChatService(deps) {
  var db=deps.db, security=deps.security, now=deps.now, env=deps.env, realtime=deps.realtime;
  function member(conversationId,userId){return db.prepare("SELECT * FROM conversation_members WHERE conversation_id=? AND user_id=?").get(conversationId,userId)||null;}
  function conversation(id){return db.prepare("SELECT * FROM chat_conversations WHERE id=?").get(id)||null;}
  function permissions(id){return db.prepare("SELECT * FROM conversation_permissions WHERE conversation_id=?").get(id)||Object.assign({conversation_id:id},DEFAULTS);}
  function canManage(m){return !!m&&(m.role==='owner'||m.role==='admin');}
  function requireMember(id,user){var c=conversation(id);if(!c||c.type!=='group'||c.archived_at)return null;var m=member(id,user.id);return m?{conversation:c,member:m,permissions:permissions(id)}:null;}
  function userSummary(id){var u=db.prepare("SELECT id,username,display_name,role,student_id FROM users WHERE id=? AND is_active=1").get(id);return u?{id:u.id,username:u.username,name:u.display_name,accountRole:u.role,studentId:u.student_id}:null;}
  function emitToMembers(id,type,payload,exclude){db.prepare("SELECT user_id FROM conversation_members WHERE conversation_id=?").all(id).forEach(function(r){if(r.user_id!==exclude)realtime.emitUser(db,r.user_id,type,payload,now);});}
  function systemMessage(id,user,text,payload){var mid=security.id('msg'),t=now();db.prepare("INSERT INTO chat_messages (id,conversation_id,sender_user_id,sender_role,message_text,created_at,message_type,payload_json) VALUES (?,?,?,?,?,?,?,?)").run(mid,id,user.id,user.role,text,t,'system',JSON.stringify(payload||{}));db.prepare("UPDATE chat_conversations SET updated_at=?,last_message_at=? WHERE id=?").run(t,t,id);emitToMembers(id,'chat.message.created',{id:mid,conversationId:id,senderUserId:user.id,senderRole:user.role,senderName:user.display_name,text:text,type:'system',payload:payload||{},createdAt:t},null);return mid;}
  function list(user,limit,offset,search){var n=Math.min(50,Math.max(1,Number(limit)||15)),skip=Math.max(0,Number(offset)||0),term=String(search||'').trim(),args=[user.id];var where="cm.user_id=? AND c.type='group' AND c.archived_at IS NULL";if(term){where+=" AND (c.title LIKE ? OR c.description LIKE ?)";args.push('%'+term+'%','%'+term+'%');}var totalStmt=db.prepare("SELECT COUNT(*) n FROM chat_conversations c JOIN conversation_members cm ON cm.conversation_id=c.id WHERE "+where),total=totalStmt.get.apply(totalStmt,args).n,listStmt=db.prepare("SELECT c.*,cm.role,cm.muted FROM chat_conversations c JOIN conversation_members cm ON cm.conversation_id=c.id WHERE "+where+" ORDER BY COALESCE(c.last_message_at,c.created_at) DESC,c.id DESC LIMIT ? OFFSET ?"),rows=listStmt.all.apply(listStmt,args.concat([n+1,skip])),more=rows.length>n;if(more)rows.length=n;return {items:rows.map(function(c){var last=db.prepare("SELECT cm.*,u.display_name sender_name FROM chat_messages cm JOIN users u ON u.id=cm.sender_user_id WHERE cm.conversation_id=? AND cm.deleted_at IS NULL ORDER BY cm.created_at DESC,cm.id DESC LIMIT 1").get(c.id),unread=db.prepare("SELECT COUNT(*) n FROM chat_messages m LEFT JOIN conversation_members own ON own.conversation_id=m.conversation_id AND own.user_id=? LEFT JOIN chat_messages lr ON lr.id=own.last_read_message_id WHERE m.conversation_id=? AND m.sender_user_id<>? AND m.deleted_at IS NULL AND (lr.id IS NULL OR m.created_at>lr.created_at OR (m.created_at=lr.created_at AND m.id>lr.id))").get(user.id,c.id,user.id).n;return {id:c.id,type:'group',title:c.title,description:c.description||'',role:c.role,muted:!!c.muted,memberCount:db.prepare("SELECT COUNT(*) n FROM conversation_members WHERE conversation_id=?").get(c.id).n,unread:unread,lastMessage:last?{id:last.id,text:last.message_text,type:last.message_type||'text',createdAt:last.created_at,senderName:last.sender_name}:null,updatedAt:c.updated_at};}),total:Number(total),hasMore:more,nextOffset:more?skip+rows.length:null};}
  function detail(id,user){var access=requireMember(id,user);if(!access)return null;var c=access.conversation,owner=userSummary(c.owner_user_id);return {id:c.id,type:'group',title:c.title,description:c.description||'',createdAt:c.created_at,updatedAt:c.updated_at,memberCount:db.prepare("SELECT COUNT(*) n FROM conversation_members WHERE conversation_id=?").get(id).n,owner:owner,myRole:access.member.role,muted:!!access.member.muted,permissions:access.permissions};}
  function create(user,input){var title=String(input.title||'').trim(),description=String(input.description||'').trim();if(title.length<2||title.length>env.chatMaxGroupName)throw ['VALIDATION','نام گروه باید بین ۲ تا '+env.chatMaxGroupName+' نویسه باشد.'];if(description.length>env.chatMaxGroupDescription)throw ['VALIDATION','توضیحات گروه بیش از حد طولانی است.'];var ids=Array.isArray(input.memberIds)?input.memberIds.map(String):[];ids=ids.filter(function(x,i,a){return x&&x!==user.id&&a.indexOf(x)===i;});if(ids.length+1>env.chatMaxGroupMembers)throw ['VALIDATION','تعداد اعضای گروه بیش از حد مجاز است.'];var valid=[];if(ids.length){var validStmt=db.prepare("SELECT id FROM users WHERE id IN ("+ids.map(function(){return'?';}).join(',')+") AND is_active=1");valid=validStmt.all.apply(validStmt,ids).map(function(x){return x.id;});}if(valid.length!==ids.length)throw ['VALIDATION','یک یا چند عضو معتبر نیستند.'];var id=security.id('group'),t=now();db.exec('BEGIN');try{db.prepare("INSERT INTO chat_conversations (id,student_id,created_at,updated_at,type,title,description,owner_user_id,created_by) VALUES (?,?,?,?,?,?,?,?,?)").run(id,null,t,t,'group',title,description||null,user.id,user.id);db.prepare("INSERT INTO conversation_permissions (conversation_id) VALUES (?)").run(id);db.prepare("INSERT INTO conversation_members (conversation_id,user_id,role,joined_at,invited_by) VALUES (?,?,?,?,?)").run(id,user.id,'owner',t,user.id);valid.forEach(function(uid){db.prepare("INSERT INTO conversation_members (conversation_id,user_id,role,joined_at,invited_by) VALUES (?,?,?,?,?)").run(id,uid,'member',t,user.id);});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}var item=detail(id,user);emitToMembers(id,'chat.conversation.created',item,user.id);systemMessage(id,user,'گروه «'+title+'» ساخته شد.',{action:'group_created'});return item;}
  function members(id,user,search,limit){var access=requireMember(id,user);if(!access)return null;var term=String(search||'').trim(),n=Math.min(50,Math.max(1,Number(limit)||30)),args=[id];var extra='';if(term){extra=' AND (u.display_name LIKE ? OR u.username LIKE ?)';args.push('%'+term+'%','%'+term+'%');}var stmt=db.prepare("SELECT u.id,u.username,u.display_name AS name,u.role AS account_role,u.student_id,cm.role,cm.joined_at,cm.muted FROM conversation_members cm JOIN users u ON u.id=cm.user_id WHERE cm.conversation_id=?"+extra+" ORDER BY CASE cm.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,u.display_name LIMIT ?");return stmt.all.apply(stmt,args.concat([n]));}
  function candidates(id,user,search,limit){var access=requireMember(id,user);if(!access||(!canManage(access.member)&&!access.permissions.members_can_add_members))return null;return db.prepare("SELECT u.id,u.username,u.display_name AS name,u.role AS account_role FROM users u WHERE u.is_active=1 AND u.id<>? AND NOT EXISTS(SELECT 1 FROM conversation_members cm WHERE cm.conversation_id=? AND cm.user_id=u.id) AND (u.display_name LIKE ? OR u.username LIKE ?) ORDER BY u.display_name LIMIT ?").all(user.id,id,'%'+String(search||'').trim()+'%','%'+String(search||'').trim()+'%',Math.min(30,Math.max(1,Number(limit)||15)));
  }
  return {DEFAULTS:DEFAULTS,member:member,conversation:conversation,permissions:permissions,canManage:canManage,requireMember:requireMember,userSummary:userSummary,emitToMembers:emitToMembers,systemMessage:systemMessage,list:list,detail:detail,create:create,members:members,candidates:candidates};
}
module.exports=createGroupChatService;
