import { Injectable } from "@nestjs/common";import { InjectRepository } from "@nestjs/typeorm";import { Between,Repository } from "typeorm";import { ApiException } from "../../common/exceptions/api.exception";import { AuditLog,DailyReport,Encouragement,ExamAssignment,Plan,Student,StudySession,User,UserRelationship } from "../../database/entities";import { PlanStatus } from "../../database/entities/plan.entity";import { RelationshipStatus,RelationshipType } from "../../database/entities/user-relationship.entity";import { NotificationsService } from "../notifications/notifications.service";
@Injectable() export class GuardianService{
 constructor(@InjectRepository(UserRelationship)private relationships:Repository<UserRelationship>,@InjectRepository(Student)private studentsRepo:Repository<Student>,@InjectRepository(Plan)private plans:Repository<Plan>,@InjectRepository(StudySession)private sessions:Repository<StudySession>,@InjectRepository(ExamAssignment)private assignments:Repository<ExamAssignment>,@InjectRepository(DailyReport)private reportsRepo:Repository<DailyReport>,@InjectRepository(Encouragement)private encouragements:Repository<Encouragement>,@InjectRepository(User)private users:Repository<User>,@InjectRepository(AuditLog)private audit:Repository<AuditLog>,private notifications:NotificationsService){}
 async students(userId:string){const rows=await this.relationships.find({where:{fromUser:{id:userId},type:RelationshipType.GUARDIAN_OF,status:RelationshipStatus.ACTIVE},relations:{toStudent:true}});return rows.map(r=>this.studentProjection(r.toStudent));}
 async dashboard(userId:string,studentId:string){const student=await this.requireChild(userId,studentId);const [progress,schedule,exams]=await Promise.all([this.progress(userId,studentId),this.schedule(userId,studentId),this.exams(userId,studentId)]);return{student:this.studentProjection(student),today:progress.today,weekly:progress.weekly,upcomingExams:exams.slice(0,5),schedule:schedule.slice(0,1),attention:progress.weekly.completionPercent<50?[{type:"LOW_PLAN_PROGRESS",message:"پیشرفت برنامه این هفته نیاز به حمایت دارد."}]:[]};}
 async progress(userId:string,studentId:string){await this.requireChild(userId,studentId);const now=new Date(),today=now.toISOString().slice(0,10),start=new Date(now);start.setDate(start.getDate()-6);const plans=await this.plans.find({where:{student:{id:studentId},status:PlanStatus.PUBLISHED,date:Between(start.toISOString().slice(0,10),today)},relations:{tasks:true},order:{date:"ASC"}});const totals=plans.reduce((a,p)=>({tasks:a.tasks+p.tasks.length,done:a.done+p.tasks.filter(t=>!!t.completedAt||t.status==="DONE").length}),{tasks:0,done:0});const sessions=await this.sessions.find({where:{student:{id:studentId},startedAt:Between(start,now)}});const seconds=sessions.reduce((n,s)=>n+s.elapsedSeconds,0);const day=plans.find(p=>p.date===today);return{studentId,today:{date:today,totalTasks:day?.tasks.length||0,completedTasks:day?.tasks.filter(t=>!!t.completedAt||t.status==="DONE").length||0},weekly:{from:start.toISOString().slice(0,10),to:today,totalTasks:totals.tasks,completedTasks:totals.done,completionPercent:totals.tasks?Math.round(totals.done/totals.tasks*100):0,studyMinutes:Math.round(seconds/60)}};}
 async schedule(userId:string,studentId:string){await this.requireChild(userId,studentId);const today=new Date().toISOString().slice(0,10);const rows=await this.plans.find({where:{student:{id:studentId},status:PlanStatus.PUBLISHED},relations:{tasks:true},order:{date:"ASC"},take:14});return rows.filter(p=>p.date>=today).map(p=>({id:p.id,date:p.date,tasks:p.tasks.map(t=>({id:t.id,title:t.title,subject:t.subject,startTime:t.startTime,endTime:t.endTime,duration:t.duration,status:t.status,completed:!!t.completedAt}))}));}
 async exams(userId:string,studentId:string){await this.requireChild(userId,studentId);const rows=await this.assignments.find({where:{student:{id:studentId}},relations:{exam:true},order:{assignedAt:"DESC"}});return rows.map(x=>({id:x.exam.id,title:x.exam.title,subject:x.exam.subject,startTime:x.exam.startTime,endTime:x.exam.endTime,durationMinutes:x.exam.duration}));}
 async reports(userId:string,studentId:string){await this.requireChild(userId,studentId);const rows=await this.reportsRepo.find({where:{student:{id:studentId}},order:{planDate:"DESC"},take:30});return rows.map(r=>({id:r.id,planDate:r.planDate,studyHours:r.studyHours,tests:r.tests,correct:r.correct,wrong:r.wrong,blank:r.blank,focus:r.focus,fatigue:r.fatigue,motivation:r.motivation}));}
 async encourage(userId:string,studentId:string,input:{message:string;kind?:string}){const student=await this.requireChild(userId,studentId);const message=String(input.message||"").replace(/<[^>]*>/g,"").trim().slice(0,500);if(!message)throw new ApiException(400,"MESSAGE_REQUIRED","متن تشویق الزامی است.");const guardian=await this.users.findOneByOrFail({id:userId});const row=await this.encouragements.save(this.encouragements.create({student,guardian,message,kind:String(input.kind||"SUPPORT").slice(0,40)}));if(student.user)await this.notifications.createForUser(student.user.id,{type:"GUARDIAN_ENCOURAGEMENT",category:"family",title:"پیام دلگرم‌کننده",body:message,url:"/more"});await this.audit.save(this.audit.create({user:guardian,action:"guardian.encouragement.create",entity:"encouragement",metadata:{encouragementId:row.id,studentId}}));return{id:row.id,createdAt:row.createdAt};}
 private async requireChild(userId:string,studentId:string){const relation=await this.relationships.findOne({where:{fromUser:{id:userId},toStudent:{id:studentId},type:RelationshipType.GUARDIAN_OF,status:RelationshipStatus.ACTIVE},relations:{toStudent:{user:true}}});if(!relation)throw new ApiException(404,"CHILD_NOT_FOUND","دانش‌آموز مرتبط پیدا نشد.");return relation.toStudent;}
 private studentProjection(s:Student){return{id:s.id,name:s.name,grade:s.grade,major:s.major,targetUniversity:s.targetUniversity,targetField:s.targetField};}
}
