import { api } from "../../../shared/api/api";
import type { Student } from "../../../shared/types/domain";
import type { LearningResponse } from "../../learning/learning-model";
import type { StudentForm } from "../model/student-form";
import { studentPayload } from "../model/student-form";
export const createStudent=(body:StudentForm)=>api.post<Student>("/admin/students",studentPayload(body,true));
export const updateStudent=(id:string,body:StudentForm)=>api.patch<Student>(`/admin/students/${id}`,studentPayload(body,false));
export const archiveStudent=(id:string)=>api.delete(`/admin/students/${id}`);
export const studentLifecycle=(id:string,action:"activate"|"deactivate"|"restore"|"force-logout")=>api.post(`/admin/students/${id}/${action}`,{});
export const resetStudentPassword=(id:string,password:string)=>api.post(`/admin/students/${id}/reset-password`,{password});
export const getStudentOverview=(id:string)=>api.get<Record<string,unknown>>(`/admin/students/${id}/overview`);
export const getStudentLearning=(id:string)=>api.get<LearningResponse>(`/admin/students/${id}/learning`);
export const getStudentAttempts=(id:string)=>api.get<unknown[]>(`/admin/students/${id}/attempts`);
export const getStudentWeekly=(id:string)=>api.get<Record<string,unknown>>(`/admin/students/${id}/progress/weekly`);
export const getStudentTopics=(id:string)=>api.get<unknown[]>(`/admin/students/${id}/performance/topics?limit=8`);
