import { api } from "../../../shared/api/api";
import type { Student } from "../../../shared/types/domain";
import type { LearningResponse } from "../../learning/learning-model";
import type { StudentForm } from "../model/student-form";
import { studentPayload } from "../model/student-form";
export const createStudent=(body:StudentForm,organizationId?:string)=>{const payload=studentPayload(body,true);return api.post<Student>("/students",{name:payload.name,username:payload.username,password:payload.password,grade:payload.grade,major:payload.major,...(organizationId?{organizationId}:{})})};
export const updateStudent=(id:string,body:StudentForm)=>api.patch<Student>(`/students/${id}`,studentPayload(body,false));
export const archiveStudent=(id:string)=>api.delete(`/students/${id}`);
export const studentLifecycle=(id:string,action:"activate"|"deactivate"|"restore"|"force-logout")=>api.post(`/students/${id}/${action}`,{});
export const resetStudentPassword=(id:string,password:string)=>api.post(`/students/${id}/reset-password`,{password});
export const getStudentOverview=(id:string)=>api.get<Record<string,unknown>>(`/students/${id}/overview`);
export const getStudentLearning=(id:string)=>api.get<LearningResponse>(`/admin/students/${id}/learning`);
export const getStudentAttempts=(id:string)=>api.get<unknown[]>(`/admin/students/${id}/attempts`);
export const getStudentWeekly=(id:string)=>api.get<Record<string,unknown>>(`/admin/students/${id}/progress/weekly`);
export const getStudentTopics=(id:string)=>api.get<unknown[]>(`/admin/students/${id}/performance/topics?limit=8`);
