import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { DataSource, In, Repository } from "typeorm";
import { ApiException } from "../../common/exceptions/api.exception";
import { MembershipStatus, OrganizationMembership } from "../../database/entities/organization-membership.entity";
import { Organization } from "../../database/entities/organization.entity";
import { Role } from "../../database/entities/role.entity";
import { UserRoleAssignment } from "../../database/entities/user-role-assignment.entity";
import { User } from "../../database/entities/user.entity";
import { AuthenticatedUser } from "../auth/auth.service";
import { AddMemberDto, CreateOrganizationDto, UpdateMemberDto, UpdateOrganizationDto } from "./dto/organization.dto";

@Injectable()
export class OrganizationsService {
  constructor(@InjectRepository(Organization) private orgs: Repository<Organization>, @InjectRepository(OrganizationMembership) private members: Repository<OrganizationMembership>, @InjectRepository(User) private users: Repository<User>, @InjectRepository(Role) private roles: Repository<Role>, @InjectRepository(UserRoleAssignment) private assignments: Repository<UserRoleAssignment>, private dataSource: DataSource) {}
  private platform(user: AuthenticatedUser) { return user.roles?.includes("PLATFORM_ADMIN"); }
  private assertScope(user: AuthenticatedUser, id: string) { if (!this.platform(user) && !user.organizationIds?.includes(id)) throw new ApiException(403, "ORGANIZATION_FORBIDDEN", "به این سازمان دسترسی ندارید."); }
  async list(user: AuthenticatedUser) { return this.platform(user) ? this.orgs.find({ order: { name: "ASC" } }) : this.orgs.find({ where: { memberships: { user: { id: user.id }, status: MembershipStatus.ACTIVE } }, order: { name: "ASC" } }); }
  async get(user: AuthenticatedUser, id: string) { this.assertScope(user, id); const org = await this.orgs.findOne({ where: { id } }); if (!org) throw new ApiException(404, "NOT_FOUND", "سازمان یافت نشد."); return org; }
  create(user: AuthenticatedUser, dto: CreateOrganizationDto) { if (!this.platform(user)) throw new ApiException(403, "FORBIDDEN", "فقط مدیر پلتفرم می‌تواند سازمان بسازد."); return this.orgs.save(this.orgs.create(dto)); }
  async update(user: AuthenticatedUser, id: string, dto: UpdateOrganizationDto) { this.assertScope(user, id); const org = await this.get(user, id); Object.assign(org, dto); return this.orgs.save(org); }
  async listMembers(user: AuthenticatedUser, id: string) { this.assertScope(user, id); return this.members.find({ where: { organization: { id } }, relations: { user: true, roleAssignments: { role: true } } }).then((items) => items.map((m) => ({ id: m.id, user: { id: m.user.id, username: m.user.username, firstName: m.user.firstName, lastName: m.user.lastName, status: m.user.status }, status: m.status, roles: m.roleAssignments.map((a) => a.role.code) }))); }
  async addMember(actor: AuthenticatedUser, organizationId: string, dto: AddMemberDto) { this.assertScope(actor, organizationId); this.assertAssignable(actor, dto.roleCodes); return this.dataSource.transaction(async (manager) => { const user = await manager.findOne(User, { where: { id: dto.userId } }); const org = await manager.findOne(Organization, { where: { id: organizationId } }); if (!user || !org) throw new ApiException(404, "NOT_FOUND", "کاربر یا سازمان یافت نشد."); let membership = await manager.findOne(OrganizationMembership, { where: { user: { id: user.id }, organization: { id: org.id } } }); membership = await manager.save(OrganizationMembership, membership ? Object.assign(membership, { status: MembershipStatus.ACTIVE }) : manager.create(OrganizationMembership, { user, organization: org })); const roles = await manager.find(Role, { where: { code: In(dto.roleCodes), organizationScoped: true } }); if (roles.length !== new Set(dto.roleCodes).size) throw new ApiException(400, "INVALID_ROLE", "نقش سازمانی نامعتبر است."); for (const role of roles) await manager.save(UserRoleAssignment, manager.create(UserRoleAssignment, { user, role, membership })); return { membershipId: membership.id, userId: user.id, roles: roles.map((r) => r.code) }; }); }
  async updateMember(actor: AuthenticatedUser, organizationId: string, userId: string, dto: UpdateMemberDto) { this.assertScope(actor, organizationId); if (dto.roleCodes) this.assertAssignable(actor, dto.roleCodes); return this.dataSource.transaction(async (manager) => { const membership = await manager.findOne(OrganizationMembership, { where: { organization: { id: organizationId }, user: { id: userId } }, relations: { user: true } }); if (!membership) throw new ApiException(404, "NOT_FOUND", "عضویت یافت نشد."); if (dto.status) membership.status = dto.status as MembershipStatus; await manager.save(membership); if (dto.roleCodes) { await manager.delete(UserRoleAssignment, { membership: { id: membership.id } }); const roles = await manager.find(Role, { where: { code: In(dto.roleCodes), organizationScoped: true } }); if (roles.length !== new Set(dto.roleCodes).size) throw new ApiException(400, "INVALID_ROLE", "نقش سازمانی نامعتبر است."); for (const role of roles) await manager.save(UserRoleAssignment, manager.create(UserRoleAssignment, { user: membership.user, membership, role })); } return { userId, status: membership.status, roles: dto.roleCodes }; }); }
  async removeMember(actor: AuthenticatedUser, organizationId: string, userId: string) { this.assertScope(actor, organizationId); const result = await this.members.update({ organization: { id: organizationId }, user: { id: userId } }, { status: MembershipStatus.REMOVED }); if (!result.affected) throw new ApiException(404, "NOT_FOUND", "عضویت یافت نشد."); return { removed: true }; }
  private assertAssignable(actor: AuthenticatedUser, roles: string[]) { if (!this.platform(actor) && roles.includes("PLATFORM_ADMIN")) throw new ApiException(403, "ROLE_ESCALATION", "تخصیص این نقش مجاز نیست."); }
}
