import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Power, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { Badge, Button, Card, EmptyState, Field, Input, Select, Textarea } from "../../components/ui";
import { api } from "../../services/api";
import { useModal } from "../../components/modal";

type Quiz = { id: string; title: string; subject?: string; duration_minutes?: number; active?: number | boolean; exam_id?: string };
type Question = { id: string; question_text?: string; question?: string; option_a?: string; option_b?: string; option_c?: string; option_d?: string; correct_option?: string };

export function QuizzesPage() {
  const qc = useQueryClient(); const [quizId, setQuizId] = useState(""); const [quiz, setQuiz] = useState({ title: "", subject: "", durationMinutes: 20 }); const [question, setQuestion] = useState({ question: "", options: ["", "", "", ""], correctOption: "a", explanation: "" });
  const modal = useModal();
  const quizzes = useQuery({ queryKey: ["quizzes"], queryFn: () => api.get<Quiz[]>("/admin/quizzes") });
  const questions = useQuery({ queryKey: ["quiz-questions", quizId], enabled: !!quizId, queryFn: () => api.get<Question[]>(`/admin/quizzes/${quizId}/questions`) });
  const selected = quizzes.data?.find((item) => item.id === quizId);
  useEffect(() => { if (!quizId && quizzes.data?.[0]) setQuizId(quizzes.data[0].id); }, [quizId, quizzes.data]);
  useEffect(() => { if (selected) setQuiz({ title: selected.title, subject: selected.subject || "", durationMinutes: selected.duration_minutes || 20 }); }, [selected?.id]);
  const save = useMutation({ mutationFn: () => quizId ? api.patch(`/admin/quizzes/${quizId}`, quiz) : api.post<{ id: string }>("/admin/quizzes", quiz), onSuccess: (value) => { qc.invalidateQueries({ queryKey: ["quizzes"] }); if (value && typeof value === "object" && "id" in value) setQuizId(String(value.id)); } });
  const toggle = useMutation({ mutationFn: () => api.patch(`/admin/quizzes/${quizId}`, { active: !selected?.active }), onSuccess: () => qc.invalidateQueries({ queryKey: ["quizzes"] }) });
  const add = useMutation({ mutationFn: () => api.post(`/admin/quizzes/${quizId}/questions`, question), onSuccess: () => { setQuestion({ question: "", options: ["", "", "", ""], correctOption: "a", explanation: "" }); qc.invalidateQueries({ queryKey: ["quiz-questions", quizId] }); } });
  const remove = useMutation({ mutationFn: (id: string) => api.delete(`/admin/questions/${id}`), onSuccess: () => qc.invalidateQueries({ queryKey: ["quiz-questions", quizId] }) });
  return <div className="grid gap-5"><div><h2 className="text-2xl font-black">آزمونک‌ها</h2><p className="text-slate-500">ساخت و ویرایش آزمونک مستقل، فعال‌سازی و مدیریت سؤال‌ها</p></div><section className="grid gap-4 lg:grid-cols-[300px_1fr]"><Card><Button className="mb-3 w-full" variant="soft" onClick={() => { setQuizId(""); setQuiz({ title: "", subject: "", durationMinutes: 20 }); }}>آزمونک جدید</Button>{quizzes.data?.length ? <div className="grid gap-2">{quizzes.data.map((item) => <button key={item.id} className={`rounded-md border p-3 text-right ${quizId === item.id ? "border-brand bg-teal-50" : ""}`} onClick={() => setQuizId(item.id)}><strong>{item.title}</strong><span className="mt-1 flex justify-between text-xs text-slate-500"><span>{item.subject || "بدون درس"}</span><Badge tone={item.active ? "green" : "neutral"}>{item.active ? "فعال" : "غیرفعال"}</Badge></span></button>)}</div> : <EmptyState title="آزمونکی ثبت نشده است." />}</Card>
  <div className="grid gap-4"><Card><div className="grid gap-3 md:grid-cols-3"><Field label="عنوان"><Input value={quiz.title} onChange={(e) => setQuiz({ ...quiz, title: e.target.value })} /></Field><Field label="درس"><Input value={quiz.subject} onChange={(e) => setQuiz({ ...quiz, subject: e.target.value })} /></Field><Field label="مدت (دقیقه)"><Input type="number" value={quiz.durationMinutes} onChange={(e) => setQuiz({ ...quiz, durationMinutes: Number(e.target.value) })} /></Field></div><div className="mt-3 flex gap-2"><Button disabled={!quiz.title || save.isPending} onClick={() => save.mutate()}><Save size={16} />ذخیره</Button>{quizId ? <Button variant="soft" onClick={() => void modal.confirm({ title: selected?.active ? "غیرفعال‌کردن آزمونک؟" : "فعال‌کردن آزمونک؟", description: selected?.active ? "دانش‌آموزان دیگر به این آزمونک دسترسی نخواهند داشت." : "آزمونک دوباره برای دانش‌آموزان قابل استفاده می‌شود.", confirmLabel: selected?.active ? "غیرفعال کن" : "فعال کن" }).then((confirmed) => confirmed && toggle.mutate())}><Power size={16} />{selected?.active ? "غیرفعال" : "فعال"}</Button> : null}</div></Card>
  {quizId ? <section className="grid gap-4 xl:grid-cols-[380px_1fr]"><Card><h3 className="mb-3 font-bold">سؤال جدید</h3><div className="grid gap-2"><Field label="صورت سؤال"><Textarea value={question.question} onChange={(e) => setQuestion({ ...question, question: e.target.value })} /></Field>{question.options.map((value, index) => <Field key={index} label={`گزینه ${index + 1}`}><Input value={value} onChange={(e) => setQuestion({ ...question, options: question.options.map((item, i) => i === index ? e.target.value : item) })} /></Field>)}<Field label="پاسخ"><Select value={question.correctOption} onChange={(e) => setQuestion({ ...question, correctOption: e.target.value })}>{["a", "b", "c", "d"].map((key, index) => <option key={key} value={key}>گزینه {index + 1}</option>)}</Select></Field><Button disabled={!question.question || question.options.some((x) => !x) || add.isPending} onClick={() => add.mutate()}>افزودن سؤال</Button></div></Card><Card><h3 className="mb-3 font-bold">سؤال‌ها</h3>{questions.data?.length ? <div className="grid gap-2">{questions.data.map((item, index) => <article key={item.id} className="rounded-md border p-3"><div className="flex justify-between"><strong>سؤال {index + 1}</strong><Button variant="danger" className="h-8 px-2" onClick={() => void modal.confirm({ title: "حذف سؤال آزمونک؟", description: "این سؤال برای همیشه از آزمونک حذف می‌شود.", tone: "danger", confirmLabel: "حذف" }).then((confirmed) => confirmed && remove.mutate(item.id))}>حذف</Button></div><p className="mt-2 text-sm">{item.question_text || item.question}</p><span className="mt-2 flex items-center gap-1 text-xs text-emerald-700"><CheckCircle2 size={14} />پاسخ {item.correct_option}</span></article>)}</div> : <EmptyState title="سؤالی ثبت نشده است." />}</Card></section> : null}</div></section></div>;
}
