import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { UserPlus } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { Button } from "../../../shared/ui/ui";
import { useStudents } from "../../../shared/hooks/useStudents";
import { useModal } from "../../../shared/ui/modal";
import { normalizePersianText } from "../../../shared/lib/utils";
import { archiveStudent, createStudent, getStudentAttempts, getStudentLearning, getStudentOverview, getStudentTopics, getStudentWeekly, resetStudentPassword, studentLifecycle, updateStudent } from "../api/students.api";
import { StudentAdminAccess } from "../components/StudentAdminAccess";
import { StudentEditor } from "../components/StudentEditor";
import { StudentInsights } from "../components/StudentInsights";
import { StudentList } from "../components/StudentList";
import { countData, emptyStudentForm, studentToForm, type StudentForm } from "../model/student-form";
export function StudentsPage(){const[searchParams]=useSearchParams();const[search,setSearch]=useState("");const[selectedId,setSelectedId]=useState(()=>searchParams.get("studentId")||"");const[form,setForm]=useState<StudentForm>(emptyStudentForm());const{students}=useStudents();const qc=useQueryClient();const modal=useModal();
const create=useMutation({mutationFn:createStudent,onSuccess:(student)=>{qc.invalidateQueries({queryKey:["students"]});setSelectedId(student.id);setForm(studentToForm(student));}});const update=useMutation({mutationFn:()=>updateStudent(selectedId,form),onSuccess:(student)=>{qc.invalidateQueries({queryKey:["students"]});setForm(studentToForm(student));}});const remove=useMutation({mutationFn:()=>archiveStudent(selectedId),onSuccess:()=>{qc.invalidateQueries({queryKey:["students"]});setSelectedId("");setForm(emptyStudentForm());}});const lifecycle=useMutation({mutationFn:(action:"activate"|"deactivate"|"restore"|"force-logout")=>studentLifecycle(selectedId,action),onSuccess:()=>qc.invalidateQueries({queryKey:["students"]})});const resetPassword=useMutation({mutationFn:()=>resetStudentPassword(selectedId,form.password),onSuccess:()=>setForm((c)=>({...c,password:""}))});
const filtered=useMemo(()=>students.filter((s)=>normalizePersianText([s.name,s.id,s.user?.username,s.grade,s.major].filter(Boolean).join(" ")).includes(normalizePersianText(search))),[search,students]);const selected=useMemo(()=>students.find((s)=>s.id===selectedId)??filtered[0]??null,[filtered,selectedId,students]);
const overview=useQuery({queryKey:["student-overview",selectedId],enabled:!!selectedId,queryFn:()=>getStudentOverview(selectedId)});const learning=useQuery({queryKey:["student-learning",selectedId],enabled:!!selectedId,queryFn:()=>getStudentLearning(selectedId)});const attempts=useQuery({queryKey:["student-attempts",selectedId],enabled:!!selectedId,queryFn:()=>getStudentAttempts(selectedId)});const weekly=useQuery({queryKey:["student-weekly",selectedId],enabled:!!selectedId,queryFn:()=>getStudentWeekly(selectedId)});const topics=useQuery({queryKey:["student-topics",selectedId],enabled:!!selectedId,queryFn:()=>getStudentTopics(selectedId)});
useEffect(()=>{if(selected&&selected.id!==selectedId)setSelectedId(selected.id);if(selected)setForm(studentToForm(selected));},[selected?.id]);
function setField(key:keyof StudentForm,value:string){setForm((c)=>({...c,[key]:value}));}
function confirmLifecycle(action:"activate"|"deactivate"|"restore"|"force-logout"){const copy={activate:["فعال‌سازی حساب؟","دانش‌آموز دوباره اجازه ورود خواهد داشت.","فعال‌سازی"],deactivate:["غیرفعال‌سازی حساب؟","نشست‌های دانش‌آموز بسته و ورود او متوقف می‌شود.","غیرفعال‌سازی"],restore:["بازیابی حساب؟","حساب بایگانی‌شده با تمام تاریخچه دوباره فعال می‌شود.","بازیابی"],"force-logout":["خروج اجباری دانش‌آموز؟","تمام نشست‌های فعال این دانش‌آموز فوراً بسته می‌شوند.","خروج اجباری"]}[action];void modal.confirm({title:copy[0],description:copy[1],confirmLabel:copy[2],tone:action==="deactivate"||action==="force-logout"?"danger":"default"}).then((ok)=>ok&&lifecycle.mutate(action));}
return <div className="grid gap-5"><div className="flex justify-end"><Button variant="soft" onClick={()=>{setSelectedId("");setForm(emptyStudentForm())}}><UserPlus size={16}/>دانش‌آموز جدید</Button></div><section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_420px]"><StudentList students={filtered} selectedId={selectedId} search={search} setSearch={setSearch} onSelect={(s)=>{setSelectedId(s.id);setForm(studentToForm(s))}}/><StudentEditor selectedId={selectedId} selected={selected} form={form} setField={setField} onSave={()=>selectedId?update.mutate():create.mutate(form)} onArchive={()=>void modal.confirm({title:"بایگانی دانش‌آموز؟",description:"حساب غیرفعال می‌شود اما تاریخچه برای بازیابی حفظ خواهد شد.",tone:"danger",confirmLabel:"بایگانی"}).then((ok)=>ok&&remove.mutate())} onPassword={()=>void modal.confirm({title:"تغییر رمز دانش‌آموز؟",description:"رمز تغییر می‌کند و تمام نشست‌های قبلی دانش‌آموز بسته می‌شوند.",confirmLabel:"تغییر رمز"}).then((ok)=>ok&&resetPassword.mutate())} onLifecycle={confirmLifecycle} busy={{save:create.isPending||update.isPending,remove:remove.isPending,password:resetPassword.isPending,lifecycle:lifecycle.isPending}}/></section>{selectedId?<StudentInsights values={[{label:"گزارش اخیر",value:countData(overview.data?.recentReports)},{label:"موارد یادگیری",value:learning.data?.summary.totalItems||0},{label:"تلاش آزمون",value:countData(attempts.data)},{label:"روزهای هفتگی",value:countData(weekly.data)},{label:"موضوع عملکرد",value:countData(topics.data)}]}/>:null}<StudentAdminAccess selectedId={selectedId}/></div>}
