#!/bin/bash

echo "Starting architecture audit preparation..."

PROJECT_ROOT=$(pwd)

echo "Project: $PROJECT_ROOT"


# Create documentation structure

mkdir -p docs/audit/database
mkdir -p docs/audit/backend
mkdir -p docs/audit/frontend
mkdir -p docs/audit/security
mkdir -p docs/audit/ux
mkdir -p docs/ai-context


echo "Detecting project technologies..."


DISCOVERY="docs/audit/project-discovery.md"


cat > $DISCOVERY <<EOF
# Project Discovery

Generated by architecture audit hook.

## Detected Files

EOF


# Detect frameworks

if [ -f package.json ]; then

echo "- Node.js project" >> $DISCOVERY

grep -E '"next"|"react"|"nestjs"' package.json >> $DISCOVERY

fi


if [ -f prisma/schema.prisma ]; then

echo "- Prisma Database detected" >> $DISCOVERY

fi


if [ -f docker-compose.yml ]; then

echo "- Docker configuration detected" >> $DISCOVERY

fi


echo "Audit preparation completed."
