import { MigrationInterface,QueryRunner } from "typeorm";
import { randomUUID } from "node:crypto";
export class ConversationChat1724141400000 implements MigrationInterface{name="ConversationChat1724141400000";
 async up(q:QueryRunner){
  await q.query(`CREATE TABLE conversations(id varchar PRIMARY KEY NOT NULL,type varchar(16) NOT NULL,title varchar NOT NULL DEFAULT (''),ownerId varchar,createdAt datetime NOT NULL DEFAULT (datetime('now')),updatedAt datetime NOT NULL DEFAULT (datetime('now')),CONSTRAINT FK_conversation_owner FOREIGN KEY(ownerId) REFERENCES users(id) ON DELETE SET NULL)`);
  await q.query(`CREATE TABLE conversation_members(id varchar PRIMARY KEY NOT NULL,role varchar(16) NOT NULL DEFAULT ('MEMBER'),muted boolean NOT NULL DEFAULT (0),leftAt datetime,lastReadAt datetime,joinedAt datetime NOT NULL DEFAULT (datetime('now')),conversationId varchar NOT NULL,userId varchar NOT NULL,CONSTRAINT FK_member_conversation FOREIGN KEY(conversationId) REFERENCES conversations(id) ON DELETE CASCADE,CONSTRAINT FK_member_user FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT UQ_conversation_member UNIQUE(conversationId,userId))`);
  await q.query(`CREATE INDEX IDX_conversation_member_user ON conversation_members(userId,leftAt)`);
  await q.query(`ALTER TABLE chat_messages ADD COLUMN conversationId varchar REFERENCES conversations(id) ON DELETE CASCADE`);await q.query(`ALTER TABLE chat_messages ADD COLUMN mentions text NOT NULL DEFAULT ('[]')`);await q.query(`ALTER TABLE chat_messages ADD COLUMN replyToId varchar REFERENCES chat_messages(id) ON DELETE SET NULL`);await q.query(`ALTER TABLE chat_messages ADD COLUMN editedAt datetime`);await q.query(`ALTER TABLE chat_messages ADD COLUMN deletedAt datetime`);
  await q.query(`CREATE INDEX IDX_chat_conversation_created ON chat_messages(conversationId,createdAt,id)`);
  const legacy=await q.query(`SELECT id,senderId,receiverId,createdAt FROM chat_messages WHERE receiverId<>'' ORDER BY createdAt`);const pairs=new Map<string,string>();for(const message of legacy){const users=[message.senderId,message.receiverId].sort();const key=users.join(":");let conversationId=pairs.get(key);if(!conversationId){conversationId=randomUUID();pairs.set(key,conversationId);await q.query(`INSERT INTO conversations(id,type,title,ownerId,createdAt,updatedAt)VALUES(?,'DIRECT','',?,?,?)`,[conversationId,users[0],message.createdAt,message.createdAt]);for(const userId of users)await q.query(`INSERT INTO conversation_members(id,conversationId,userId,role)VALUES(?,?,?,'MEMBER')`,[randomUUID(),conversationId,userId]);}await q.query(`UPDATE chat_messages SET conversationId=? WHERE id=?`,[conversationId,message.id]);}
  await q.query(`CREATE TABLE message_reactions(id varchar PRIMARY KEY NOT NULL,emoji varchar(32) NOT NULL,createdAt datetime NOT NULL DEFAULT (datetime('now')),messageId varchar NOT NULL,userId varchar NOT NULL,CONSTRAINT FK_reaction_message FOREIGN KEY(messageId) REFERENCES chat_messages(id) ON DELETE CASCADE,CONSTRAINT FK_reaction_user FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT UQ_message_reaction UNIQUE(messageId,userId,emoji))`);
  for(const key of ["chat.read","chat.send","chat.group.create","chat.group.manage","chat.moderate"])await q.query(`INSERT OR IGNORE INTO permissions(id,code,description)VALUES(lower(hex(randomblob(16))),?,'')`,[key]);
  for(const role of ["STUDENT","GUARDIAN","ADVISOR","TEACHER","MENTOR","CONTENT_MANAGER","ORGANIZATION_ADMIN"])for(const permission of ["chat.read","chat.send"])await q.query(`INSERT OR IGNORE INTO role_permissions(id,roleId,permissionId)SELECT lower(hex(randomblob(16))),r.id,p.id FROM roles r,permissions p WHERE r.code=? AND p.code=?`,[role,permission]);
  for(const role of ["ADVISOR","TEACHER","MENTOR","CONTENT_MANAGER","ORGANIZATION_ADMIN"])for(const permission of ["chat.group.create","chat.group.manage"])await q.query(`INSERT OR IGNORE INTO role_permissions(id,roleId,permissionId)SELECT lower(hex(randomblob(16))),r.id,p.id FROM roles r,permissions p WHERE r.code=? AND p.code=?`,[role,permission]);
  await q.query(`INSERT OR IGNORE INTO role_permissions(id,roleId,permissionId)SELECT lower(hex(randomblob(16))),r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='PLATFORM_ADMIN'`);
 }
 async down(q:QueryRunner){await q.query(`DROP TABLE message_reactions`);await q.query(`DROP TABLE conversation_members`);await q.query(`DROP TABLE conversations`);}
}
