(function(){
var APP_VERSION='1.6.2',CACHE='moshaver-admin-'+APP_VERSION;
var SHELL=['./','./index.html','./css/app.css?v='+APP_VERSION,'./js/ui-utils.shared.js?v='+APP_VERSION,'./js/api-client.shared.js?v='+APP_VERSION,'./js/api.js?v='+APP_VERSION,'./js/push-client.js?v='+APP_VERSION,'./js/core/state.js?v='+APP_VERSION,'./js/utils/dates.js?v='+APP_VERSION,'./js/components/forms.js?v='+APP_VERSION,'./js/components/modal.js?v='+APP_VERSION,'./js/core/connectivity.js?v='+APP_VERSION,'./js/views/reports.js?v='+APP_VERSION,'./js/views/students.js?v='+APP_VERSION,'./js/views/subjects.js?v='+APP_VERSION,'./js/views/system.js?v='+APP_VERSION,'./js/admin.js?v='+APP_VERSION,'./js/update.js?v='+APP_VERSION,'./manifest.webmanifest','./icons/icon-192.png','./icons/icon-512.png','./icons/logo.svg'];
self.addEventListener('install',function(event){event.waitUntil(caches.open(CACHE).then(function(cache){return cache.addAll(SHELL);}));});
self.addEventListener('activate',function(event){event.waitUntil(caches.keys().then(function(keys){return Promise.all(keys.map(function(key){if(key.indexOf('moshaver-admin-')===0&&key!==CACHE)return caches.delete(key);}));}).then(function(){return self.clients.claim();}));});
self.addEventListener('message',function(event){if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',function(event){var request=event.request;if(request.method!=='GET')return;var target=new URL(request.url);if(target.pathname.indexOf('/api/')>=0||target.origin!==self.location.origin||/\/(config\.js|version\.json|sw\.js)$/.test(target.pathname))return;if(request.mode==='navigate'){event.respondWith(fetch(request).then(function(response){var copy=response.clone();caches.open(CACHE).then(function(cache){cache.put('./index.html',copy);});return response;}).catch(function(){return caches.match('./index.html');}));return;}event.respondWith(caches.match(request).then(function(hit){return hit||fetch(request).then(function(response){if(response&&response.status===200){var copy=response.clone();caches.open(CACHE).then(function(cache){cache.put(request,copy);});}return response;});}));});
self.addEventListener('push',function(event){var data={};try{data=event.data?event.data.json():{};}catch(e){}event.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(function(list){if(list.some(function(client){return client.visibilityState==='visible';}))return;return self.registration.showNotification(data.title||'اعلان جدید مشاور',{body:data.body||'',icon:'./icons/icon-192.png',badge:'./icons/icon-192.png',tag:data.notificationId||undefined,data:{url:data.url||'/'}});}));});
self.addEventListener('notificationclick',function(event){event.notification.close();var url=event.notification.data&&event.notification.data.url||'/';event.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(function(list){if(list.length){list[0].focus();list[0].postMessage({type:'NOTIFICATION_CLICK',url:url});return;}return self.clients.openWindow('./');}));});
self.addEventListener('pushsubscriptionchange',function(event){event.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(function(list){return Promise.all(list.map(function(client){client.postMessage({type:'PUSH_SUBSCRIPTION_CHANGED'});}));}));});
})();
