import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { DataSource, IsNull, Repository } from "typeorm";
import { ApiException } from "../../common/exceptions/api.exception";
import { Exam, ExamAssignment, ExamRetryRequest, ExamSyllabus, Mistake, Organization, Quiz, QuizAttempt, QuizQuestion, Student, SyllabusProgress, User } from "../../database/entities";
import { RetryRequestStatus } from "../../database/entities/exam-retry-request.entity";
import { AuthorizationService, UserContext } from "../authorization/authorization.service";
import { CreateQuizDto, ModerateRetryDto, QuizQuestionDto, SubmitQuizDto, SyllabusDto, SyllabusProgressDto, UpdateQuizDto } from "./dto/assessment.dto";

@Injectable()
export class AssessmentsService {
  constructor(
    @InjectRepository(Exam) private exams: Repository<Exam>, @InjectRepository(ExamAssignment) private assignments: Repository<ExamAssignment>,
    @InjectRepository(ExamSyllabus) private syllabus: Repository<ExamSyllabus>, @InjectRepository(SyllabusProgress) private progress: Repository<SyllabusProgress>,
    @InjectRepository(ExamRetryRequest) private retries: Repository<ExamRetryRequest>, @InjectRepository(Quiz) private quizzes: Repository<Quiz>,
    @InjectRepository(QuizQuestion) private questions: Repository<QuizQuestion>, @InjectRepository(QuizAttempt) private attempts: Repository<QuizAttempt>,
    @InjectRepository(Student) private students: Repository<Student>, private authz: AuthorizationService, private db: DataSource,
  ) {}
  private student(userId:string) { return this.students.findOneOrFail({where:{user:{id:userId}}}); }
  async addSyllabus(examId:string,dto:SyllabusDto){ const exam=await this.exams.findOneByOrFail({id:examId}); return this.syllabus.save(this.syllabus.create({...dto,description:dto.description||"",required:!!dto.required,track:dto.track||"",exam})); }
  async removeSyllabus(id:string){ const result=await this.syllabus.delete(id); if(!result.affected) throw new ApiException(404,"SYLLABUS_NOT_FOUND","بودجه آزمون پیدا نشد."); return {id,deleted:true}; }
  async updateProgress(userId:string,id:string,dto:SyllabusProgressDto){ const student=await this.student(userId); const row=await this.syllabus.findOne({where:{id},relations:{exam:true}}); if(!row || !await this.assignments.findOne({where:{exam:{id:row.exam.id},student:{id:student.id}}})) throw new ApiException(404,"SYLLABUS_NOT_FOUND","بودجه آزمون پیدا نشد."); let value=await this.progress.findOne({where:{student:{id:student.id},syllabus:{id}}}); value ||= this.progress.create({student,syllabus:row}); Object.assign(value,{status:dto.status,accuracy:dto.accuracy??0,note:dto.note||""}); return this.progress.save(value); }
  async requestRetry(userId:string,examId:string,message=""){ const student=await this.student(userId); const exam=await this.exams.findOneByOrFail({id:examId}); if(!await this.assignments.findOne({where:{exam:{id:examId},student:{id:student.id}}})) throw new ApiException(404,"EXAM_NOT_ASSIGNED","آزمون در دسترس نیست."); const pending=await this.retries.findOne({where:{exam:{id:examId},student:{id:student.id},status:RetryRequestStatus.PENDING}}); if(pending) return pending; return this.retries.save(this.retries.create({exam,student,message})); }
  async listRetries(context:UserContext){ const rows=await this.retries.find({relations:{exam:true,student:true},order:{createdAt:"DESC"}}); const out=[]; for(const row of rows) if(await this.authz.canAccessStudent(context,row.student.id,"retry_requests.read")) out.push(row); return out; }
  async moderateRetry(context:UserContext,userId:string,id:string,dto:ModerateRetryDto){ if(dto.status===RetryRequestStatus.PENDING) throw new ApiException(400,"INVALID_STATUS","وضعیت نهایی لازم است."); const row=await this.retries.findOne({where:{id},relations:{exam:true,student:true}}); if(!row) throw new ApiException(404,"RETRY_NOT_FOUND","درخواست پیدا نشد."); if(!await this.authz.canAccessStudent(context,row.student.id,"retry_requests.moderate")) throw new ApiException(403,"STUDENT_FORBIDDEN","به این دانش‌آموز دسترسی ندارید."); if(row.status!==RetryRequestStatus.PENDING) throw new ApiException(409,"RETRY_RESOLVED","درخواست قبلا بررسی شده است."); row.status=dto.status; row.moderatorNote=dto.note||""; row.resolvedAt=new Date(); row.resolvedBy=await this.db.manager.findOneByOrFail(User,{id:userId}); if(dto.status===RetryRequestStatus.APPROVED) row.exam.attemptLimit+=1; return this.db.transaction(async m=>{ await m.save(Exam,row.exam); return m.save(ExamRetryRequest,row); }); }
  async listQuizzes(){ return this.quizzes.find({relations:{questions:true,exam:true,organization:true},order:{createdAt:"DESC"}}); }
  async createQuiz(dto:CreateQuizDto){ const [exam,organization]=await Promise.all([dto.examId?this.exams.findOneByOrFail({id:dto.examId}):null,dto.organizationId?this.db.manager.findOneByOrFail(Organization,{id:dto.organizationId}):null]); return this.quizzes.save(this.quizzes.create({...dto,subject:dto.subject||"",durationMinutes:dto.durationMinutes||20,active:dto.active??true,exam,organization})); }
  async updateQuiz(id:string,dto:UpdateQuizDto){ const quiz=await this.quizzes.findOneByOrFail({id}); Object.assign(quiz,dto); return this.quizzes.save(quiz); }
  async quizQuestions(id:string,answers=true){ const quiz=await this.quizzes.findOneByOrFail({id}); const rows=await this.questions.find({where:{quiz:{id}},order:{sortOrder:"ASC"}}); return answers?rows:rows.map(({correctAnswer:_c,explanation:_e,...q})=>q); }
  async addQuizQuestion(id:string,dto:QuizQuestionDto){ if(dto.options.length!==4 || !dto.options.includes(dto.correctAnswer)) throw new ApiException(400,"INVALID_QUESTION","چهار گزینه و پاسخ صحیح معتبر لازم است."); const quiz=await this.quizzes.findOneByOrFail({id}); return this.questions.save(this.questions.create({...dto,explanation:dto.explanation||"",sortOrder:dto.sortOrder||0,quiz})); }
  async studentQuiz(userId:string,id:string){ const student=await this.student(userId); const quiz=await this.quizzes.findOne({where:{id,active:true},relations:{exam:true}}); if(!quiz) throw new ApiException(404,"QUIZ_NOT_FOUND","آزمونک پیدا نشد."); await this.assertQuizAccess(quiz,student.id); return {...quiz,questions:await this.quizQuestions(id,false)}; }
  async startQuiz(userId:string,id:string){ const student=await this.student(userId); const quiz=await this.quizzes.findOne({where:{id,active:true},relations:{exam:true,questions:true}}); if(!quiz) throw new ApiException(404,"QUIZ_NOT_FOUND","آزمونک پیدا نشد."); await this.assertQuizAccess(quiz,student.id); let run=await this.attempts.findOne({where:{quiz:{id},student:{id:student.id},submittedAt:IsNull()},relations:{quiz:{questions:true}}}); if(!run) run=await this.attempts.save(this.attempts.create({quiz,student,startedAt:new Date(),answers:[]})); return this.runPayload(run); }
  async submitQuiz(userId:string,id:string,dto:SubmitQuizDto){ const student=await this.student(userId); const run=await this.attempts.findOne({where:{id:dto.runId,quiz:{id},student:{id:student.id},submittedAt:IsNull()},relations:{quiz:{questions:true}}}); if(!run) throw new ApiException(409,"NO_ACTIVE_ATTEMPT","تلاش فعالی وجود ندارد."); const deadline=run.startedAt.getTime()+run.quiz.durationMinutes*60000; const submittedAt=new Date(); const answers=submittedAt.getTime()>deadline?run.answers:dto.answers; const map=new Map(answers.map(a=>[a.questionId,a.selectedOption||""])); const correct=run.quiz.questions.filter(q=>map.get(q.id)===q.correctAnswer).length; const blank=run.quiz.questions.filter(q=>!map.get(q.id)).length; const wrong=run.quiz.questions.length-correct-blank; return this.db.transaction(async m=>{ Object.assign(run,{answers,correct,wrong,blank,percent:run.quiz.questions.length?Math.round(correct/run.quiz.questions.length*100):0,submittedAt}); await m.save(QuizAttempt,run); for(const q of run.quiz.questions.filter(q=>map.get(q.id)&&map.get(q.id)!==q.correctAnswer)){ const exists=await m.findOne(Mistake,{where:{studentId:student.id,questionId:q.id}}); if(!exists) await m.save(Mistake,m.create(Mistake,{studentId:student.id,questionId:q.id,reason:"",resolved:false})); } return this.result(run); }); }
  async history(userId:string,id?:string){ const student=await this.student(userId); if(id){ const row=await this.attempts.findOne({where:{id,student:{id:student.id}},relations:{quiz:{questions:true}}}); if(!row) throw new ApiException(404,"ATTEMPT_NOT_FOUND","نتیجه پیدا نشد."); return this.result(row); } return this.attempts.find({where:{student:{id:student.id}},relations:{quiz:true},order:{startedAt:"DESC"}}); }
  private async assertQuizAccess(quiz:Quiz,studentId:string){ if(quiz.exam && !await this.assignments.findOne({where:{exam:{id:quiz.exam.id},student:{id:studentId}}})) throw new ApiException(404,"QUIZ_NOT_ASSIGNED","آزمونک در دسترس نیست."); }
  private runPayload(run:QuizAttempt){ const deadline=new Date(run.startedAt.getTime()+run.quiz.durationMinutes*60000); return {runId:run.id,startedAt:run.startedAt,deadline,remainingSeconds:Math.max(0,Math.ceil((deadline.getTime()-Date.now())/1000)),savedAnswers:run.answers,quiz:{id:run.quiz.id,title:run.quiz.title,durationMinutes:run.quiz.durationMinutes,questions:run.quiz.questions.map(({correctAnswer:_c,explanation:_e,...q})=>q)}}; }
  private result(run:QuizAttempt){ const map=new Map(run.answers.map(a=>[a.questionId,a.selectedOption||""])); return {id:run.id,quizId:run.quiz.id,correct:run.correct,wrong:run.wrong,blank:run.blank,percent:run.percent,startedAt:run.startedAt,submittedAt:run.submittedAt,review:run.quiz.questions?.map(q=>({questionId:q.id,selectedOption:map.get(q.id)||null,correctOption:q.correctAnswer,explanation:q.explanation,isCorrect:map.get(q.id)===q.correctAnswer}))||[]}; }
}
