import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "../auth";
import type { RoleCode } from "../../shared/types/domain";
import { Button, Card, EmptyState, Field, Input, Select } from "../../shared/ui/ui";
import { createOrganization, createUser, listOrganizations, listUsers, setUserActive } from "./api/access.api";

const roleLabels: Record<RoleCode, string> = { STUDENT: "دانش‌آموز", GUARDIAN: "سرپرست", ADVISOR: "مشاور", TEACHER: "دبیر", MENTOR: "منتور", CONTENT_MANAGER: "مدیر محتوا", ORGANIZATION_ADMIN: "مدیر سازمان", PLATFORM_ADMIN: "مدیر پلتفرم" };
const staffRoles = Object.keys(roleLabels).filter((role) => role !== "STUDENT") as RoleCode[];

export function UsersPage() {
  const auth = useAuth();
  const qc = useQueryClient();
  const organizationId = auth.context?.activeOrganization?.id;
  const users = useQuery({ queryKey: ["users", organizationId ?? "platform"], queryFn: () => listUsers(organizationId) });
  const [draft, setDraft] = useState({ username: "", password: "", firstName: "", lastName: "", role: "ADVISOR" as RoleCode });
  const create = useMutation({ mutationFn: () => createUser({ username: draft.username, password: draft.password, firstName: draft.firstName, lastName: draft.lastName, roleCodes: [draft.role], ...(organizationId ? { organizationId } : {}) }), onSuccess: async () => { setDraft({ username: "", password: "", firstName: "", lastName: "", role: "ADVISOR" }); await qc.invalidateQueries({ queryKey: ["users"] }); } });
  const toggle = useMutation({ mutationFn: ({ id, active }: { id: string; active: boolean }) => setUserActive(id, active), onSuccess: () => qc.invalidateQueries({ queryKey: ["users"] }) });
  return <div className="grid gap-4"><header><h1 className="text-xl font-black">کاربران و کارکنان</h1><p className="text-sm text-slate-500">مدیریت حساب‌ها در محدوده سازمان فعال</p></header>{auth.can("users.manage") ? <Card><form className="grid gap-3 md:grid-cols-3" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><Field label="نام کاربری"><Input required minLength={2} value={draft.username} onChange={(e) => setDraft({ ...draft, username: e.target.value })} /></Field><Field label="رمز اولیه"><Input required minLength={12} type="password" value={draft.password} onChange={(e) => setDraft({ ...draft, password: e.target.value })} /></Field><Field label="نقش"><Select value={draft.role} onChange={(e) => setDraft({ ...draft, role: e.target.value as RoleCode })}>{staffRoles.filter((role) => role !== "PLATFORM_ADMIN" || auth.hasRole("PLATFORM_ADMIN")).map((role) => <option key={role} value={role}>{roleLabels[role]}</option>)}</Select></Field><Field label="نام"><Input value={draft.firstName} onChange={(e) => setDraft({ ...draft, firstName: e.target.value })} /></Field><Field label="نام خانوادگی"><Input value={draft.lastName} onChange={(e) => setDraft({ ...draft, lastName: e.target.value })} /></Field><div className="flex items-end"><Button className="w-full" loading={create.isPending}>ساخت حساب</Button></div>{create.isError ? <p role="alert" className="text-sm text-rose-700">{create.error instanceof Error ? create.error.message : "ساخت حساب ناموفق بود."}</p> : null}</form></Card> : null}<Card>{users.isLoading ? <div className="h-32 animate-pulse rounded-lg bg-slate-100" /> : users.isError ? <div role="alert"><p className="text-rose-700">دریافت کاربران ناموفق بود.</p><Button variant="soft" onClick={() => users.refetch()}>تلاش دوباره</Button></div> : !users.data?.length ? <EmptyState title="کاربری در این محدوده نیست." /> : <div className="grid gap-2">{users.data.map((user) => <div key={user.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><strong>{[user.firstName, user.lastName].filter(Boolean).join(" ") || user.username}</strong><p className="text-xs text-slate-500" dir="ltr">{user.username} · {user.assignments.map((item) => roleLabels[item.role] || item.role).join("، ")}</p></div>{auth.can("users.manage") ? <Button variant="soft" loading={toggle.isPending} onClick={() => toggle.mutate({ id: user.id, active: user.status !== "ACTIVE" })}>{user.status === "ACTIVE" ? "غیرفعال‌سازی" : "فعال‌سازی"}</Button> : null}</div>)}</div>}</Card></div>;
}

export function OrganizationsPage() {
  const auth = useAuth();
  const qc = useQueryClient();
  const organizations = useQuery({ queryKey: ["organizations"], queryFn: listOrganizations });
  const [name, setName] = useState("");
  const create = useMutation({ mutationFn: () => createOrganization({ name, type: "SCHOOL" }), onSuccess: async () => { setName(""); await qc.invalidateQueries({ queryKey: ["organizations"] }); } });
  return <div className="grid gap-4"><header><h1 className="text-xl font-black">سازمان‌ها</h1><p className="text-sm text-slate-500">محدوده‌های عضویت و دسترسی</p></header>{auth.hasRole("PLATFORM_ADMIN") && auth.can("organization.manage") ? <Card><form className="flex flex-col gap-3 sm:flex-row" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><Field label="نام سازمان"><Input required minLength={2} value={name} onChange={(e) => setName(e.target.value)} /></Field><Button className="self-end" loading={create.isPending}>ساخت سازمان</Button></form>{create.isError ? <p role="alert" className="mt-2 text-sm text-rose-700">{create.error instanceof Error ? create.error.message : "ساخت سازمان ناموفق بود."}</p> : null}</Card> : null}<Card>{organizations.isLoading ? <div className="h-32 animate-pulse rounded-lg bg-slate-100" /> : organizations.isError ? <div role="alert"><p className="text-rose-700">دریافت سازمان‌ها ناموفق بود.</p><Button variant="soft" onClick={() => organizations.refetch()}>تلاش دوباره</Button></div> : !organizations.data?.length ? <EmptyState title="سازمانی یافت نشد." /> : <div className="grid gap-2">{organizations.data.map((organization) => <button type="button" key={organization.id} className="rounded-lg border p-3 text-right hover:bg-slate-50" onClick={() => auth.setActiveOrganization(auth.context?.availableOrganizations.find((item) => item.id === organization.id) ?? null)}><strong>{organization.name}</strong><p className="text-xs text-slate-500">{organization.type} · {organization.status}</p></button>)}</div>}</Card></div>;
}
