(function(global){
'use strict';
var state={me:null,dashboard:null,plan:null,exams:[],subjects:[],reviews:[],mistakes:[],activeSession:null,currentTask:null,selectedTask:null,selectedIssueType:'',quiz:null,quizRunId:null,quizIndex:0,quizAnswers:{},quizStartedAt:null,timerTicker:null,presenceTicker:null,sessionHeartbeat:null,scheduleDate:'',busyQuiz:false,chatConversation:null,chatMessages:[],chatUnread:0,eventSource:null,chatPoll:null,authEpoch:0,startupAuthRequest:null,loginRequest:null,authStatus:'checking',bootEpoch:0,lastSyncAt:0,sessionActionBusy:false,quizTimer:null,quizSubmitting:false,chatSending:false,authRetryTimer:null,currentExamId:null,currentExamCloseAt:null,examRefreshTimer:null};
var AUTH_SIGNAL_KEY='moshaver_student_auth_signal';
var typeLabels={study:'مطالعه',review:'مرور',test:'تست',class:'کلاس',prayer:'نماز',meal:'غذا',break:'استراحت',exam:'آزمون'};
var typeIcons={study:'book',review:'review',test:'test',class:'class',prayer:'prayer',meal:'meal',break:'break',exam:'exam'};
var issueTypes=['مطلب را نفهمیدم','فراموش کردم','تمرکز نداشتم','خواب‌آلود بودم','زمان کم آوردم','خیلی سخت بود','برنامه به‌هم خورد','سایر'];
var mistakeReasons=['ضعف علمی','فراموشی','بی‌دقتی','شک','کمبود زمان','بدخوانی سؤال','محاسبات','عدم تسلط مفهومی'];
function el(id){return document.getElementById(id);}function q(sel,root){return(root||document).querySelector(sel);}function qa(sel,root){return(root||document).querySelectorAll(sel);}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function icon(name,cls){return '<svg class="'+(cls||'icon')+'"><use href="#i-'+name+'" xlink:href="#i-'+name+'"></use></svg>';}
function faNum(v){var s=String(v==null?'':v),m='۰۱۲۳۴۵۶۷۸۹';return s.replace(/[0-9]/g,function(x){return m.charAt(Number(x));});}
function g2j(gy,gm,gd){var gdm=[0,31,59,90,120,151,181,212,243,273,304,334],jy,days,jm,jd,gy2;if(gy>1600){jy=979;gy-=1600;}else{jy=0;gy-=621;}gy2=gm>2?gy+1:gy;days=365*gy+Math.floor((gy2+3)/4)-Math.floor((gy2+99)/100)+Math.floor((gy2+399)/400)-80+gd+gdm[gm-1];jy+=33*Math.floor(days/12053);days%=12053;jy+=4*Math.floor(days/1461);days%=1461;if(days>365){jy+=Math.floor((days-1)/365);days=(days-1)%365;}if(days<186){jm=1+Math.floor(days/31);jd=1+(days%31);}else{jm=7+Math.floor((days-186)/30);jd=1+((days-186)%30);}return{jy:jy,jm:jm,jd:jd};}
function shamsiParts(iso){var m=String(iso||'').match(/^(\d{4})-(\d{2})-(\d{2})/);if(!m)return null;var g={y:Number(m[1]),m:Number(m[2]),d:Number(m[3])},j=g2j(g.y,g.m,g.d),dt=new Date(g.y,g.m-1,g.d,12,0,0);return{year:j.jy,month:j.jm,day:j.jd,weekday:dt.getDay()};}
function shamsiDate(iso,withWeekday){var p=shamsiParts(iso);if(!p)return String(iso||'');var months=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'],days=['یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه','شنبه'];return (withWeekday?days[p.weekday]+' ':'')+faNum(p.day)+' '+months[p.month-1]+' '+faNum(p.year);}
function shamsiDateTime(v){if(!v)return'—';var raw=String(v),date=raw.slice(0,10),time='';var tm=raw.match(/T(\d{2}):(\d{2})/);if(tm)time=faNum(tm[1]+':'+tm[2]);return shamsiDate(date,false)+(time?'، '+time:'');}
function isoToday(){var d=new Date(),y=d.getFullYear(),m=('0'+(d.getMonth()+1)).slice(-2),day=('0'+d.getDate()).slice(-2);return y+'-'+m+'-'+day;}
function shiftDate(iso,days){var d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+days);return d.getFullYear()+'-'+('0'+(d.getMonth()+1)).slice(-2)+'-'+('0'+d.getDate()).slice(-2);}
function hhmm(){var d=new Date();return('0'+d.getHours()).slice(-2)+':'+('0'+d.getMinutes()).slice(-2);}
function plannedMinutes(task){if(!task)return 0;var a=task.start.split(':'),b=task.end.split(':');return Math.max(0,(+b[0]*60 + +b[1])-(+a[0]*60 + +a[1]));}
function toast(msg,type){var stack=el('toastStack');if(!stack)return;var card=document.createElement('div'),kind=type||((/خطا|نشد|نامعتبر|نیست/.test(String(msg)))?'error':'success');card.className='toast-card '+kind;card.innerHTML='<span class="toast-icon">'+icon(kind==='error'?'alert':'check2')+'</span><div><strong>'+(kind==='error'?'نیاز به توجه':'انجام شد')+'</strong><p>'+esc(msg)+'</p></div>';stack.appendChild(card);setTimeout(function(){card.classList.add('leaving');setTimeout(function(){if(card.parentNode)card.parentNode.removeChild(card);},220);},3600);}
function setButtonBusy(btn,busy){if(!btn)return;btn.disabled=!!busy;btn.classList.toggle('busy',!!busy);}
function autoGrow(t){if(!t)return;t.style.height='auto';t.style.height=Math.min(120,t.scrollHeight)+'px';}
function shortDateTime(v){return shamsiDateTime(v);}
function chatDayLabel(day){if(!day)return'';var t=isoToday();if(day===t)return'امروز';if(day===shiftDate(t,-1))return'دیروز';return shamsiDate(day,true);}
function api(method,path,body,cb){
  var epoch=state.authEpoch;
  return API.request(method,path,body,function(err,data,status){
    if(epoch!==state.authEpoch)return;
    if(!err)state.lastSyncAt=Date.now();
    if(cb)cb(err,data,status);
  });
}
function queueKey(){return 'moshaver_queue:'+(state.me&&state.me.id?state.me.id:'anonymous');}
function queued(method,path,body,cb){if(navigator.onLine===false){var arr=[];try{arr=JSON.parse(localStorage.getItem(queueKey())||'[]');}catch(e){}arr.push({method:method,path:path,body:body,at:new Date().toISOString()});try{localStorage.setItem(queueKey(),JSON.stringify(arr));}catch(e){}setSync('در صف');toast('آفلاین است؛ تغییر بعداً همگام می‌شود.');if(cb)cb(null,{queued:true});return;}api(method,path,body,cb);}
function flushQueue(){if(navigator.onLine===false||!state.me)return;var key=queueKey(),arr=[];try{arr=JSON.parse(localStorage.getItem(key)||'[]');}catch(e){}if(!arr.length){setSync('همگام');return;}var item=arr[0];api(item.method,item.path,item.body,function(err){if(err){setSync('خطا');return;}arr.shift();try{localStorage.setItem(key,JSON.stringify(arr));}catch(e){}flushQueue();});}
function setSync(text){var s=el('syncState');if(s){q('span',s).textContent=text;}}
function showLogin(message){
  el('loginScreen').className='login-shell';
  el('appScreen').className='app hidden';
  stopPresence();disconnectEvents();hideFocus();stopSessionClock();
  var err=el('loginError'),btn=q('#loginForm button[type="submit"]');
  if(btn)btn.disabled=false;
  if(message){err.textContent=message;err.className='form-error';}
  else{err.textContent='';err.className='form-error hidden';}
}
function showApp(){
  el('loginScreen').className='login-shell hidden';
  el('appScreen').className='app';
  var err=el('loginError');if(err){err.textContent='';err.className='form-error hidden';}
  startPresence();
}
function resetAuthenticatedState(){
  state.me=null;state.dashboard=null;state.plan=null;state.exams=[];state.subjects=[];state.reviews=[];state.mistakes=[];
  state.activeSession=null;state.currentTask=null;state.selectedTask=null;state.chatConversation=null;state.chatMessages=[];state.chatUnread=0;
  state.busyQuiz=false;state.quiz=null;state.quizRunId=null;state.sessionActionBusy=false;state.currentExamId=null;state.currentExamCloseAt=null;clearExamRefresh();
}
function hasPendingLogout(){try{return sessionStorage.getItem('moshaver_logout_pending')==='1';}catch(e){return false;}}
function setPendingLogout(value){try{if(value)sessionStorage.setItem('moshaver_logout_pending','1');else sessionStorage.removeItem('moshaver_logout_pending');}catch(e){}}
function broadcastAuth(kind){try{localStorage.setItem(AUTH_SIGNAL_KEY,JSON.stringify({kind:kind,at:Date.now()}));}catch(e){}}
function finishLocalLogout(message,keepPending,skipBroadcast){
  state.authStatus='anonymous';state.authEpoch++;state.bootEpoch++;
  API.clearAuth();API.abortAll();stopPresence();disconnectEvents();stopSessionClock();resetAuthenticatedState();
  if(!keepPending)setPendingLogout(false);
  el('loginPassword').value='';
  showLogin(message||'با موفقیت خارج شدید.');
  if(!skipBroadcast)broadcastAuth('logout');
}
function handleAuthFailure(err){
  if(state.authStatus!=='authenticated')return;
  setPendingLogout(false);
  finishLocalLogout((err&&err.message)||'نشست شما پایان یافته است. دوباره وارد شوید.',false,false);
}
function flushPendingLogout(done){
  if(!hasPendingLogout()){if(done)done(null);return;}
  API.request('POST','/auth/logout',{},function(err){
    if(err&&err.status===0){if(done)done(err);return;}
    setPendingLogout(false);API.clearAuth();if(done)done(null);
  },{suppressAuthFailure:true,noCsrfRetry:true});
}
function clearWrongRoleSession(message){
  state.authStatus='logging-out';setPendingLogout(true);
  API.request('POST','/auth/logout',{},function(err){
    finishLocalLogout(message,!!(err&&err.status===0),false);
  },{suppressAuthFailure:true,noCsrfRetry:true});
}
function closeModals(){var ms=qa('.modal');for(var i=0;i<ms.length;i++)ms[i].classList.add('hidden');el('modalBackdrop').className='modal-backdrop hidden';}
function openModal(id){el('modalBackdrop').className='modal-backdrop';el(id).classList.remove('hidden');}
function bindClosers(){var xs=qa('[data-close]');for(var i=0;i<xs.length;i++)xs[i].onclick=function(){closeModals();};el('modalBackdrop').onclick=function(){closeModals();};}
function switchView(name){var vs=qa('.view'),ns=qa('.nav-item');for(var i=0;i<vs.length;i++)vs[i].classList.remove('active');for(i=0;i<ns.length;i++)ns[i].classList.remove('active');var target=el('view-'+name);if(!target)return;target.classList.add('active');var n=q('.nav-item[data-view="'+name+'"]');if(n)n.classList.add('active');if(name==='exams')loadExams();if(name==='progress')loadProgress();if(name==='schedule')loadSchedule(state.scheduleDate||isoToday());if(name==='chat'){loadChat(true);setTimeout(scrollChatBottom,80);}window.scrollTo(0,0);}
function bindNav(){var ns=qa('.nav-item');for(var i=0;i<ns.length;i++)ns[i].onclick=function(){switchView(this.getAttribute('data-view'));};}
function deviceLabel(){var ua=navigator.userAgent||'';if(/Android/i.test(ua))return 'Android';if(/iPhone|iPad/i.test(ua))return 'iOS';return 'Web';}
function startPresence(){stopPresence();sendPresence();state.presenceTicker=setInterval(sendPresence,45000);}
function stopPresence(){if(state.presenceTicker)clearInterval(state.presenceTicker);state.presenceTicker=null;if(state.sessionHeartbeat)clearInterval(state.sessionHeartbeat);state.sessionHeartbeat=null;}
function sendPresence(){if(!state.me)return;var st=state.activeSession?'studying':(state.busyQuiz?'quiz':'online');api('POST','/presence',{state:st,taskId:state.activeSession?state.activeSession.taskId:null,sessionId:state.activeSession?state.activeSession.id:null,deviceLabel:deviceLabel()},function(){});}
function record(eventType,entityType,entityId,meta){if(!state.me)return;api('POST','/activity',{eventType:eventType,entityType:entityType||'',entityId:entityId||'',metadata:meta||{},state:state.activeSession?'studying':'online',taskId:state.activeSession?state.activeSession.taskId:null,sessionId:state.activeSession?state.activeSession.id:null,deviceLabel:deviceLabel()},function(){});}
function loadMe(done){var epoch=++state.authEpoch;state.authStatus='checking';state.startupAuthRequest=API.request('GET','/auth/me',null,function(err,data){state.startupAuthRequest=null;if(epoch!==state.authEpoch)return;if(err){if(err.status===401)state.authStatus='anonymous';else state.authStatus='checking';return done&&done(err);}if(!data||data.role!=='student'){clearWrongRoleSession('این حساب دانش‌آموز نیست.');return done&&done({status:403,message:'این حساب دانش‌آموز نیست.',handled:true});}state.me=data;state.authStatus='authenticated';done&&done(null,data);},{suppressAuthFailure:true});}
function cancelStartupAuth(){
  state.authEpoch++;
  if(state.startupAuthRequest){try{state.startupAuthRequest.abort();}catch(e){}state.startupAuthRequest=null;}
}
function loadDashboard(date){date=date||isoToday();api('GET','/dashboard?date='+encodeURIComponent(date),null,function(err,data){if(err){toast(err.message);return;}state.dashboard=data;state.plan=data.plan;state.subjects=data.subjects||[];el('studentSubtitle').textContent=(data.student.grade||'')+' • '+(data.student.major||'');el('helloName').textContent='سلام '+data.student.name+' 👋';el('notificationBadge').textContent=faNum(data.unreadNotifications||0);el('notificationBadge').className=(data.unreadNotifications?'badge':'badge hidden');renderToday();loadReviews();restoreSession();});}
function renderToday(){var d=state.dashboard||{},plan=d.plan,metrics=d.planMetrics||{};el('todayPersian').textContent=plan&&plan.persianDate?plan.persianDate:shamsiDate(isoToday(),true);el('planTitle').textContent=plan&&plan.title?plan.title:'فعالیت‌های امروز';renderMotivation(plan);el('metricTasks').textContent=faNum((metrics.doneTasks||0)+(metrics.partialTasks||0))+'/'+faNum(metrics.totalTasks||0);var pct=metrics.totalTasks?Math.round(((metrics.doneTasks||0)+(metrics.partialTasks||0)*.5)*100/metrics.totalTasks):0;el('metricTasksBar').style.width=pct+'%';el('metricMinutes').textContent=faNum(metrics.actualMinutes||0)+' دقیقه';el('plannedMinutes').textContent='از '+faNum(metrics.plannedMinutes||0)+' دقیقه';el('metricTests').textContent=faNum(metrics.actualTests||0);el('plannedTests').textContent='هدف '+faNum(metrics.plannedTests||0);renderCurrent();renderTimeline(plan?plan.tasks:[],'todayTimeline');renderExamFocus(d.nextExam);}
function renderMotivation(plan){var box=el('motivationCard'),text=plan&&plan.motivationText?String(plan.motivationText).replace(/^\s+|\s+$/g,''):'';if(!box)return;if(!text){box.className='daily-motivation hidden';return;}el('motivationText').textContent=text;box.className='daily-motivation';}
function statusForTask(t,nowTime){if(t.completion)return t.completion.status==='done'?'done':(t.completion.status==='partial'?'partial':'skipped');if(t.start<=nowTime&&nowTime<t.end)return'current';if(t.end<=nowTime)return'overdue';return'next';}
function getCurrentAndNext(tasks){var nowT=hhmm(),cur=null,next=null;for(var i=0;i<tasks.length;i++){var t=tasks[i];if(t.completion)continue;if(t.start<=nowT&&nowT<t.end){cur=t;break;}if(!next&&t.start>nowT)next=t;}if(!cur&&state.activeSession){for(i=0;i<tasks.length;i++)if(tasks[i].id===state.activeSession.taskId){cur=tasks[i];break;}}return{current:cur,next:next};}
function renderCurrent(){var tasks=state.plan&&state.plan.tasks?state.plan.tasks:[],cn=getCurrentAndNext(tasks);state.currentTask=cn.current;el('nowTime').textContent=hhmm();if(!cn.current){el('nowEmpty').className='empty-now';el('nowTask').className='hidden';}else{var t=cn.current;el('nowEmpty').className='empty-now hidden';el('nowTask').className='';el('nowSubject').textContent=t.subject||typeLabels[t.type]||'فعالیت';el('nowTitle').textContent=t.title||typeLabels[t.type]||'فعالیت';el('nowTypeIcon').innerHTML=icon(typeIcons[t.type]||'book');var meta='<span>'+esc(t.start)+' تا '+esc(t.end)+'</span>';if(t.pages)meta+='<span>صفحه '+esc(t.pages)+'</span>';if(t.testCount)meta+='<span>'+faNum(t.testCount)+' تست</span>';el('nowMeta').innerHTML=meta;if(t.type==='exam'&&t.examId)el('startNowBtn').innerHTML=icon('test')+'<span>باز کردن آزمون</span>';else el('startNowBtn').innerHTML=state.activeSession&&state.activeSession.taskId===t.id?icon('check')+'<span>پایان مطالعه</span>':icon('play')+'<span>شروع مطالعه</span>';}
if(cn.next){el('nextStrip').className='next-strip';el('nextTitle').textContent=(cn.next.subject?cn.next.subject+' — ':'')+(cn.next.title||'فعالیت');el('nextTime').textContent=cn.next.start;}else el('nextStrip').className='next-strip hidden';}
function taskCardHtml(t){var status=statusForTask(t,hhmm()),label={done:'انجام شده',partial:'نیمه‌کاره',skipped:'رد شده',current:'الان',overdue:'نیازمند تصمیم',next:'بعدی'}[status]||'';var cls=status==='partial'?'done':status,examCta=(t.type==='exam'&&t.examId&&!t.completion)?'<button class="timeline-exam-btn" data-task-exam="'+esc(t.examId)+'">'+icon('test')+'<span>باز کردن آزمون</span></button>':'';var details=(t.pages?'صفحه '+t.pages:'')+(t.testCount?(t.pages?' • ':'')+faNum(t.testCount)+' تست':'')+(t.note?((t.pages||t.testCount)?' • ':'')+t.note:'');return '<div class="timeline-item" data-task="'+esc(t.id)+'"><div class="timeline-time">'+faNum(t.start)+'</div><div class="timeline-card '+cls+(t.type==='exam'?' exam-task-card':'')+'"><div class="timeline-card-top"><span class="status-chip">'+label+'</span><span class="task-kind">'+esc(typeLabels[t.type]||'فعالیت')+'</span></div><div class="timeline-main"><span class="round-icon">'+icon(typeIcons[t.type]||'book')+'</span><div class="timeline-copy"><h4>'+esc((t.subject?t.subject+' — ':'')+(t.title||typeLabels[t.type]||'فعالیت'))+'</h4>'+(details?'<p>'+esc(details)+'</p>':'')+'</div></div>'+examCta+'</div></div>';}
function renderTimeline(tasks,target){var box=el(target);if(!tasks||!tasks.length){box.innerHTML='<div class="empty-card">برای این روز برنامه‌ای منتشر نشده است.</div>';return;}var html='';for(var i=0;i<tasks.length;i++)html+=taskCardHtml(tasks[i]);box.innerHTML=html;var cards=qa('[data-task]',box);for(i=0;i<cards.length;i++)cards[i].onclick=function(){var t=findTask(this.getAttribute('data-task'),tasks);if(t&&t.type==='exam'&&t.examId){openExam({id:t.examId});return;}openTask(t);};var examBtns=qa('[data-task-exam]',box);for(i=0;i<examBtns.length;i++)examBtns[i].onclick=function(e){if(e){e.preventDefault();e.stopPropagation();}openExam({id:this.getAttribute('data-task-exam')});};}
function findTask(id,tasks){tasks=tasks||(state.plan?state.plan.tasks:[]);for(var i=0;i<(tasks||[]).length;i++)if(tasks[i].id===id)return tasks[i];return null;}
function openTask(t){if(!t)return;if(t.type==='exam'&&t.examId){openExam({id:t.examId});return;}state.selectedTask=t;record('task.opened','task',t.id,{});var body='<div class="task-modal-head"><span class="round-icon">'+icon(typeIcons[t.type]||'book')+'</span><div><div class="eyebrow">'+esc(typeLabels[t.type]||'فعالیت')+'</div><h3>'+esc((t.subject?t.subject+' — ':'')+(t.title||''))+'</h3></div></div><div class="task-detail-grid"><span>'+esc(t.start)+' تا '+esc(t.end)+'</span>'+(t.pages?'<span>صفحه '+esc(t.pages)+'</span>':'')+(t.testCount?'<span>'+faNum(t.testCount)+' تست</span>':'')+'</div>'+(t.note?'<p class="muted">'+esc(t.note)+'</p>':'')+'<div id="taskComments"></div><div class="task-actions"><button id="modalStudyBtn" class="btn primary">'+(state.activeSession&&state.activeSession.taskId===t.id?'پایان مطالعه':'شروع')+'</button><button id="modalDoneBtn" class="btn soft">انجام شد</button><button id="modalPartialBtn" class="btn soft">نیمه‌کاره</button></div><button id="modalIssueBtn" class="btn ghost full">'+icon('alert')+' این بخش برایم مشکل دارد</button>'+(t.quizId?'<button id="modalQuizBtn" class="btn soft full">'+icon('test')+' شروع آزمونک مرتبط</button>':'');el('taskModalBody').innerHTML=body;openModal('taskModal');el('modalStudyBtn').onclick=function(){if(state.activeSession&&state.activeSession.taskId===t.id)finishStudy();else startStudy(t);};el('modalDoneBtn').onclick=function(){completeTask(t,'done');};el('modalPartialBtn').onclick=function(){completeTask(t,'partial');};el('modalIssueBtn').onclick=function(){openIssue(t);};if(el('modalQuizBtn'))el('modalQuizBtn').onclick=function(){startQuiz(t.quizId);};api('GET','/tasks/'+encodeURIComponent(t.id)+'/comments',null,function(err,comments){if(err||!comments||!comments.length)return;var h='<div class="eyebrow" style="margin-top:14px">پیام مشاور</div>';for(var i=0;i<comments.length;i++)h+='<div class="advisor-comment">'+esc(comments[i].body)+'</div>';el('taskComments').innerHTML=h;});}
function completeTask(t,status){var mins=state.activeSession&&state.activeSession.taskId===t.id?Math.round((Date.now()-new Date(state.activeSession.startedAt).getTime())/60000):plannedMinutes(t);queued('PUT','/tasks/'+encodeURIComponent(t.id)+'/completion',{status:status,actualMinutes:mins,actualTests:status==='done'?Number(t.testCount||0):0,note:''},function(err){if(err)return toast(err.message);if(state.activeSession&&state.activeSession.taskId===t.id)finishStudy(true);else{closeModals();toast(status==='done'?'ثبت شد ✓':'نیمه‌کاره ثبت شد');loadDashboard();}});}
function showFocus(t){if(!t)return;el('focusSubject').textContent=t.subject||typeLabels[t.type]||'مطالعه';el('focusTitle').textContent=t.title||'';var g='';if(t.pages)g+='<span>صفحه '+esc(t.pages)+'</span>';if(t.testCount)g+='<span>'+faNum(t.testCount)+' تست</span>';g+='<span>'+esc(t.start)+' تا '+esc(t.end)+'</span>';el('focusGoal').innerHTML=g;el('focusMode').className='focus-mode';}
function hideFocus(){if(el('focusMode'))el('focusMode').className='focus-mode hidden';}
function startStudy(t){if(!t||state.sessionActionBusy)return;state.sessionActionBusy=true;api('POST','/study-sessions/start',{taskId:t.id,deviceLabel:deviceLabel()},function(err,data){state.sessionActionBusy=false;if(err){if(err.code==='ACTIVE_STUDY_SESSION'){restoreSession();toast('یک جلسه مطالعه دیگر فعال است؛ ابتدا همان را تمام کن.');return;}return toast(err.message);}state.activeSession=data;closeModals();startSessionClock();renderCurrent();showFocus(t);toast('مطالعه شروع شد');});}
function restoreSession(){api('GET','/study-sessions/active',null,function(err,data){if(err)return;state.activeSession=data||null;if(data){startSessionClock();var ft=findTask(data.taskId);if(ft)showFocus(ft);}else{stopSessionClock();hideFocus();}renderCurrent();});}
function startSessionClock(){stopSessionClock();if(!state.activeSession)return;el('activeTimer').className='active-timer';updateTimer();state.timerTicker=setInterval(updateTimer,1000);state.sessionHeartbeat=setInterval(function(){if(!state.activeSession)return;api('POST','/study-sessions/'+state.activeSession.id+'/heartbeat',{deviceLabel:deviceLabel()},function(){});},45000);}
function stopSessionClock(){if(state.timerTicker)clearInterval(state.timerTicker);state.timerTicker=null;if(state.sessionHeartbeat)clearInterval(state.sessionHeartbeat);state.sessionHeartbeat=null;el('activeTimer').className='active-timer hidden';}
function updateTimer(){if(!state.activeSession)return;var sec=Math.max(0,Math.floor((Date.now()-new Date(state.activeSession.startedAt).getTime())/1000)),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;var txt=('0'+h).slice(-2)+':'+('0'+m).slice(-2)+':'+('0'+s).slice(-2);el('timerDisplay').textContent=txt;if(el('focusTimer'))el('focusTimer').textContent=txt;}
function finishStudy(silent){if(!state.activeSession||state.sessionActionBusy)return;var id=state.activeSession.id;state.sessionActionBusy=true;api('POST','/study-sessions/'+id+'/finish',{deviceLabel:deviceLabel()},function(err,data){state.sessionActionBusy=false;if(err){if(err.status===404){state.activeSession=null;stopSessionClock();hideFocus();loadDashboard();return;}return toast(err.message);}state.activeSession=null;stopSessionClock();hideFocus();closeModals();if(!silent)toast('جلسه با '+faNum(data.actualMinutes)+' دقیقه ثبت شد');loadDashboard();});}
function openIssue(t){state.selectedTask=t;state.selectedIssueType='';var h='';for(var i=0;i<issueTypes.length;i++)h+='<button class="choice-btn" data-issue="'+esc(issueTypes[i])+'">'+esc(issueTypes[i])+'</button>';el('issueChoices').innerHTML=h;el('issueNote').value='';closeModals();openModal('issueModal');var bs=qa('[data-issue]',el('issueChoices'));for(i=0;i<bs.length;i++)bs[i].onclick=function(){var all=qa('[data-issue]',el('issueChoices'));for(var j=0;j<all.length;j++)all[j].classList.remove('active');this.classList.add('active');state.selectedIssueType=this.getAttribute('data-issue');};}
function submitIssue(){if(!state.selectedIssueType)return toast('نوع مشکل را انتخاب کن.');queued('POST','/task-issues',{taskId:state.selectedTask?state.selectedTask.id:null,issueType:state.selectedIssueType,note:el('issueNote').value},function(err){if(err)return toast(err.message);closeModals();toast('برای مشاور ارسال شد.');});}
function loadReviews(){api('GET','/reviews',null,function(err,data){if(err)return;state.reviews=data||[];renderReviews();});}
function renderReviews(){var box=el('reviewCard'),list=el('reviewList');if(!state.reviews.length){box.className='review-card hidden';return;}box.className='review-card';el('reviewCount').textContent=faNum(state.reviews.length);var h='';for(var i=0;i<state.reviews.length;i++){var r=state.reviews[i];h+='<div class="review-item"><div><strong>'+esc(r.subject||'مرور')+'</strong><small>'+esc(r.description||'')+' • '+faNum(r.intervalDays)+' روزه</small></div><button data-review="'+esc(r.id)+'">انجام شد</button></div>';}list.innerHTML=h;var bs=qa('[data-review]',list);for(i=0;i<bs.length;i++)bs[i].onclick=function(){var id=this.getAttribute('data-review');api('PATCH','/reviews/'+id,{status:'done'},function(err){if(err)return toast(err.message);toast('مرور ثبت شد');loadReviews();});};}
function renderExamFocus(e){var box=el('examFocus');if(!e){box.className='exam-focus hidden';return;}box.className='exam-focus';el('examFocusTitle').textContent=e.title;var days=Math.ceil((new Date(e.isoDate+'T12:00:00')-new Date(isoToday()+'T12:00:00'))/86400000);el('examFocusDate').textContent=(e.persianDate||shamsiDate(e.isoDate,true))+' • '+faNum(Math.max(0,days))+' روز مانده';el('examReadiness').textContent=faNum(e.readiness||0)+'%';box.onclick=function(){openExam(e);};}
function examReasonText(d){var map={ready:'آماده شروع',resume:'آزمون در حال اجراست',not_open:'هنوز زمان آزمون نرسیده',closed:'زمان آزمون تمام شده',attempt_limit:'تلاش مجاز استفاده شده',retry_pending:'درخواست تلاش مجدد در حال بررسی است',no_questions:'مشاور هنوز سؤال‌ها را آماده نکرده',not_published:'هنوز منتشر نشده',cancelled:'آزمون لغو شده',completed:'آزمون بسته شده'};return map[d&&d.reason]||'اطلاعات آزمون';}
function examActionLabel(d){if(!d)return'مشاهده';if(d.reason==='resume')return'ادامه آزمون';if(d.canStart)return'شروع آزمون';if(d.reason==='attempt_limit')return'درخواست تلاش مجدد';return'جزئیات آزمون';}
function clearExamRefresh(){if(state.examRefreshTimer){clearTimeout(state.examRefreshTimer);state.examRefreshTimer=null;}}
function scheduleExamRefresh(exams){clearExamRefresh();var nowMs=Date.now(),next=0,list=exams||state.exams||[];for(var i=0;i<list.length;i++){var e=list[i],times=[e.openAt,e.closeAt];for(var j=0;j<times.length;j++){if(!times[j])continue;var ms=new Date(times[j]).getTime();if(ms>nowMs+100&&!isNaN(ms)&&(next===0||ms<next))next=ms;}}if(next){var delay=Math.max(250,Math.min(2147480000,next-nowMs+350));state.examRefreshTimer=setTimeout(function(){state.examRefreshTimer=null;if(state.authStatus==='authenticated')loadExams();},delay);}}
function loadExams(){api('GET','/exams',null,function(err,data){if(err)return toast(err.message,'error');state.exams=data||[];scheduleExamRefresh(state.exams);var box=el('examList'),h='';if(!state.exams.length)h='<div class="empty-card">آزمونی ثبت نشده است.</div>';for(var i=0;i<state.exams.length;i++){var e=state.exams[i],d=e.delivery||{},pct=0;h+='<article class="exam-card exam-delivery-card" data-exam="'+esc(e.id)+'"><div class="exam-card-head"><div><div class="eyebrow">'+esc(e.persianDate||shamsiDate(e.isoDate,true))+'</div><h3>'+esc(e.title)+'</h3><p>'+esc(examReasonText(d))+'</p></div><div class="readiness"><strong>…</strong><span>آمادگی</span></div></div><div class="exam-mini-stats"><span><small>تلاش</small><strong>'+faNum(d.attemptsUsed||0)+'/'+faNum(d.allowedAttempts||e.maxAttempts||1)+'</strong></span><span><small>زمان</small><strong>'+faNum(e.durationMinutes||120)+' دقیقه</strong></span><span><small>سؤال</small><strong>'+faNum(d.questionCount||0)+'</strong></span></div><div class="exam-window-student">'+icon(d.canStart||d.reason==='resume'?'target':'lock-exam')+'<span>'+esc(shortDateTime(e.openAt))+' تا '+esc(shortDateTime(e.closeAt))+'</span></div><button class="btn '+(d.canStart||d.reason==='resume'?'primary':'soft')+' full exam-open-button">'+esc(examActionLabel(d))+'</button></article>';}box.innerHTML=h;var cards=qa('[data-exam]',box);for(i=0;i<cards.length;i++)(function(card){var id=card.getAttribute('data-exam');api('GET','/exams/'+id+'/progress',null,function(er,p){if(!er){q('.readiness strong',card).textContent=faNum(p.readiness)+'%';q('.exam-open-button',card).textContent=examActionLabel(p.delivery||{});card.onclick=function(){openExam(p);};}});})(cards[i]);});}
function openExam(e){api('GET','/exams/'+e.id+'/progress',null,function(err,p){if(err)return toast(err.message,'error');var d=p.delivery||{};if(d.reason==='not_open'&&p.openAt){clearExamRefresh();var waitMs=new Date(p.openAt).getTime()-Date.now()+350;if(waitMs>0)state.examRefreshTimer=setTimeout(function(){state.examRefreshTimer=null;if(!el('examModal').classList.contains('hidden'))openExam({id:p.id});else loadExams();},Math.min(2147480000,waitMs));}var h='<div class="exam-modal-hero"><div><span class="eyebrow">'+esc(p.persianDate||shamsiDate(p.isoDate,true))+'</span><h3>'+esc(p.title)+'</h3><p>'+esc(p.instructions||p.note||'بودجه‌بندی و زمان آزمون را قبل از شروع بررسی کن.')+'</p></div><div class="readiness"><strong>'+faNum(p.readiness)+'%</strong><span>آمادگی</span></div></div><div class="exam-delivery-panel"><div class="exam-delivery-status"><strong>'+esc(examReasonText(d))+'</strong><small>'+esc(shortDateTime(p.openAt))+' تا '+esc(shortDateTime(p.closeAt))+'</small></div><div class="exam-mini-stats"><span><small>تلاش مصرف‌شده</small><strong>'+faNum(d.attemptsUsed||0)+'</strong></span><span><small>تلاش مجاز</small><strong>'+faNum(d.allowedAttempts||p.maxAttempts||1)+'</strong></span><span><small>مدت</small><strong>'+faNum(p.durationMinutes||120)+' دقیقه</strong></span></div>';
    if(d.canStart||d.reason==='resume')h+='<button id="examStartBtn" class="btn primary full exam-start">'+(d.reason==='resume'?'ادامه آزمون':'شروع آزمون')+'</button><p class="exam-warning">پس از شروع، زمان آزمون ادامه پیدا می‌کند؛ بستن پنجره زمان را متوقف نمی‌کند.</p>';
    else if(d.reason==='attempt_limit')h+='<label class="block-label">پیام برای مشاور<textarea id="examRetryMessage" rows="2" placeholder="چرا به یک تلاش دیگر نیاز داری؟"></textarea></label><button id="examRetryBtn" class="btn soft full">'+icon('retry')+' درخواست یک تلاش دیگر</button>';
    else if(d.reason==='retry_pending')h+='<div class="exam-pending">'+icon('retry')+' درخواست تلاش مجدد ارسال شده و منتظر تصمیم مشاور است.</div>';
    h+='</div><div class="syllabus-section"><h4>بودجه و وضعیت آمادگی</h4>';
    for(var i=0;i<p.syllabus.length;i++){var x=p.syllabus[i];h+='<div class="syllabus-item"><div class="syllabus-item-head"><div><strong>'+esc(x.subject)+'</strong><p>'+esc(x.description)+'</p></div><select data-syllabus="'+esc(x.id)+'"><option value="unread"'+(x.status==='unread'?' selected':'')+'>نخوانده</option><option value="read"'+(x.status==='read'?' selected':'')+'>خوانده</option><option value="tested"'+(x.status==='tested'?' selected':'')+'>تست زده</option><option value="review"'+(x.status==='review'?' selected':'')+'>نیازمند مرور</option><option value="mastered"'+(x.status==='mastered'?' selected':'')+'>مسلط</option></select></div></div>';}
    h+='</div>';el('examModalBody').innerHTML=h;openModal('examModal');if(el('examStartBtn'))el('examStartBtn').onclick=function(){startExam(p.id,this);};if(el('examRetryBtn'))el('examRetryBtn').onclick=function(){requestExamRetry(p.id,this);};var sels=qa('[data-syllabus]',el('examModalBody'));for(i=0;i<sels.length;i++)sels[i].onchange=function(){var id=this.getAttribute('data-syllabus'),v=this.value;api('PUT','/syllabus/'+id+'/progress',{status:v,accuracy:0,note:''},function(er){if(er)return toast(er.message,'error');toast('وضعیت ذخیره شد');loadReviews();});};});}
function startExam(id,btn){if(!id||state.quizSubmitting)return;setButtonBusy(btn,true);api('POST','/exams/'+encodeURIComponent(id)+'/start',{deviceLabel:deviceLabel()},function(err,data){setButtonBusy(btn,false);if(err){if(err.code==='EXAM_NOT_AVAILABLE'||err.code==='ATTEMPT_LIMIT')loadExams();return toast(err.message,'error');}state.currentExamId=id;state.currentExamCloseAt=data&&data.exam?data.exam.closeAt:null;beginQuizRun(data);});}
function requestExamRetry(id,btn){var text=el('examRetryMessage')?String(el('examRetryMessage').value||'').trim():'';setButtonBusy(btn,true);api('POST','/exams/'+encodeURIComponent(id)+'/retry-request',{message:text},function(err){setButtonBusy(btn,false);if(err)return toast(err.message,'error');toast('درخواست برای مشاور ارسال شد');openExam({id:id});loadExams();});}
function loadProgress(){api('GET','/subjects',null,function(err,subs){if(!err){state.subjects=subs||[];renderSubjects();}});api('GET','/mistakes?limit=80',null,function(err,data){if(!err){state.mistakes=data||[];renderMistakes();}});}
function renderSubjects(){var h='';for(var i=0;i<state.subjects.length;i++){var s=state.subjects[i],p=Number(s.progress||0);h+='<div class="subject-row"><div class="subject-row-head"><strong>'+esc(s.name)+'</strong><small>'+faNum(p)+'% • '+esc(s.mastery||'در حال پیشرفت')+'</small></div><div class="bar"><i style="width:'+p+'%"></i></div></div>';}el('subjectProgress').innerHTML=h||'<div class="empty-card">هنوز داده‌ای نیست.</div>';}
function renderMistakes(){var counts={},h='';for(var i=0;i<state.mistakes.length;i++){var m=state.mistakes[i],r=m.errorReason||'دسته‌بندی نشده';counts[r]=(counts[r]||0)+1;h+='<div class="mistake-card"><strong>'+esc((m.subject?m.subject+' — ':'')+(m.quizTitle||''))+'</strong><p>'+esc(m.question||'')+'</p><select data-mistake="'+esc(m.id)+'"><option value="">دلیل خطا...</option>';for(var j=0;j<mistakeReasons.length;j++)h+='<option'+(m.errorReason===mistakeReasons[j]?' selected':'')+'>'+esc(mistakeReasons[j])+'</option>';h+='</select></div>';}var sum='';for(var k in counts)if(Object.prototype.hasOwnProperty.call(counts,k))sum+='<span>'+esc(k)+': '+faNum(counts[k])+'</span>';el('mistakeSummary').innerHTML=sum||'<span>هنوز خطای ثبت‌شده‌ای نیست.</span>';el('mistakeList').innerHTML=h;var sels=qa('[data-mistake]');for(i=0;i<sels.length;i++)sels[i].onchange=function(){var id=this.getAttribute('data-mistake'),v=this.value;api('PATCH','/mistakes/'+id,{errorReason:v},function(err){if(err)toast(err.message);else toast('دلیل خطا ذخیره شد');});};}
function loadSchedule(date){state.scheduleDate=date;el('scheduleDate').value=date;if(el('schedulePersianDate'))el('schedulePersianDate').textContent=shamsiDate(date,true);api('GET','/plans?date='+date,null,function(err,p){if(err)return toast(err.message);if(p&&p.persianDate&&el('schedulePersianDate'))el('schedulePersianDate').textContent=p.persianDate;renderScheduleMotivation(p);renderTimeline(p&&p.tasks?p.tasks:[],'scheduleDay');});}
function renderScheduleMotivation(plan){var box=el('scheduleMotivation'),text=plan&&plan.motivationText?String(plan.motivationText).replace(/^\s+|\s+$/g,''):'';if(!box)return;if(!text){box.className='daily-motivation compact hidden';return;}el('scheduleMotivationText').textContent=text;box.className='daily-motivation compact';}
function loadNotifications(){api('GET','/notifications',null,function(err,data){if(err)return toast(err.message,'error');var list=data||[],h='',unread=0;for(var i=0;i<list.length;i++){var n=list[i];if(!n.isRead)unread++;h+='<button class="notification-item '+(!n.isRead?'unread':'')+'" data-notification="'+esc(n.id)+'"><span class="notification-dot"></span><span class="notification-copy"><strong>'+esc(n.title)+'</strong><p>'+esc(n.body)+'</p><small>'+esc(shortDateTime(n.createdAt||''))+'</small></span>'+(!n.isRead?'<b>جدید</b>':'')+'</button>';}el('notificationsList').innerHTML=h||'<div class="empty-card">پیام جدیدی نداری.</div>';el('notificationUnreadText').textContent=faNum(unread);el('notificationBadge').textContent=faNum(unread);el('notificationBadge').className=unread?'badge':'badge hidden';openModal('notificationsModal');var bs=qa('[data-notification]',el('notificationsList'));for(i=0;i<bs.length;i++)bs[i].onclick=function(){var id=this.getAttribute('data-notification'),row=this;if(!row.classList.contains('unread'))return;api('PUT','/notifications/'+encodeURIComponent(id)+'/read',{},function(er){if(er)return toast(er.message,'error');row.classList.remove('unread');loadNotifications();loadDashboard();});};});}
function openReport(){var d=state.dashboard||{},m=d.planMetrics||{},r=d.latestReport||{};el('focusInput').value=r.focus||7;el('fatigueInput').value=r.fatigue||5;el('motivationInput').value=r.motivation||7;el('reportProblem').value=r.problem||'';el('reportTomorrow').value=r.tomorrow||'';syncOutputs();openModal('reportModal');}
function submitReport(){queued('POST','/reports',{planDate:isoToday(),focus:Number(el('focusInput').value),fatigue:Number(el('fatigueInput').value),motivation:Number(el('motivationInput').value),problem:el('reportProblem').value,tomorrow:el('reportTomorrow').value},function(err){if(err)return toast(err.message);closeModals();toast('گزارش شبانه ثبت شد ✓');loadDashboard();});}
function syncOutputs(){el('focusOut').textContent=faNum(el('focusInput').value);el('fatigueOut').textContent=faNum(el('fatigueInput').value);el('motivationOut').textContent=faNum(el('motivationInput').value);}
function openRecovery(){el('recoveryNote').value='';openModal('recoveryModal');}
function submitRecovery(){queued('POST','/recovery-requests',{planDate:isoToday(),reason:el('recoveryReason').value,note:el('recoveryNote').value},function(err){if(err)return toast(err.message);record('recovery.requested','plan',isoToday(),{});closeModals();toast('برای مشاور ارسال شد.');});}
function quizDraftKey(){return state.quizRunId?'moshaver_quiz_draft:'+state.quizRunId:'';}
function saveQuizDraft(){var k=quizDraftKey();if(!k)return;try{localStorage.setItem(k,JSON.stringify({answers:state.quizAnswers,index:state.quizIndex}));}catch(e){}}
function loadQuizDraft(){var k=quizDraftKey();if(!k)return;try{var d=JSON.parse(localStorage.getItem(k)||'null');if(d){state.quizAnswers=d.answers||{};state.quizIndex=Math.max(0,Number(d.index||0));}}catch(e){}}
function clearQuizDraft(){var k=quizDraftKey();if(!k)return;try{localStorage.removeItem(k);}catch(e){}}
function beginQuizRun(data){state.quiz=data.quiz;state.quizRunId=data.runId;state.quizIndex=0;state.quizAnswers={};state.quizStartedAt=data.startedAt;state.busyQuiz=true;state.quizSubmitting=false;loadQuizDraft();sendPresence();closeModals();openModal('quizModal');startQuizTimer();renderQuiz();}
function startQuiz(id){if(!id)return;api('POST','/quizzes/'+id+'/start',{deviceLabel:deviceLabel()},function(err,data){if(err)return toast(err.message,'error');state.currentExamId=data.quiz&&data.quiz.examId?data.quiz.examId:null;state.currentExamCloseAt=null;beginQuizRun(data);});}
function startQuizTimer(){stopQuizTimer();updateQuizTimer();state.quizTimer=setInterval(updateQuizTimer,1000);}
function stopQuizTimer(){if(state.quizTimer)clearInterval(state.quizTimer);state.quizTimer=null;}
function remainingQuizSeconds(){if(!state.quiz||!state.quizStartedAt)return 0;var total=Math.max(1,Number(state.quiz.durationMinutes||20))*60,elapsed=Math.max(0,Math.floor((Date.now()-new Date(state.quizStartedAt).getTime())/1000)),left=Math.max(0,total-elapsed);if(state.currentExamCloseAt){var closeLeft=Math.max(0,Math.floor((new Date(state.currentExamCloseAt).getTime()-Date.now())/1000));left=Math.min(left,closeLeft);}return left;}
function updateQuizTimer(){var sec=remainingQuizSeconds(),node=el('quizCountdown');if(node){var m=Math.floor(sec/60),s=sec%60;node.textContent=faNum(('0'+m).slice(-2)+':'+('0'+s).slice(-2));node.className='quiz-countdown '+(sec<=300?'danger':'');}if(sec<=0&&state.busyQuiz&&!state.quizSubmitting)finishQuiz(true);}
function renderQuiz(){var qz=state.quiz;if(!qz)return;var qs=qz.questions||[],idx=Math.min(state.quizIndex,Math.max(0,qs.length-1)),qst=qs[idx];state.quizIndex=idx;if(!qst){finishQuiz();return;}var letters=['a','b','c','d'],h='<div class="quiz-topline"><div class="eyebrow">'+esc(qz.title)+' • سؤال '+faNum(idx+1)+' از '+faNum(qs.length)+'</div><strong id="quizCountdown" class="quiz-countdown">--:--</strong></div><div class="quiz-progress"><i style="width:'+Math.round((idx+1)*100/qs.length)+'%"></i></div><div class="quiz-question">'+esc(qst.question)+'</div>';for(var i=0;i<4;i++)h+='<button class="quiz-option '+(state.quizAnswers[qst.id]===letters[i]?'selected':'')+'" data-option="'+letters[i]+'"><span>'+faNum(i+1)+'</span>'+esc(qst.options[i])+'</button>';h+='<div class="quiz-answer-state">'+faNum(Object.keys(state.quizAnswers).length)+' از '+faNum(qs.length)+' پاسخ داده شده</div><div class="quiz-footer"><button id="quizPrev" class="btn soft"'+(idx===0?' disabled':'')+'>قبلی</button><button id="quizNext" class="btn primary">'+(idx===qs.length-1?'ثبت نهایی':'بعدی')+'</button></div>';el('quizBody').innerHTML=h;updateQuizTimer();var opts=qa('[data-option]',el('quizBody'));for(i=0;i<opts.length;i++)opts[i].onclick=function(){state.quizAnswers[qst.id]=this.getAttribute('data-option');saveQuizDraft();renderQuiz();};el('quizPrev').onclick=function(){if(state.quizIndex>0){state.quizIndex--;saveQuizDraft();renderQuiz();}};el('quizNext').onclick=function(){if(state.quizIndex<qs.length-1){state.quizIndex++;saveQuizDraft();renderQuiz();}else{var blank=qs.length-Object.keys(state.quizAnswers).length;if(blank>0&&!confirm(faNum(blank)+' سؤال بدون پاسخ است. آزمون ثبت شود؟'))return;finishQuiz();}};}
function finishQuiz(auto){if(!state.quiz||!state.quizRunId||state.quizSubmitting)return;state.quizSubmitting=true;var answers=[],qs=state.quiz.questions||[];for(var i=0;i<qs.length;i++)answers.push({questionId:qs[i].id,selectedOption:state.quizAnswers[qs[i].id]||null,errorReason:''});api('POST','/quizzes/'+state.quiz.id+'/attempts',{runId:state.quizRunId,answers:answers},function(err,result){state.quizSubmitting=false;if(err)return toast(err.message,'error');stopQuizTimer();clearQuizDraft();state.busyQuiz=false;state.quizRunId=null;sendPresence();el('quizBody').innerHTML='<div class="quiz-result"><div class="readiness"><strong>'+faNum(result.percent)+'%</strong><span>نتیجه</span></div><h3>'+(auto?'زمان تمام شد؛ آزمون ثبت شد':'آزمون ثبت شد')+'</h3><p class="muted">'+faNum(result.correct)+' درست • '+faNum(result.wrong)+' غلط • '+faNum(result.blank)+' نزده • '+faNum(Math.round((result.durationSeconds||0)/60))+' دقیقه</p><button id="quizResultClose" class="btn primary full">بستن آزمون و برگشت به برنامه</button></div>';el('quizResultClose').onclick=function(){closeModals();state.quiz=null;state.currentExamId=null;state.currentExamCloseAt=null;loadDashboard();loadProgress();loadExams();};});}
function cancelQuiz(){if(!state.busyQuiz){closeModals();return;}var isExam=!!(state.quiz&&state.quiz.examId);if(isExam){if(confirm('از صفحه آزمون خارج شوی؟ زمان آزمون ادامه دارد و دوباره می‌توانی همین تلاش را ادامه بدهی.')){saveQuizDraft();stopQuizTimer();state.busyQuiz=false;state.quiz=null;state.currentExamId=null;state.currentExamCloseAt=null;sendPresence();closeModals();loadExams();}return;}if(confirm('آزمونک را بدون ثبت ببندی؟')){record('quiz.cancelled','quiz',state.quiz?state.quiz.id:'',{});clearQuizDraft();stopQuizTimer();state.busyQuiz=false;state.quiz=null;state.quizRunId=null;state.sessionActionBusy=false;state.currentExamId=null;state.currentExamCloseAt=null;clearExamRefresh();sendPresence();closeModals();}}
function chatActive(){return el('view-chat')&&el('view-chat').classList.contains('active');}
function setChatBadge(n){state.chatUnread=Math.max(0,Number(n||0));var b=el('chatNavBadge');if(!b)return;b.textContent=faNum(state.chatUnread);b.className=state.chatUnread?'badge nav-badge':'badge nav-badge hidden';}
function chatTime(v){try{var d=new Date(v);return('0'+d.getHours()).slice(-2)+':'+('0'+d.getMinutes()).slice(-2);}catch(e){return'';}}
function scrollChatBottom(){var box=el('chatMessages');if(!box)return;box.scrollTop=box.scrollHeight;setTimeout(function(){box.scrollTop=box.scrollHeight;},30);}
function renderChat(){var box=el('chatMessages');if(!box)return;var list=state.chatMessages||[],h='',lastDay='';if(!list.length)h='<div class="chat-empty-friendly">'+icon('advisor')+'<strong>هنوز پیامی نیست</strong><p>مثل یک گفت‌وگوی معمولی، پیام کوتاهت را برای مشاور بفرست.</p></div>';for(var i=0;i<list.length;i++){var m=list[i],mine=state.me&&m.senderUserId===state.me.id,day=String(m.createdAt||'').slice(0,10);if(day!==lastDay){lastDay=day;h+='<div class="chat-day-separator"><span>'+esc(chatDayLabel(day))+'</span></div>';}h+='<div class="message-row '+(mine?'mine':'theirs')+'">'+(!mine?'<span class="message-avatar">م</span>':'')+'<div class="message-bubble"><p>'+esc(m.deletedAt?'پیام حذف شده':m.text)+'</p><div class="message-meta"><span>'+faNum(chatTime(m.createdAt))+'</span>'+(mine?'<span class="message-seen">'+(m.seen?'✓✓':'✓')+'</span>':'')+'</div></div></div>';}box.innerHTML=h;scrollChatBottom();}
function markChatRead(){if(!state.chatConversation)return;api('POST','/chat/conversations/'+encodeURIComponent(state.chatConversation.id)+'/read',{},function(err){if(!err)setChatBadge(0);});}
function loadChat(mark){api('GET','/chat/conversation',null,function(err,c){if(err)return toast(err.message);state.chatConversation=c;el('advisorName').textContent=c.advisor&&c.advisor.name?c.advisor.name:'مشاور';setChatBadge(c.unread||state.chatUnread);api('GET','/chat/conversations/'+encodeURIComponent(c.id)+'/messages?limit=80',null,function(er,d){if(er)return toast(er.message);state.chatMessages=d.messages||[];renderChat();if(mark||chatActive())markChatRead();});});}
function sendChat(){var input=el('chatInput'),text=String(input.value||'').trim();if(!text||!state.chatConversation||state.chatSending)return;if(text.length>3000)return toast('پیام خیلی طولانی است.','error');state.chatSending=true;setButtonBusy(el('studentChatSend'),true);api('POST','/chat/conversations/'+encodeURIComponent(state.chatConversation.id)+'/messages',{text:text},function(err,item){state.chatSending=false;setButtonBusy(el('studentChatSend'),false);if(err)return toast(err.message,'error');input.value='';autoGrow(input);state.chatMessages.push(item);renderChat();});}
function disconnectEvents(){if(state.eventSource){try{state.eventSource.close();}catch(e){}state.eventSource=null;}if(state.chatPoll){clearInterval(state.chatPoll);state.chatPoll=null;}}
function realtimeEvent(type,data){if(type==='chat.message.created'){if(data&&state.chatConversation&&data.conversationId===state.chatConversation.id){loadChat(chatActive());}else setChatBadge(state.chatUnread+1);if(!chatActive())toast('پیام جدید از مشاور');return;}if(type==='chat.messages.read'){if(chatActive())loadChat(false);return;}if(type==='plan.published'||type==='plan.updated'){toast('برنامه توسط مشاور به‌روزرسانی شد');loadDashboard();if(el('view-schedule').classList.contains('active'))loadSchedule(state.scheduleDate||isoToday());return;}if(type==='exam.updated'||type==='exam.retry_reviewed'){toast(type==='exam.retry_reviewed'?'وضعیت درخواست آزمون به‌روزرسانی شد':'آزمون توسط مشاور به‌روزرسانی شد');if(el('view-exams').classList.contains('active'))loadExams();loadDashboard();return;}if(type==='advisor.comment.created'){toast('پیام جدید مشاور برای یکی از فعالیت‌ها');return;}if(type==='notification.created'){var b=el('notificationBadge'),n=state.dashboard?Number(state.dashboard.unreadNotifications||0):0;b.textContent=faNum(n+1);b.className='badge';toast(data&&data.title?data.title:'اعلان جدید');return;}if(type==='review.created')loadReviews();}
function connectEvents(){disconnectEvents();state.eventSource=API.openEvents(realtimeEvent,function(st){var p=el('advisorPresence');if(!p)return;if(st==='open'){p.textContent='● ارتباط زنده';p.className='chat-presence online';}else{p.textContent='○ در حال اتصال';p.className='chat-presence reconnecting';}});if(!state.eventSource)state.chatPoll=setInterval(function(){if(chatActive())loadChat(false);},20000);}

function openPassword(){openModal('passwordModal');}
function changePassword(){var a=el('studentNewPassword').value,b=el('studentNewPassword2').value;if(a!==b)return toast('تکرار رمز با رمز جدید یکسان نیست.');if(a.length<12)return toast('رمز جدید باید حداقل ۱۲ نویسه باشد.');api('POST','/auth/change-password',{currentPassword:el('studentCurrentPassword').value,newPassword:a},function(err){if(err)return toast(err.message);closeModals();el('studentCurrentPassword').value='';el('studentNewPassword').value='';el('studentNewPassword2').value='';toast('رمز تغییر کرد و نشست‌های دیگر بسته شدند.');});}
function toggleTheme(){var dark=document.body.classList.contains('dark');if(dark){document.body.classList.remove('dark');localStorage.setItem('kp_theme','light');el('themeLabel').textContent='روشن';}else{document.body.classList.add('dark');localStorage.setItem('kp_theme','dark');el('themeLabel').textContent='تیره';}}
function applyTheme(){if(localStorage.getItem('kp_theme')==='dark'){document.body.classList.add('dark');el('themeLabel').textContent='تیره';}}
function logout(){
  if(state.authStatus==='logging-out'||state.authStatus==='anonymous')return;
  state.authStatus='logging-out';
  state.authEpoch++;state.bootEpoch++;
  if(state.loginRequest){try{state.loginRequest.abort();}catch(e){}state.loginRequest=null;}
  if(state.startupAuthRequest){try{state.startupAuthRequest.abort();}catch(e){}state.startupAuthRequest=null;}
  API.abortAll();stopPresence();disconnectEvents();stopSessionClock();
  setPendingLogout(true);
  API.request('POST','/auth/logout',{},function(err){
    if(err&&err.status===0){finishLocalLogout('از برنامه خارج شدی. خروج سرور به محض برگشت اینترنت تکمیل می‌شود.',true,false);return;}
    finishLocalLogout('با موفقیت خارج شدید.',false,false);
  },{suppressAuthFailure:true,noCsrfRetry:true});
}
function bindActions(){el('loginForm').onsubmit=function(e){
  e.preventDefault();
  if(state.authStatus==='logging-in')return;
  cancelStartupAuth();
  if(state.loginRequest){try{state.loginRequest.abort();}catch(ex){}state.loginRequest=null;}
  el('loginError').className='form-error hidden';
  var btn=q('#loginForm button[type="submit"]'),btnLabel=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.textContent='در حال ورود…';}
  state.authStatus='logging-in';
  var loginEpoch=++state.authEpoch;
  state.loginRequest=API.request('POST','/auth/login',{username:el('loginUsername').value,password:el('loginPassword').value},function(err,data){
    state.loginRequest=null;if(btn){btn.disabled=false;btn.textContent=btnLabel||'ورود به برنامه';}
    if(loginEpoch!==state.authEpoch)return;
    if(err){state.authStatus='anonymous';el('loginError').textContent=err.message;el('loginError').className='form-error';return;}
    if(!data||!data.user||data.user.role!=='student'){if(data&&data.csrfToken)API.setCsrf(data.csrfToken);clearWrongRoleSession('این حساب دانش‌آموز نیست.');return;}
    setPendingLogout(false);API.setCsrf(data.csrfToken||'');state.me=data.user;state.authStatus='authenticated';el('loginPassword').value='';
    broadcastAuth('login');bootAuthenticated();
  },{suppressAuthFailure:true});
};el('startNowBtn').onclick=function(){if(state.currentTask&&state.currentTask.type==='exam'&&state.currentTask.examId){openExam({id:state.currentTask.examId});return;}if(state.activeSession)finishStudy();else if(state.currentTask)startStudy(state.currentTask);};el('openNowBtn').onclick=function(){if(state.currentTask&&state.currentTask.type==='exam'&&state.currentTask.examId)openExam({id:state.currentTask.examId});else openTask(state.currentTask);};el('recoveryQuickBtn').onclick=openRecovery;el('recoveryBtn').onclick=openRecovery;el('submitRecoveryBtn').onclick=submitRecovery;el('submitIssueBtn').onclick=submitIssue;el('reportBtn').onclick=openReport;el('submitReportBtn').onclick=submitReport;el('notificationBtn').onclick=loadNotifications;el('notificationsMenuBtn').onclick=loadNotifications;el('markAllNotifications').onclick=function(){api('PUT','/notifications/read-all',{},function(err){if(err)return toast(err.message,'error');toast('همه اعلان‌ها خوانده شد');loadNotifications();loadDashboard();});};el('passwordBtn').onclick=openPassword;el('studentSavePassword').onclick=changePassword;el('themeBtn').onclick=toggleTheme;el('progressBtn').onclick=function(){switchView('progress');};el('logoutBtn').onclick=logout;el('scheduleTodayBtn').onclick=function(){loadSchedule(isoToday());};el('schedulePrev').onclick=function(){loadSchedule(shiftDate(state.scheduleDate||isoToday(),-1));};el('scheduleNext').onclick=function(){loadSchedule(shiftDate(state.scheduleDate||isoToday(),1));};el('scheduleDate').onchange=function(){if(this.value)loadSchedule(this.value);};if(el('schedulePickBtn'))el('schedulePickBtn').onclick=function(){var input=el('scheduleDate');try{if(input.showPicker)input.showPicker();else input.click();}catch(e){input.click();}};el('focusInput').oninput=syncOutputs;el('fatigueInput').oninput=syncOutputs;el('motivationInput').oninput=syncOutputs;el('quizCloseBtn').onclick=cancelQuiz;el('focusBackBtn').onclick=hideFocus;el('focusFinishBtn').onclick=function(){finishStudy();};el('chatForm').onsubmit=function(e){e.preventDefault();sendChat();};var cq=qa('[data-student-chat-quick]');for(var i=0;i<cq.length;i++)cq[i].onclick=function(){el('chatInput').value=this.getAttribute('data-student-chat-quick');autoGrow(el('chatInput'));el('chatInput').focus();};el('chatInput').oninput=function(){autoGrow(this);};}
function bootAuthenticated(){
  if(state.authStatus!=='authenticated'||!state.me)return;
  state.bootEpoch++;
  stopPresence();disconnectEvents();
  showApp();state.scheduleDate=isoToday();
  loadDashboard();connectEvents();loadChat(false);flushQueue();
}
function syncVisible(){
  if(state.authStatus!=='authenticated'||!state.me||document.hidden)return;
  if(Date.now()-state.lastSyncAt<15000)return;
  API.refreshCsrf(function(err){if(err)return;loadDashboard();if(chatActive())loadChat(false);});
}
function syncAuthSignal(ev){
  if(!ev||ev.key!==AUTH_SIGNAL_KEY||!ev.newValue)return;
  var data=null;try{data=JSON.parse(ev.newValue);}catch(e){}
  if(!data)return;
  if(data.kind==='logout'){
    if(state.authStatus!=='anonymous')finishLocalLogout('نشست در تب دیگری خارج شد.',false,true);
    return;
  }
  if(data.kind==='login'&&state.authStatus!=='logging-in'&&state.authStatus!=='logging-out'){
    restoreStudentAuth();
  }
}
function restoreStudentAuth(){if(state.authRetryTimer){clearTimeout(state.authRetryTimer);state.authRetryTimer=null;}var btn=q('#loginForm button[type="submit"]');if(btn){btn.disabled=true;btn.textContent='در حال بازیابی نشست…';}var er=el('loginError');if(er){er.textContent='در حال بررسی نشست امن…';er.className='form-error auth-checking';}loadMe(function(err){if(err){if(err.handled)return;if(err.status===401){if(btn){btn.disabled=false;btn.textContent='ورود به برنامه';}showLogin();return;}state.authStatus='checking';if(er){er.textContent='ارتباط موقتاً قطع است؛ نشست شما حفظ شده و دوباره تلاش می‌کنیم…';er.className='form-error auth-checking';}state.authRetryTimer=setTimeout(restoreStudentAuth,1800);return;}if(btn){btn.disabled=false;btn.textContent='ورود به برنامه';}bootAuthenticated();});}
function init(){
  bindClosers();bindNav();bindActions();applyTheme();
  API.setAuthFailureHandler(handleAuthFailure);
  el('appVersion').textContent=(global.APP_CONFIG&&global.APP_CONFIG.APP_VERSION)||'1.4.2';
  setInterval(function(){if(!el('appScreen').classList.contains('hidden'))renderCurrent();},30000);
  window.addEventListener('online',function(){el('offlineBar').className='offline-bar hidden';if(hasPendingLogout()){flushPendingLogout(function(err){if(!err&&state.authStatus==='anonymous')showLogin('خروج سرور هم تکمیل شد.');});return;}flushQueue();syncVisible();});
  window.addEventListener('offline',function(){el('offlineBar').className='offline-bar';setSync('آفلاین');});
  document.addEventListener('visibilitychange',function(){if(!document.hidden)syncVisible();});
  window.addEventListener('pageshow',syncVisible);
  window.addEventListener('storage',syncAuthSignal);
  if(navigator.onLine===false)el('offlineBar').className='offline-bar';
  if(hasPendingLogout()){
    state.authStatus='logging-out';
    flushPendingLogout(function(err){state.authStatus='anonymous';if(err)showLogin('خروج قبلی هنوز منتظر اتصال اینترنت است.');else showLogin();});
    return;
  }
  loadMe(function(err){if(err){if(!err.handled)showLogin();return;}bootAuthenticated();});
}
global.KP_RUNTIME={isBusy:function(){return !!state.activeSession||state.busyQuiz;},stopForUpdate:function(){stopPresence();stopSessionClock();disconnectEvents();}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
