import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpen, CheckSquare2, ExternalLink, Pencil, Plus, RefreshCw, Search, Trash2, UsersRound, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Button, Card, Input, Textarea } from "../../shared/ui/ui";
import { createResource, deleteResource, LearningResource, listResources, listResourceStudents, ResourceInput, updateResource } from "./api/resources.api";

const empty: ResourceInput = { title: "", description: "", type: "LINK", url: "", status: "PUBLISHED", studentIds: [] };

export function ResourcesPage() {
  const qc = useQueryClient();
  const resources = useQuery({ queryKey: ["learning-resources"], queryFn: listResources });
  const students = useQuery({ queryKey: ["students", "resource-picker"], queryFn: listResourceStudents });
  const [form, setForm] = useState<ResourceInput>(empty);
  const [editing, setEditing] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [confirmDelete, setConfirmDelete] = useState<string | null>(null);
  const save = useMutation({ mutationFn: () => editing ? updateResource(editing, form) : createResource(form), onSuccess: () => { setForm(empty); setEditing(null); void qc.invalidateQueries({ queryKey: ["learning-resources"] }); } });
  const remove = useMutation({ mutationFn: deleteResource, onSuccess: () => { setConfirmDelete(null); void qc.invalidateQueries({ queryKey: ["learning-resources"] }); } });
  const filtered = useMemo(() => (students.data || []).filter((item) => `${item.name} ${item.grade} ${item.major}`.toLowerCase().includes(search.trim().toLowerCase())), [students.data, search]);
  const toggle = (id: string) => setForm((value) => ({ ...value, studentIds: value.studentIds.includes(id) ? value.studentIds.filter((item) => item !== id) : [...value.studentIds, id] }));
  const edit = (item: LearningResource) => { setEditing(item.id); setForm({ title: item.title, description: item.description, type: item.type, url: item.url, status: item.status, studentIds: item.assignments.map((assignment) => assignment.student.id) }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const submit = (event: FormEvent) => { event.preventDefault(); save.mutate(); };
  const loading = resources.isLoading || students.isLoading;
  const failed = resources.isError || students.isError;

  return <section className="space-y-5">
    <div><p className="text-xs font-bold text-brand">کتابخانه قابل تخصیص</p><h1 className="mt-1 text-2xl font-black">منابع آموزشی دانش‌آموزان</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-600 dark:text-slate-300">پیوند یا ویدئوی امن را یک‌بار بسازید، چند دانش‌آموز را هم‌زمان انتخاب کنید و وضعیت انتشار را کنترل کنید.</p></div>
    <Card className="p-4 sm:p-5"><form className="grid gap-4" onSubmit={submit}><div className="flex items-center justify-between gap-3"><h2 className="font-black">{editing ? "ویرایش منبع" : "منبع تازه"}</h2>{editing ? <Button type="button" variant="ghost" onClick={() => { setEditing(null); setForm(empty); }}><X size={16}/>انصراف</Button> : null}</div><div className="grid gap-3 md:grid-cols-2"><Field label="عنوان"><Input required minLength={2} maxLength={180} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })}/></Field><Field label="پیوند امن (HTTPS)"><Input required type="url" inputMode="url" dir="ltr" placeholder="https://…" value={form.url} onChange={(e) => setForm({ ...form, url: e.target.value })}/></Field><Field label="نوع"><Select value={form.type} onChange={(value) => setForm({ ...form, type: value as ResourceInput["type"] })}><option value="LINK">پیوند</option><option value="VIDEO">ویدئو</option></Select></Field><Field label="وضعیت"><Select value={form.status} onChange={(value) => setForm({ ...form, status: value as ResourceInput["status"] })}><option value="PUBLISHED">منتشرشده</option><option value="DRAFT">پیش‌نویس</option><option value="ARCHIVED">بایگانی</option></Select></Field></div><Field label="توضیح"><Textarea maxLength={4000} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></Field>
      <fieldset className="rounded-2xl border p-3"><legend className="px-2 text-sm font-bold">دانش‌آموزان دریافت‌کننده ({form.studentIds.length})</legend><div className="relative mt-1"><Search className="absolute right-3 top-3 text-slate-400" size={17}/><Input className="pr-10" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="جست‌وجوی نام، پایه یا رشته"/></div><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="soft" onClick={() => setForm({ ...form, studentIds: [...new Set([...form.studentIds, ...filtered.map((item) => item.id)])] })}><CheckSquare2 size={16}/>انتخاب نتایج</Button><Button type="button" variant="ghost" onClick={() => setForm({ ...form, studentIds: [] })}>لغو همه</Button></div><div className="mt-3 grid max-h-64 gap-2 overflow-auto sm:grid-cols-2 lg:grid-cols-3">{filtered.map((student) => <label key={student.id} className="flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border px-3 py-2 hover:border-brand/40"><input type="checkbox" className="size-4 accent-brand" checked={form.studentIds.includes(student.id)} onChange={() => toggle(student.id)}/><span><span className="block text-sm font-bold">{student.name}</span><span className="text-xs text-slate-500">{student.grade || "پایه نامشخص"} · {student.major || "رشته نامشخص"}</span></span></label>)}</div>{!filtered.length ? <p className="py-5 text-center text-sm text-slate-500">دانش‌آموزی مطابق جست‌وجو نیست.</p> : null}</fieldset>
      <div className="flex flex-wrap items-center gap-3"><Button type="submit" loading={save.isPending} disabled={!form.studentIds.length}><Plus size={16}/>{editing ? "ذخیره تغییرات" : "ساخت و تخصیص"}</Button>{save.isError ? <p role="alert" className="text-sm text-rose-700">{save.error instanceof Error ? save.error.message : "ذخیره انجام نشد."}</p> : null}</div></form></Card>
    {loading ? <Card className="p-8 text-center" role="status">در حال آماده‌سازی منابع…</Card> : null}{failed ? <Card className="p-6 text-center text-rose-700" role="alert"><p>دریافت اطلاعات انجام نشد.</p><Button className="mt-3" variant="soft" onClick={() => void Promise.all([resources.refetch(), students.refetch()])}><RefreshCw size={16}/>تلاش دوباره</Button></Card> : null}
    {!loading && !failed && !resources.data?.length ? <Card className="p-8 text-center"><BookOpen className="mx-auto text-brand"/><h2 className="mt-3 font-bold">هنوز منبعی ساخته نشده است</h2></Card> : null}
    <div className="grid gap-3 lg:grid-cols-2">{resources.data?.map((item) => <Card key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-brand/10 px-2 py-1 text-xs font-bold text-brand">{item.type === "VIDEO" ? "ویدئو" : "پیوند"} · {item.status === "PUBLISHED" ? "منتشرشده" : item.status === "DRAFT" ? "پیش‌نویس" : "بایگانی"}</span><h2 className="mt-3 font-black">{item.title}</h2></div><a className="rounded-xl p-2 text-brand hover:bg-brand/10" href={item.url} target="_blank" rel="noreferrer" aria-label={`باز کردن ${item.title}`}><ExternalLink size={18}/></a></div><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.description || "بدون توضیح"}</p><p className="mt-3 flex items-center gap-2 text-xs text-slate-500"><UsersRound size={15}/>{item.assignments.length} دانش‌آموز</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="soft" onClick={() => edit(item)}><Pencil size={16}/>ویرایش</Button>{confirmDelete === item.id ? <><Button variant="danger" loading={remove.isPending} onClick={() => remove.mutate(item.id)}>حذف قطعی</Button><Button variant="ghost" onClick={() => setConfirmDelete(null)}>انصراف</Button></> : <Button variant="ghost" onClick={() => setConfirmDelete(item.id)}><Trash2 size={16}/>حذف</Button>}</div></Card>)}</div>
  </section>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-bold"><span>{label}</span>{children}</label>; }
function Select({ value, onChange, children }: { value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <select className="h-11 w-full rounded-xl border bg-white px-3 text-sm dark:bg-slate-900" value={value} onChange={(event) => onChange(event.target.value)}>{children}</select>; }
