import { Injectable } from "@nestjs/common";import { InjectRepository } from "@nestjs/typeorm";import { DataSource,Repository } from "typeorm";import { ApiException } from "../../common/exceptions/api.exception";import { Recommendation,Student,User } from "../../database/entities";import { RecommendationStatus } from "../../database/entities/recommendation.entity";import { AuthorizationService,UserContext } from "../authorization/authorization.service";
@Injectable()export class AnalyticsService{constructor(private db:DataSource,@InjectRepository(Student)private students:Repository<Student>,@InjectRepository(Recommendation)private recommendations:Repository<Recommendation>,@InjectRepository(User)private users:Repository<User>,private authorization:AuthorizationService){}
 async analytics(context:UserContext,studentId:string,projection="staff"){if(!await this.authorization.canAccessStudent(context,studentId,"analytics.read")&&projection!=="self")throw new ApiException(403,"STUDENT_FORBIDDEN","به این دانش‌آموز دسترسی ندارید.");return this.metrics(studentId,projection);}
 async self(userId:string){const student=await this.students.findOneByOrFail({user:{id:userId}} as never);return this.metrics(student.id,"self");}
 async metrics(studentId:string,projection:string){const one=async(sql:string)=>(await this.db.query(sql,[studentId]))[0];const [tasks,study,exams,quiz,reviews,subjects]=await Promise.all([one(`SELECT COUNT(*)total,SUM(CASE WHEN completedAt IS NOT NULL OR status='DONE' THEN 1 ELSE 0 END)completed FROM tasks t JOIN plans p ON p.id=t.planId WHERE p.studentId=?`),one(`SELECT SUM(elapsedSeconds)seconds,COUNT(*)sessions FROM study_sessions WHERE studentId=? AND status='FINISHED'`),one(`SELECT AVG(score)average,COUNT(*)attempts FROM exam_attempts WHERE studentId=? AND finishedAt IS NOT NULL`),one(`SELECT AVG(percent)average,COUNT(*)attempts FROM quiz_attempts WHERE studentId=? AND submittedAt IS NOT NULL`),one(`SELECT COUNT(*)reviews,AVG(newMastery)mastery FROM learning_reviews r JOIN learning_items i ON i.id=r.itemId WHERE i.studentId=?`),this.db.query(`SELECT i.subject,COUNT(*)items,AVG(i.mastery)mastery FROM learning_items i WHERE i.studentId=? GROUP BY i.subject`,[studentId])]);const completion=tasks.total?Math.round(tasks.completed/tasks.total*100):null;const result={studentId,planCompletion:completion,taskCompletion:completion,studyDurationMinutes:study.seconds==null?null:Math.round(study.seconds/60),studySessions:study.sessions||0,examPerformance:exams.average==null?null:Math.round(exams.average*10)/10,examAttempts:exams.attempts||0,questionAccuracy:quiz.average==null?null:Math.round(quiz.average*10)/10,quizAttempts:quiz.attempts||0,reviewConsistency:reviews.reviews||0,averageMastery:reviews.mastery==null?null:Math.round(reviews.mastery*10)/10,subjectPerformance:subjects};if(projection==="guardian")return{studentId,planCompletion:result.planCompletion,studyDurationMinutes:result.studyDurationMinutes,examPerformance:result.examPerformance,encouragement:"روند را با حمایت و گفت‌وگو دنبال کنید."};return result;}
 async listRecommendations(context:UserContext,studentId:string,includeEvidence=true){if(!await this.authorization.canAccessStudent(context,studentId,"recommendations.read"))throw new ApiException(403,"STUDENT_FORBIDDEN","دسترسی ندارید.");const rows=await this.recommendations.find({where:{student:{id:studentId}},order:{createdAt:"DESC"}});return includeEvidence?rows:rows.map(({evidence:_e,reason:_r,...x})=>x);}
 async selfRecommendations(userId:string){const student=await this.students.findOneByOrFail({user:{id:userId}} as never);const rows=await this.recommendations.find({where:{student:{id:student.id},status:RecommendationStatus.PROPOSED},order:{createdAt:"DESC"}});return rows.map(r=>({id:r.id,type:r.type,title:r.title,status:r.status,createdAt:r.createdAt}));}
 async createRecommendation(context:UserContext,userId:string,studentId:string,input:{type:string;title:string;reason:string;evidence:Record<string,unknown>}){if(!await this.authorization.canAccessStudent(context,studentId,"recommendations.manage"))throw new ApiException(403,"STUDENT_FORBIDDEN","دسترسی ندارید.");const [student,user]=await Promise.all([this.students.findOneByOrFail({id:studentId}),this.users.findOneByOrFail({id:userId})]);return this.recommendations.save(this.recommendations.create({student,createdByUser:user,createdByType:"STAFF",type:input.type,title:input.title,reason:input.reason,evidence:input.evidence,status:RecommendationStatus.PROPOSED}));}
 async act(userId:string,id:string,status:RecommendationStatus){const student=await this.students.findOneByOrFail({user:{id:userId}} as never);const row=await this.recommendations.findOne({where:{id,student:{id:student.id}}});if(!row)throw new ApiException(404,"RECOMMENDATION_NOT_FOUND","پیشنهاد پیدا نشد.");if(![RecommendationStatus.ACCEPTED,RecommendationStatus.REJECTED,RecommendationStatus.DISMISSED].includes(status))throw new ApiException(400,"STATUS_INVALID","وضعیت معتبر نیست.");row.status=status;row.actedAt=new Date();return this.recommendations.save(row);}
 studentHealth(studentId:string){return this.metrics(studentId,"staff");}}
