"use strict";

function registerGroupChatRoutes(router,deps){
  var db=deps.db,security=deps.security,now=deps.now,str=deps.str,query=deps.query,ok=deps.ok,fail=deps.fail,audit=deps.audit,bucketAllow=deps.bucketAllow,groups=deps.groups,env=deps.env;
  function denied(res){return fail(res,403,'FORBIDDEN','اجازه انجام این کار را ندارید.');}
  function missing(res){return fail(res,404,'NOT_FOUND','گفت‌وگو یا عضو پیدا نشد.');}
  function parse(v,fallback){try{return JSON.parse(v||'');}catch(e){return fallback||{};}}
  function mapMessage(row,user){var reactions=db.prepare("SELECT mr.emoji,COUNT(*) count,MAX(CASE WHEN mr.user_id=? THEN 1 ELSE 0 END) reacted FROM message_reactions mr WHERE mr.message_id=? GROUP BY mr.emoji ORDER BY MIN(mr.created_at)").all(user.id,row.id);var mentions=db.prepare("SELECT user_id FROM message_mentions WHERE message_id=?").all(row.id).map(function(x){return x.user_id;});return {id:row.id,conversationId:row.conversation_id,senderUserId:row.sender_user_id,senderRole:row.sender_role,senderName:row.sender_name||'',type:row.message_type||'text',text:row.deleted_at?'':row.message_text,payload:row.deleted_at?{}:parse(row.payload_json,{}),replyToId:row.reply_to_id||null,createdAt:row.created_at,editedAt:row.edited_at||null,deletedAt:row.deleted_at||null,pinnedAt:row.pinned_at||null,reactions:reactions.map(function(x){return {emoji:x.emoji,count:Number(x.count),reacted:!!x.reacted};}),mentionUserIds:mentions};}
  function accessMessage(messageId,user){var row=db.prepare("SELECT m.*,u.display_name sender_name,c.type conversation_type,c.archived_at FROM chat_messages m JOIN users u ON u.id=m.sender_user_id JOIN chat_conversations c ON c.id=m.conversation_id WHERE m.id=?").get(messageId);if(!row)return null;if(row.conversation_type==='group'){var a=groups.requireMember(row.conversation_id,user);return a?{row:row,access:a}:null;}var c=deps.canUseConversation(user,row.conversation_id);return c?{row:row,access:null}:null;}
  function event(id,type,payload,exclude){groups.emitToMembers(id,type,payload,exclude);}
  function mentionIds(text,id,allow){if(!allow)return[];var names=[],re=/(^|\s)@([\w.\-\u0600-\u06ff]{2,40})/g,m;while((m=re.exec(text)))names.push(m[2]);if(!names.length)return[];var marks=names.map(function(){return'?';}).join(','),stmt=db.prepare("SELECT u.id FROM users u JOIN conversation_members cm ON cm.user_id=u.id WHERE cm.conversation_id=? AND u.username IN ("+marks+")");return stmt.all.apply(stmt,[id].concat(names)).map(function(x){return x.id;});}
  function addMessage(id,user,type,text,payload,reply){var a=groups.requireMember(id,user);if(!a)return null;if(a.member.role==='member'&&!a.permissions.members_can_send_messages)throw ['FORBIDDEN','ارسال پیام برای اعضا غیرفعال است.'];var mid=security.id('msg'),t=now(),mentions=mentionIds(text,id,a.member.role!=='member'||a.permissions.members_can_use_mentions);db.exec('BEGIN');try{db.prepare("INSERT INTO chat_messages (id,conversation_id,sender_user_id,sender_role,message_text,reply_to_id,created_at,message_type,payload_json) VALUES (?,?,?,?,?,?,?,?,?)").run(mid,id,user.id,user.role,text,reply||null,t,type,JSON.stringify(payload||{}));mentions.forEach(function(uid){db.prepare("INSERT OR IGNORE INTO message_mentions (message_id,user_id,created_at) VALUES (?,?,?)").run(mid,uid,t);});db.prepare("UPDATE chat_conversations SET updated_at=?,last_message_at=? WHERE id=?").run(t,t,id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}var row=db.prepare("SELECT m.*,u.display_name sender_name FROM chat_messages m JOIN users u ON u.id=m.sender_user_id WHERE m.id=?").get(mid),item=mapMessage(row,user);event(id,'chat.message.created',item,user.id);mentions.forEach(function(uid){deps.realtime.emitUser(db,uid,'chat.mention.created',item,now);});return item;}

  router.add('GET',/^\/api\/v1\/chat\/conversations$/,['admin','student'],function(req,res,match,body,user){var q=query(req),groupPage=groups.list(user,q.limit,q.offset,q.search),items=groupPage.items;if(user.role==='student'){var direct=deps.getOrCreateConversation(user.student_id);items=[{id:direct.id,type:'direct',title:'گفتگو با مشاور',description:'',role:'member',unread:deps.conversationUnread(direct.id,user),lastMessage:null}].concat(items);}ok(res,{items:items,total:groupPage.total+(user.role==='student'?1:0),hasMore:groupPage.hasMore,nextOffset:groupPage.nextOffset});});
  router.add('GET',/^\/api\/v1\/chat\/users$/,['admin','student'],function(req,res,m,b,user){var q=query(req),term=str(q.search,100),limit=Math.min(30,Math.max(1,Number(q.limit)||15));if(!term)return ok(res,[]);ok(res,db.prepare("SELECT id,username,display_name AS name,role AS accountRole FROM users WHERE is_active=1 AND id<>? AND (display_name LIKE ? OR username LIKE ?) ORDER BY display_name LIMIT ?").all(user.id,'%'+term+'%','%'+term+'%',limit));});
  router.add('POST',/^\/api\/v1\/chat\/groups$/,['admin','student'],function(req,res,match,body,user){if(!bucketAllow('group-create:'+user.id,env.chatGroupCreatesPerHour,3600000))return fail(res,429,'RATE_LIMITED','تعداد ساخت گروه بیش از حد مجاز است.');try{var item=groups.create(user,body||{});audit(user,'CHAT_GROUP_CREATED','chat_conversation',item.id,{title:item.title});ok(res,item,201);}catch(e){if(Array.isArray(e))return fail(res,e[0]==='FORBIDDEN'?403:400,e[0],e[1]);throw e;}});
  router.add('GET',/^\/api\/v1\/chat\/conversations\/([^/]+)$/,['admin','student'],function(req,res,m,b,user){var d=groups.detail(m[1],user);if(!d)return missing(res);ok(res,d);});
  router.add('GET',/^\/api\/v1\/chat\/groups\/([^/]+)\/members$/,['admin','student'],function(req,res,m,b,user){var q=query(req),rows=groups.members(m[1],user,q.search,q.limit);if(!rows)return missing(res);ok(res,rows);});
  router.add('GET',/^\/api\/v1\/chat\/groups\/([^/]+)\/candidates$/,['admin','student'],function(req,res,m,b,user){var q=query(req),rows=groups.candidates(m[1],user,q.search,q.limit);if(!rows)return denied(res);ok(res,rows);});
  router.add('POST',/^\/api\/v1\/chat\/groups\/([^/]+)\/members$/,['admin','student'],function(req,res,m,body,user){var a=groups.requireMember(m[1],user);if(!a)return missing(res);if(!groups.canManage(a.member)&&!a.permissions.members_can_add_members)return denied(res);var uid=str(body.userId,120),target=groups.userSummary(uid);if(!target)return missing(res);if(db.prepare("SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=?").get(m[1],uid))return fail(res,409,'CONFLICT','این کاربر عضو گروه است.');var count=db.prepare("SELECT COUNT(*) n FROM conversation_members WHERE conversation_id=?").get(m[1]).n;if(count>=env.chatMaxGroupMembers)return fail(res,400,'VALIDATION','ظرفیت گروه تکمیل است.');db.prepare("INSERT INTO conversation_members (conversation_id,user_id,role,joined_at,invited_by) VALUES (?,?,?,?,?)").run(m[1],uid,'member',now(),user.id);groups.systemMessage(m[1],user,target.name+' به گروه اضافه شد.',{action:'member_added',userId:uid});event(m[1],'chat.member.added',{conversationId:m[1],member:target},null);audit(user,'CHAT_MEMBER_ADDED','chat_conversation',m[1],{userId:uid});ok(res,target,201);});
  router.add('DELETE',/^\/api\/v1\/chat\/groups\/([^/]+)\/members\/([^/]+)$/,['admin','student'],function(req,res,m,b,user){var a=groups.requireMember(m[1],user),target=groups.member(m[1],m[2]);if(!a||!target)return missing(res);if(!groups.canManage(a.member)||target.role==='owner'||(a.member.role==='admin'&&target.role!=='member'))return denied(res);db.prepare("DELETE FROM conversation_members WHERE conversation_id=? AND user_id=?").run(m[1],m[2]);event(m[1],'chat.member.removed',{conversationId:m[1],userId:m[2]},null);audit(user,'CHAT_MEMBER_REMOVED','chat_conversation',m[1],{userId:m[2]});ok(res,{removed:true});});
  router.add('PATCH',/^\/api\/v1\/chat\/groups\/([^/]+)\/members\/([^/]+)$/,['admin','student'],function(req,res,m,body,user){var a=groups.requireMember(m[1],user),target=groups.member(m[1],m[2]),role=str(body.role,20);if(!a||!target)return missing(res);if(a.member.role!=='owner'||target.role==='owner'||['admin','member'].indexOf(role)<0)return denied(res);db.prepare("UPDATE conversation_members SET role=? WHERE conversation_id=? AND user_id=?").run(role,m[1],m[2]);event(m[1],'chat.member.role_changed',{conversationId:m[1],userId:m[2],role:role},null);audit(user,'CHAT_MEMBER_ROLE_CHANGED','chat_conversation',m[1],{userId:m[2],role:role});ok(res,{userId:m[2],role:role});});
  router.add('POST',/^\/api\/v1\/chat\/groups\/([^/]+)\/transfer-owner$/,['admin','student'],function(req,res,m,body,user){var a=groups.requireMember(m[1],user),uid=str(body.userId,120),target=groups.member(m[1],uid);if(!a||!target)return missing(res);if(a.member.role!=='owner'||uid===user.id)return denied(res);db.exec('BEGIN');try{db.prepare("UPDATE conversation_members SET role='admin' WHERE conversation_id=? AND user_id=?").run(m[1],user.id);db.prepare("UPDATE conversation_members SET role='owner' WHERE conversation_id=? AND user_id=?").run(m[1],uid);db.prepare("UPDATE chat_conversations SET owner_user_id=?,updated_at=? WHERE id=?").run(uid,now(),m[1]);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}event(m[1],'chat.owner.transferred',{conversationId:m[1],oldOwnerId:user.id,ownerId:uid},null);audit(user,'CHAT_OWNER_TRANSFERRED','chat_conversation',m[1],{ownerId:uid});ok(res,{ownerId:uid,myRole:'admin'});});
  router.add('POST',/^\/api\/v1\/chat\/groups\/([^/]+)\/leave$/,['admin','student'],function(req,res,m,b,user){var a=groups.requireMember(m[1],user);if(!a)return missing(res);if(a.member.role==='owner')return fail(res,409,'OWNER_MUST_TRANSFER','ابتدا مالکیت گروه را منتقل کنید.');db.prepare("DELETE FROM conversation_members WHERE conversation_id=? AND user_id=?").run(m[1],user.id);event(m[1],'chat.member.removed',{conversationId:m[1],userId:user.id},user.id);ok(res,{left:true});});
  router.add('PATCH',/^\/api\/v1\/chat\/groups\/([^/]+)$/,['admin','student'],function(req,res,m,body,user){var a=groups.requireMember(m[1],user);if(!a)return missing(res);if(!groups.canManage(a.member))return denied(res);var title=body.title==null?a.conversation.title:String(body.title).trim(),description=body.description==null?(a.conversation.description||''):String(body.description).trim();if(title.length<2||title.length>env.chatMaxGroupName||description.length>env.chatMaxGroupDescription)return fail(res,400,'VALIDATION','نام یا توضیحات گروه معتبر نیست.');if(body.archived&&a.member.role!=='owner')return denied(res);db.prepare("UPDATE chat_conversations SET title=?,description=?,archived_at=?,updated_at=? WHERE id=?").run(title,description||null,body.archived?now():a.conversation.archived_at,now(),m[1]);event(m[1],'chat.conversation.updated',{conversationId:m[1],title:title,description:description,archived:!!body.archived},null);ok(res,groups.detail(m[1],user));});
  router.add('PATCH',/^\/api\/v1\/chat\/groups\/([^/]+)\/permissions$/,['admin','student'],function(req,res,m,body,user){var a=groups.requireMember(m[1],user);if(!a)return missing(res);if(a.member.role!=='owner')return denied(res);var keys=Object.keys(groups.DEFAULTS),sets=[],args=[];keys.forEach(function(k){if(Object.prototype.hasOwnProperty.call(body,k)){sets.push(k+'=?');args.push(body[k]?1:0);}});if(sets.length){args.push(m[1]);var stmt=db.prepare("UPDATE conversation_permissions SET "+sets.join(',')+" WHERE conversation_id=?");stmt.run.apply(stmt,args);}event(m[1],'chat.conversation.updated',{conversationId:m[1],permissions:groups.permissions(m[1])},null);ok(res,groups.permissions(m[1]));});
  router.add('PATCH',/^\/api\/v1\/chat\/conversations\/([^/]+)\/mute$/,['admin','student'],function(req,res,m,body,user){var a=groups.requireMember(m[1],user);if(!a)return missing(res);db.prepare("UPDATE conversation_members SET muted=? WHERE conversation_id=? AND user_id=?").run(body.muted?1:0,m[1],user.id);ok(res,{muted:!!body.muted});});

  router.add('PATCH',/^\/api\/v1\/chat\/messages\/([^/]+)$/,['admin','student'],function(req,res,m,body,user){var found=accessMessage(m[1],user);if(!found)return missing(res);var row=found.row,text=String(body.text||'').trim();if(!text||text.length>3000)return fail(res,400,'VALIDATION','متن پیام معتبر نیست.');var allowed=row.sender_user_id===user.id;if(found.access&&found.access.member.role==='member'&&!found.access.permissions.members_can_edit_own_messages)allowed=false;if(row.deleted_at||!allowed)return denied(res);db.prepare("UPDATE chat_messages SET message_text=?,edited_at=? WHERE id=?").run(text,now(),row.id);var updated=accessMessage(row.id,user).row,item=mapMessage(updated,user);if(found.access)event(row.conversation_id,'chat.message.edited',item,user.id);audit(user,'CHAT_MESSAGE_EDITED','chat_message',row.id,{});ok(res,item);});
  router.add('DELETE',/^\/api\/v1\/chat\/messages\/([^/]+)$/,['admin','student'],function(req,res,m,b,user){var found=accessMessage(m[1],user);if(!found)return missing(res);var row=found.row,allowed=row.sender_user_id===user.id;if(found.access){if(found.access.member.role==='member'&&!found.access.permissions.members_can_delete_own_messages)allowed=false;if(groups.canManage(found.access.member)&&found.access.permissions.admins_can_delete_messages)allowed=true;}if(row.deleted_at||!allowed)return denied(res);var t=now();db.prepare("UPDATE chat_messages SET deleted_at=?,message_text='' WHERE id=?").run(t,row.id);var payload={id:row.id,conversationId:row.conversation_id,deletedAt:t};if(found.access)event(row.conversation_id,'chat.message.deleted',payload,user.id);audit(user,'CHAT_MESSAGE_DELETED','chat_message',row.id,{});ok(res,payload);});
  router.add('POST',/^\/api\/v1\/chat\/messages\/([^/]+)\/reactions$/,['admin','student'],function(req,res,m,body,user){var found=accessMessage(m[1],user),emoji=String(body.emoji||'').trim();if(!found)return missing(res);if(!/^(?:[\u00a9\u00ae\u203c-\u3299]|[\ud83c-\ud83e][\udc00-\udfff])(?:\ufe0f|\u200d|[\ud83c][\udffb-\udfff]){0,4}$/u.test(emoji))return fail(res,400,'VALIDATION','واکنش معتبر نیست.');if(found.access&&found.access.member.role==='member'&&!found.access.permissions.members_can_react)return denied(res);db.prepare("INSERT OR IGNORE INTO message_reactions (message_id,user_id,emoji,created_at) VALUES (?,?,?,?)").run(m[1],user.id,emoji,now());var item=mapMessage(accessMessage(m[1],user).row,user);if(found.access)event(found.row.conversation_id,'chat.reaction.updated',{conversationId:found.row.conversation_id,messageId:m[1],reactions:item.reactions},user.id);ok(res,item.reactions,201);});
  router.add('DELETE',/^\/api\/v1\/chat\/messages\/([^/]+)\/reactions\/([^/]+)$/,['admin','student'],function(req,res,m,b,user){var found=accessMessage(m[1],user);if(!found)return missing(res);db.prepare("DELETE FROM message_reactions WHERE message_id=? AND user_id=? AND emoji=?").run(m[1],user.id,decodeURIComponent(m[2]));var item=mapMessage(accessMessage(m[1],user).row,user);if(found.access)event(found.row.conversation_id,'chat.reaction.updated',{conversationId:found.row.conversation_id,messageId:m[1],reactions:item.reactions},user.id);ok(res,item.reactions);});

  function shareRoute(regex,type,permission,builder){router.add('POST',regex,['student'],function(req,res,m,body,user){var a=groups.requireMember(m[1],user);if(!a)return missing(res);if(a.member.role==='member'&&!a.permissions[permission])return denied(res);try{var snap=builder(user,body||{});var item=addMessage(m[1],user,type,'',snap,null);audit(user,'CHAT_SNAPSHOT_SHARED','chat_message',item.id,{type:type,fields:Object.keys(snap)});ok(res,item,201);}catch(e){if(Array.isArray(e))return fail(res,400,e[0],e[1]);throw e;}});}
  shareRoute(/^\/api\/v1\/chat\/conversations\/([^/]+)\/share\/study-state$/,'study_state','members_can_share_study_state',function(user,body){var allowed=['studyMinutes','planProgress','testCount','reviews'],selected=Array.isArray(body.fields)?body.fields.filter(function(x){return allowed.indexOf(x)>=0;}):[];if(!selected.length)throw ['VALIDATION','حداقل یک مورد را انتخاب کنید.'];var out={label:'وضعیت امروز',sharedAt:now()},sid=user.student_id,bounds=deps.iranDayBounds(deps.todayIso());if(selected.indexOf('studyMinutes')>=0)out.studyMinutes=Number(db.prepare("SELECT COALESCE(SUM(actual_minutes),0) n FROM study_sessions WHERE student_id=? AND status='finished' AND started_at>=? AND started_at<?").get(sid,bounds.start,bounds.end).n);if(selected.indexOf('testCount')>=0){var q=db.prepare("SELECT COALESCE(SUM(correct+wrong+blank),0) n FROM quiz_attempts WHERE student_id=? AND submitted_at>=? AND submitted_at<?").get(sid,bounds.start,bounds.end);out.testCount=Number(q.n);}if(selected.indexOf('planProgress')>=0){var p=db.prepare("SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN tc.status='done' THEN 1 ELSE 0 END),0) done FROM tasks t JOIN plans p ON p.id=t.plan_id LEFT JOIN task_completions tc ON tc.task_id=t.id AND tc.student_id=p.student_id WHERE p.student_id=? AND p.plan_date=?").get(sid,deps.todayIso());out.plan={done:Number(p.done),total:Number(p.total)};}if(selected.indexOf('reviews')>=0)out.reviews=Number(db.prepare("SELECT COUNT(*) n FROM learning_items WHERE student_id=? AND status='pending' AND due_date<=?").get(sid,deps.todayIso()).n);return out;});
  shareRoute(/^\/api\/v1\/chat\/conversations\/([^/]+)\/share\/exam-result$/,'exam_result','members_can_share_exam_results',function(user,body){var id=str(body.attemptId,120),sql="SELECT qa.id,qa.correct,qa.wrong,qa.blank,qa.percent,qa.duration_seconds,COALESCE(e.title,q.title) title FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id LEFT JOIN exams e ON e.id=q.exam_id WHERE qa.student_id=?",args=[user.student_id];if(id){sql+=" AND qa.id=?";args.push(id);}sql+=" ORDER BY qa.submitted_at DESC LIMIT 1";var stmt=db.prepare(sql),a=stmt.get.apply(stmt,args);if(!a)throw ['NOT_FOUND','نتیجه آزمون پیدا نشد.'];return {title:a.title||'آزمون',percent:a.percent,correct:a.correct,wrong:a.wrong,blank:a.blank,durationMinutes:Math.round(Number(a.duration_seconds||0)/60),sharedAt:now()};});
  shareRoute(/^\/api\/v1\/chat\/conversations\/([^/]+)\/share\/study-time$/,'study_time','members_can_share_study_state',function(user,body){var days=Math.min(31,Math.max(1,Number(body.days)||7)),rows=db.prepare("SELECT substr(started_at,1,10) day,SUM(actual_minutes) minutes FROM study_sessions WHERE student_id=? AND status='finished' AND started_at>=datetime('now',?) GROUP BY substr(started_at,1,10) ORDER BY day").all(user.student_id,'-'+days+' days');return {label:days===1?'امروز':'بازه '+days+' روزه',days:rows,totalMinutes:rows.reduce(function(n,x){return n+Number(x.minutes||0);},0),sharedAt:now()};});
  shareRoute(/^\/api\/v1\/chat\/conversations\/([^/]+)\/share\/current-activity$/,'current_activity','members_can_share_study_state',function(user){var s=db.prepare("SELECT ss.started_at,ss.actual_minutes,t.title,t.subject FROM study_sessions ss LEFT JOIN tasks t ON t.id=ss.task_id WHERE ss.student_id=? AND ss.status='active' ORDER BY ss.started_at DESC LIMIT 1").get(user.student_id);if(!s)throw ['NOT_FOUND','فعالیت در حال اجرا پیدا نشد.'];return {title:s.title||'مطالعه',subject:s.subject||'',startedAt:s.started_at,minutes:Math.max(Number(s.actual_minutes||0),Math.floor((Date.now()-new Date(s.started_at).getTime())/60000)),sharedAt:now()};});
  shareRoute(/^\/api\/v1\/chat\/conversations\/([^/]+)\/share\/learning-item$/,'learning_item','members_can_share_learning_progress',function(user,body){var id=str(body.itemId,120),x=id?db.prepare("SELECT id,subject,book,chapter,lesson,topic,title,note,hint FROM learning_items WHERE id=? AND student_id=?").get(id,user.student_id):db.prepare("SELECT id,subject,book,chapter,lesson,topic,title,note,hint FROM learning_items WHERE student_id=? ORDER BY updated_at DESC LIMIT 1").get(user.student_id);if(!x)throw ['NOT_FOUND','مورد یادگیری پیدا نشد.'];var out={subject:x.subject||'',book:x.book||'',chapter:x.chapter||'',lesson:x.lesson||'',topic:x.topic||'',title:x.title,sharedAt:now()};if(body.includeNote)out.note=x.note||'';if(body.includeHint)out.hint=x.hint||'';return out;});
}
module.exports=registerGroupChatRoutes;
