import { ArrowRight, CheckCircle2, Clock3, MinusCircle, XCircle } from 'lucide-react';
import { useState } from 'react';
import { apiClient } from '../../../services/api-client';

type SubjectResult = { subject: string; percentage: number; correct: number; wrong: number; unanswered: number; total: number };
type ReviewItem = { questionId: string; question: string; selectedOption: string | null; correctOption: string; explanation?: string; isCorrect: boolean; subject?: string; topic?: string };
export type ExamResultData = { id: string; status?: 'calculating' | 'preliminary' | 'released' | 'withheld'; score?: number | null; correct?: number; wrong?: number; unanswered?: number; total: number; finishedAt?: string; subjects?: SubjectResult[]; review?: ReviewItem[] };

export function ExamResult({ result, onBack }: { result: ExamResultData; onBack: () => void }) {
  if (result.status && result.status !== 'released' && result.status !== 'preliminary') return <section className="mx-auto max-w-xl space-y-4"><button className="back-action" onClick={onBack}><ArrowRight />بازگشت</button><article className="surface rounded-3xl p-6 text-center"><Clock3 className="mx-auto size-10 text-saffron" /><h1 className="mt-3 text-xl font-black">پاسخ‌ها ثبت شد</h1><p className="mt-2 text-sm leading-7 text-ink/60">{result.status === 'withheld' ? 'نتیجه این آزمون فعلاً قابل نمایش نیست.' : 'نتیجه در حال محاسبه است و پس از انتشار برگزارکننده نمایش داده می‌شود.'}</p>{result.finishedAt ? <code className="mt-4 block text-xs text-ink/50">{result.id} · {formatDate(result.finishedAt)}</code> : null}</article></section>;
  const correct = result.correct || 0;
  const wrong = result.wrong ?? Math.max(0, result.total - correct - (result.unanswered || 0));
  const unanswered = result.unanswered ?? Math.max(0, result.total - correct - wrong);
  return <section className="mx-auto max-w-xl space-y-4 pb-6"><button className="back-action" onClick={onBack}><ArrowRight />بازگشت به آزمون‌ها</button><header className="rounded-[1.75rem] bg-gradient-to-br from-mint to-[#2f6e60] p-6 text-white"><span className="text-xs text-white/70">نتیجه آزمون</span><strong className="mt-2 block text-5xl font-black">{toPersian(result.score ?? 0)}٪</strong><p className="mt-2 text-sm text-white/75">{result.status === 'preliminary' ? 'نتیجه اولیه' : 'نتیجه منتشرشده'}</p></header><div className="grid grid-cols-3 gap-2"><Metric icon={<CheckCircle2 />} label="درست" value={correct} className="text-emerald-700" /><Metric icon={<XCircle />} label="غلط" value={wrong} className="text-rose-700" /><Metric icon={<MinusCircle />} label="نزده" value={unanswered} className="text-slate-600" /></div><p className="rounded-2xl bg-sky-50 p-4 text-sm leading-7 text-sky-900">هنوز داده کافی برای محاسبه تراز و رتبه وجود ندارد.</p>{result.subjects?.length ? <SubjectAnalysis subjects={result.subjects} /> : null}{result.review?.length ? <Review items={result.review} /> : null}</section>;
}

function SubjectAnalysis({ subjects }: { subjects: SubjectResult[] }) { return <section aria-labelledby="subject-analysis-title"><h2 id="subject-analysis-title" className="mb-3 font-black">تحلیل درس‌ها</h2><div className="space-y-3">{subjects.map((item) => <article key={item.subject} className="surface rounded-2xl p-4"><div className="flex items-center justify-between"><strong>{item.subject}</strong><span className="font-black text-mint">{toPersian(item.percentage)}٪</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-ink/10"><span className="block h-full rounded-full bg-mint" style={{ width: `${Math.max(0, Math.min(100, item.percentage))}%` }} /></div><p className="mt-2 text-xs text-ink/55">{toPersian(item.correct)} درست · {toPersian(item.wrong)} غلط · {toPersian(item.unanswered)} نزده</p></article>)}</div></section>; }
function Review({ items }: { items: ReviewItem[] }) { return <section><h2 className="mb-3 font-black">پاسخ تشریحی</h2><div className="space-y-3">{items.map((item, index) => <article key={item.questionId} className="surface rounded-3xl p-4"><div className="flex gap-2">{item.isCorrect ? <CheckCircle2 className="mt-1 shrink-0 text-emerald-600" /> : <XCircle className="mt-1 shrink-0 text-rose-600" />}<div className="min-w-0 flex-1"><strong>سؤال {toPersian(index + 1)}</strong>{item.subject || item.topic ? <p className="mt-1 text-xs text-mint">{[item.subject, item.topic].filter(Boolean).join(' · ')}</p> : null}<p className="mt-2 text-sm leading-7">{item.question}</p><p className="mt-3 text-xs text-ink/60">پاسخ شما: {optionLabel(item.selectedOption)} · پاسخ درست: {optionLabel(item.correctOption)}</p>{item.explanation ? <p className="mt-3 rounded-2xl bg-paper p-3 text-sm leading-7">{item.explanation}</p> : null}{!item.isCorrect ? <MistakeReason questionId={item.questionId} /> : null}</div></div></article>)}</div></section>; }
const reasons = ['بی‌دقتی', 'بلد نبودم', 'شک بین گزینه‌ها', 'کمبود زمان', 'محاسبات', 'فراموشی'];
function MistakeReason({ questionId }: { questionId: string }) { const [state, setState] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle'); async function classify(reason: string) { setState('saving'); try { await apiClient.request('PATCH', `/student/mistakes/question/${questionId}`, { reason }); setState('saved'); } catch { setState('error'); } } return <div className="mt-4"><label className="text-xs font-bold" htmlFor={`mistake-${questionId}`}>دلیل اشتباه</label><select id={`mistake-${questionId}`} className="mt-2 w-full rounded-xl border border-ink/15 bg-white px-3 py-3 text-sm" defaultValue="" disabled={state === 'saving'} onChange={(event) => void classify(event.target.value)}><option value="" disabled>انتخاب دلیل</option>{reasons.map((reason) => <option key={reason}>{reason}</option>)}</select>{state === 'saved' ? <p className="mt-2 text-xs text-emerald-700">به مرور اشتباهات افزوده شد.</p> : state === 'error' ? <p className="mt-2 text-xs text-rose-700">ثبت دلیل ناموفق بود؛ دوباره تلاش کن.</p> : null}</div>; }
function Metric({ icon, label, value, className }: { icon: React.ReactNode; label: string; value: number; className: string }) { return <div className={`surface rounded-2xl p-3 text-center ${className}`}><span className="mx-auto block w-fit [&>svg]:size-5">{icon}</span><strong className="mt-1 block text-xl">{toPersian(value)}</strong><span className="text-xs">{label}</span></div>; }
function optionLabel(value?: string | null) { const index = ['a', 'b', 'c', 'd'].indexOf(value || ''); return index >= 0 ? `گزینه ${toPersian(index + 1)}` : 'بدون پاسخ'; }
function toPersian(value: number) { return new Intl.NumberFormat('fa-IR').format(value); }
function formatDate(value: string) { return new Intl.DateTimeFormat('fa-IR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
