import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { ApiException } from "../../common/exceptions/api.exception";
import { Organization } from "../../database/entities/organization.entity";
import { Student } from "../../database/entities/student.entity";
import { RelationshipStatus, UserRelationship } from "../../database/entities/user-relationship.entity";
import { User } from "../../database/entities/user.entity";
import { AuthenticatedUser } from "../auth/auth.service";
import { CreateRelationshipDto, UpdateRelationshipDto } from "./dto/relationship.dto";

@Injectable()
export class RelationshipsService {
  constructor(@InjectRepository(UserRelationship) private relationships: Repository<UserRelationship>, @InjectRepository(User) private users: Repository<User>, @InjectRepository(Student) private students: Repository<Student>, @InjectRepository(Organization) private organizations: Repository<Organization>) {}
  private platform(user: AuthenticatedUser) { return user.roles?.includes("PLATFORM_ADMIN"); }
  private canManage(user: AuthenticatedUser, organizationId?: string | null) { return this.platform(user) || Boolean(organizationId && user.organizationIds?.includes(organizationId) && user.capabilities?.includes("organization.members.manage")); }
  async list(user: AuthenticatedUser) { const where = this.platform(user) ? {} : { fromUser: { id: user.id } }; return this.relationships.find({ where, relations: { fromUser: true, toStudent: true, organization: true }, order: { createdAt: "DESC" } }).then((items) => items.map(this.project)); }
  async get(user: AuthenticatedUser, id: string) { const item = await this.relationships.findOne({ where: { id }, relations: { fromUser: true, toStudent: true, organization: true } }); if (!item) throw new ApiException(404, "NOT_FOUND", "رابطه یافت نشد."); if (item.fromUser.id !== user.id && !this.canManage(user, item.organization?.id)) throw new ApiException(404, "NOT_FOUND", "رابطه یافت نشد."); return this.project(item); }
  async create(user: AuthenticatedUser, dto: CreateRelationshipDto) { if (!this.canManage(user, dto.organizationId)) throw new ApiException(403, "FORBIDDEN", "ایجاد این رابطه مجاز نیست."); const [fromUser, student, organization] = await Promise.all([this.users.findOne({ where: { id: dto.fromUserId } }), this.students.findOne({ where: { id: dto.toStudentId } }), dto.organizationId ? this.organizations.findOne({ where: { id: dto.organizationId } }) : Promise.resolve(null)]); if (!fromUser || !student || (dto.organizationId && !organization)) throw new ApiException(404, "NOT_FOUND", "کاربر، دانش‌آموز یا سازمان یافت نشد."); const existing = await this.relationships.findOne({ where: { fromUser: { id: dto.fromUserId }, toStudent: { id: dto.toStudentId }, organization: dto.organizationId ? { id: dto.organizationId } : undefined, type: dto.type } }); if (existing && ![RelationshipStatus.REJECTED, RelationshipStatus.REVOKED].includes(existing.status)) throw new ApiException(409, "RELATIONSHIP_EXISTS", "این رابطه از قبل وجود دارد."); const item = existing ?? this.relationships.create({ fromUser, toStudent: student, organization, type: dto.type }); item.status = RelationshipStatus.PENDING; item.acceptedAt = null; item.revokedAt = null; return this.relationships.save(item).then(this.project); }
  async update(user: AuthenticatedUser, id: string, dto: UpdateRelationshipDto) { const item = await this.relationships.findOne({ where: { id }, relations: { fromUser: true, organization: true } }); if (!item) throw new ApiException(404, "NOT_FOUND", "رابطه یافت نشد."); const selfDecision = item.fromUser.id === user.id && [RelationshipStatus.ACTIVE, RelationshipStatus.REJECTED].includes(dto.status); if (!selfDecision && !this.canManage(user, item.organization?.id)) throw new ApiException(403, "FORBIDDEN", "تغییر این رابطه مجاز نیست."); item.status = dto.status; item.acceptedAt = dto.status === RelationshipStatus.ACTIVE ? new Date() : item.acceptedAt; item.revokedAt = dto.status === RelationshipStatus.REVOKED ? new Date() : null; return this.relationships.save(item).then(this.project); }
  remove(user: AuthenticatedUser, id: string) { return this.update(user, id, { status: RelationshipStatus.REVOKED }); }
  async forStudent(user: AuthenticatedUser, studentId: string) { const self = await this.students.findOne({ where: { id: studentId, user: { id: user.id } } }); const allowed = Boolean(self) || this.platform(user) || Boolean(await this.relationships.findOne({ where: { fromUser: { id: user.id }, toStudent: { id: studentId }, status: RelationshipStatus.ACTIVE } })); if (!allowed) throw new ApiException(404, "NOT_FOUND", "دانش‌آموز یافت نشد."); return this.relationships.find({ where: { toStudent: { id: studentId }, status: RelationshipStatus.ACTIVE }, relations: { fromUser: true, organization: true } }).then((items) => items.map(this.project)); }
  async myStudents(user: AuthenticatedUser) { const own = user.roles?.includes("STUDENT") ? await this.students.find({ where: { user: { id: user.id } } }) : []; const links = await this.relationships.find({ where: { fromUser: { id: user.id }, status: RelationshipStatus.ACTIVE }, relations: { toStudent: true, organization: true } }); return [...own.map((student) => ({ student: { id: student.id, name: student.name }, relationship: { type: "SELF", status: "ACTIVE" } })), ...links.map((link) => ({ student: { id: link.toStudent.id, name: link.toStudent.name }, relationship: { id: link.id, type: link.type, status: link.status, organizationId: link.organization?.id ?? null } }))]; }
  private project(item: UserRelationship) { return { id: item.id, type: item.type, status: item.status, fromUser: { id: item.fromUser.id, username: item.fromUser.username, firstName: item.fromUser.firstName, lastName: item.fromUser.lastName }, student: item.toStudent ? { id: item.toStudent.id, name: item.toStudent.name } : undefined, organizationId: item.organization?.id ?? null, createdAt: item.createdAt, acceptedAt: item.acceptedAt, revokedAt: item.revokedAt }; }
}
